<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>BlueOath.Server</AssemblyName>
    <RootNamespace>BlueOath.Server</RootNamespace>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueOath.Core\BlueOath.Core.csproj" />
    <ProjectReference Include="..\BlueOath.Protocol\BlueOath.Protocol.csproj" />
    <ProjectReference Include="..\BlueOath.Storage\BlueOath.Storage.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="announcements.json" />
    <EmbeddedResource Include="gm-goods.json" />
    <EmbeddedResource Include="gm-mails.json" />
  </ItemGroup>
</Project>
