using Microsoft.Data.Sqlite;
using System.Text;
using System.Text.Json;

static class ConfigClassTool
{
    private const byte XorKey = 0x55;

    public static int RunAsync(string[] args)
    {
        var region = ReadArg(args, "--region=") ?? "jp";
        var configRoot = ResolveConfigRoot(args, region);
        var output = Path.GetFullPath(ReadArg(args, "--output=") ?? Path.Combine(FindRoot(), "config-cs"));
        var ns = ReadArg(args, "--namespace=") ?? "BlueOath.Server.Configs";

        var summary = Generate(configRoot, output, ns);
        Console.WriteLine(JsonSerializer.Serialize(new
        {
            complete = true,
            action = "config-cs",
            region,
            configRoot = Path.GetFullPath(configRoot),
            output,
            ns,
            summary.Classes,
            summary.Fields
        }));
        return 0;
    }

    private static GenerationSummary Generate(string configRoot, string outputDir, string ns)
    {
        if (!Directory.Exists(configRoot))
            throw new DirectoryNotFoundException($"Config directory not found: {configRoot}");
        Directory.CreateDirectory(outputDir);
        foreach (var stale in Directory.EnumerateFiles(outputDir, "Config*.cs"))
            File.Delete(stale);

        var classes = 0;
        var fields = 0;
        var usedClassNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var dbPath in Directory.EnumerateFiles(configRoot, "config_*.db")
                     .OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
        {
            fields += GenerateTable(dbPath, outputDir, ns, usedClassNames);
            classes++;
        }
        return new GenerationSummary(classes, fields);
    }

    private static int GenerateTable(string dbPath, string outputDir, string ns, HashSet<string> usedClassNames)
    {
        var table = Path.GetFileNameWithoutExtension(dbPath);
        var root = new ConfigSchema.Node();
        var rows = 0;

        using (var connection = OpenReadOnly(dbPath))
        using (var command = connection.CreateCommand())
        {
            command.CommandText = "SELECT jsonbytes FROM DBObject WHERE CAST(id AS TEXT) <> 'nill'";
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                using var document = JsonDocument.Parse(Xor(ReadBytes(reader, 0)));
                ConfigSchema.Merge(root, document.RootElement);
                rows++;
            }
        }

        var className = UniqueName(usedClassNames, ToPascalCase(table));
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// Table: {table} (rows: {rows})");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine();
        builder.AppendLine($"namespace {ns};");
        builder.AppendLine();
        builder.AppendLine($"public class {className}");
        builder.AppendLine("{");

        var used = new HashSet<string>(StringComparer.Ordinal);
        var fieldCount = 0;
        foreach (var field in root.Fields.OrderBy(f => f.Key, StringComparer.Ordinal))
        {
            var candidate = ToPascalCase(field.Key);
            if (ReservedPropertyNames.Contains(candidate)) candidate += "Value";
            var propertyName = UniqueName(used, candidate);
            var type = RenderField(field.Value);
            builder.AppendLine($"    [JsonPropertyName({JsonSerializer.Serialize(field.Key)})]");
            builder.AppendLine($"    public {type} {propertyName} {{ get; set; }}");
            fieldCount++;
        }

        builder.AppendLine("}");
        File.WriteAllText(Path.Combine(outputDir, className + ".cs"), builder.ToString(), new UTF8Encoding(false));
        return fieldCount;
    }

    private static string RenderField(ConfigSchema.Node node)
    {
        var baseType = ConfigSchema.CSharpType(node);
        if (node.HasNull || IsReference(baseType)) return baseType + "?";
        return baseType;
    }

    private static bool IsValueType(string baseType) =>
        baseType is "long" or "double" or "bool";

    private static bool IsReference(string baseType) => !IsValueType(baseType);

    private static readonly HashSet<string> ReservedPropertyNames = new(StringComparer.Ordinal)
    {
        "Equals", "GetHashCode", "GetType", "ReferenceEquals", "ToString", "MemberwiseClone", "Finalize"
    };

    private static string ToPascalCase(string name)
    {
        var builder = new StringBuilder();
        var upper = true;
        foreach (var ch in name)
        {
            if (ch == '_' || !char.IsLetterOrDigit(ch))
            {
                upper = true;
                continue;
            }
            builder.Append(upper ? char.ToUpperInvariant(ch) : ch);
            upper = false;
        }
        var result = builder.ToString();
        if (result.Length == 0) result = "Value";
        if (char.IsDigit(result[0])) result = "_" + result;
        return result;
    }

    private static string UniqueName(HashSet<string> used, string candidate)
    {
        if (used.Add(candidate)) return candidate;
        var index = 2;
        while (!used.Add(candidate + index)) index++;
        return candidate + index;
    }

    private static SqliteConnection OpenReadOnly(string path)
    {
        var builder = new SqliteConnectionStringBuilder
        {
            DataSource = path,
            Mode = SqliteOpenMode.ReadOnly,
            Pooling = false
        };
        var connection = new SqliteConnection(builder.ConnectionString);
        connection.Open();
        return connection;
    }

    private static byte[] ReadBytes(SqliteDataReader reader, int ordinal)
    {
        if (reader.IsDBNull(ordinal)) return [];
        var value = reader.GetValue(ordinal);
        return value switch
        {
            byte[] bytes => bytes,
            string text => Encoding.UTF8.GetBytes(text),
            _ => throw new InvalidDataException($"Unsupported jsonbytes SQLite type: {value.GetType().FullName}")
        };
    }

    private static byte[] Xor(ReadOnlySpan<byte> source)
    {
        var result = new byte[source.Length];
        for (var index = 0; index < source.Length; index++)
            result[index] = (byte)(source[index] ^ XorKey);
        return result;
    }

    private static string ResolveConfigRoot(string[] args, string region)
    {
        var custom = ReadArg(args, "--config-root=");
        if (!string.IsNullOrWhiteSpace(custom)) return Path.GetFullPath(custom);
        var root = FindRoot();
        return region.ToLowerInvariant() switch
        {
            "jp" => Path.Combine(root, "blueoath", "blueoath", "blueoath_Data", "StreamingAssets", "config"),
            "cn" => Path.Combine(root, "苍蓝誓约", "clsy", "clsy_Data", "StreamingAssets", "config"),
            _ => throw new ArgumentException("--region must be jp or cn")
        };
    }

    private static string FindRoot()
    {
        var current = new DirectoryInfo(Environment.CurrentDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "BlueOath.Local.sln"))) return current.FullName;
            current = current.Parent;
        }
        throw new DirectoryNotFoundException("Could not locate BlueOath.Local.sln");
    }

    private static string? ReadArg(string[] args, string prefix) =>
        args.FirstOrDefault(x => x.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))?[prefix.Length..];

    private sealed record GenerationSummary(int Classes, int Fields);
}
