// <auto-generated />
// Table: config_key_list (rows: 228)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigKeyList
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
}
