// <auto-generated />
// Table: config_magazine_page (rows: 126)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMagazinePage
{
    [JsonPropertyName("button_show")]
    public long ButtonShow { get; set; }
    [JsonPropertyName("contents_desc")]
    public string? ContentsDesc { get; set; }
    [JsonPropertyName("contents_image")]
    public string? ContentsImage { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("image_big")]
    public string? ImageBig { get; set; }
    [JsonPropertyName("magazine_info_id")]
    public long MagazineInfoId { get; set; }
    [JsonPropertyName("page_type")]
    public long PageType { get; set; }
    [JsonPropertyName("ship_fleet_id")]
    public long ShipFleetId { get; set; }
    [JsonPropertyName("task_id")]
    public List<long>? TaskId { get; set; }
}
