// <auto-generated />
// Table: config_activity (rows: 389)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigActivity
{
    [JsonPropertyName("activity_top")]
    public string? ActivityTop { get; set; }
    [JsonPropertyName("audobattle_chapter")]
    public List<long>? AudobattleChapter { get; set; }
    [JsonPropertyName("banner_goto")]
    public long BannerGoto { get; set; }
    [JsonPropertyName("banner_gotopage")]
    public string? BannerGotopage { get; set; }
    [JsonPropertyName("banner_gotopage_activity")]
    public string? BannerGotopageActivity { get; set; }
    [JsonPropertyName("banner_order")]
    public long BannerOrder { get; set; }
    [JsonPropertyName("banner_pic")]
    public string? BannerPic { get; set; }
    [JsonPropertyName("bg")]
    public string? Bg { get; set; }
    [JsonPropertyName("bg_pic")]
    public string? BgPic { get; set; }
    [JsonPropertyName("close_groupbase")]
    public List<object>? CloseGroupbase { get; set; }
    [JsonPropertyName("extra_ship_id")]
    public long ExtraShipId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_open")]
    public long IsOpen { get; set; }
    [JsonPropertyName("item_recycling_id")]
    public List<long>? ItemRecyclingId { get; set; }
    [JsonPropertyName("mail_id")]
    public long MailId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("p1")]
    public List<object>? P1 { get; set; }
    [JsonPropertyName("p10")]
    public List<object>? P10 { get; set; }
    [JsonPropertyName("p11")]
    public List<object>? P11 { get; set; }
    [JsonPropertyName("p12")]
    public List<object>? P12 { get; set; }
    [JsonPropertyName("p13")]
    public List<object>? P13 { get; set; }
    [JsonPropertyName("p14")]
    public List<List<long>>? P14 { get; set; }
    [JsonPropertyName("p2")]
    public List<object>? P2 { get; set; }
    [JsonPropertyName("p3")]
    public List<object>? P3 { get; set; }
    [JsonPropertyName("p4")]
    public List<object>? P4 { get; set; }
    [JsonPropertyName("p5")]
    public List<object>? P5 { get; set; }
    [JsonPropertyName("p6")]
    public List<object>? P6 { get; set; }
    [JsonPropertyName("p7")]
    public List<object>? P7 { get; set; }
    [JsonPropertyName("p8")]
    public List<object>? P8 { get; set; }
    [JsonPropertyName("p9")]
    public List<long>? P9 { get; set; }
    [JsonPropertyName("padding_image")]
    public string? PaddingImage { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("period_list")]
    public List<long>? PeriodList { get; set; }
    [JsonPropertyName("period_list_area")]
    public List<object>? PeriodListArea { get; set; }
    [JsonPropertyName("plot_type")]
    public long PlotType { get; set; }
    [JsonPropertyName("rank_id")]
    public long RankId { get; set; }
    [JsonPropertyName("red_dot")]
    public List<long>? RedDot { get; set; }
    [JsonPropertyName("seacopy_type")]
    public long SeacopyType { get; set; }
    [JsonPropertyName("send_reward")]
    public long SendReward { get; set; }
    [JsonPropertyName("shop_id")]
    public long ShopId { get; set; }
    [JsonPropertyName("show_function")]
    public long ShowFunction { get; set; }
    [JsonPropertyName("show_type")]
    public long ShowType { get; set; }
    [JsonPropertyName("test_buff_show")]
    public List<string>? TestBuffShow { get; set; }
    [JsonPropertyName("test_image")]
    public string? TestImage { get; set; }
    [JsonPropertyName("test_ship")]
    public List<long>? TestShip { get; set; }
    [JsonPropertyName("test_show")]
    public List<long>? TestShow { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
