// <auto-generated />
// Table: config_battle_qte_effect (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleQteEffect
{
    [JsonPropertyName("bqe_id")]
    public long BqeId { get; set; }
    [JsonPropertyName("damage_effect")]
    public double DamageEffect { get; set; }
    [JsonPropertyName("qte_step")]
    public long QteStep { get; set; }
}
