// <auto-generated />
// Table: config_eca_index (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEcaIndex
{
    [JsonPropertyName("action_id")]
    public List<long>? ActionId { get; set; }
    [JsonPropertyName("conditon_id")]
    public List<long>? ConditonId { get; set; }
    [JsonPropertyName("event_params")]
    public string? EventParams { get; set; }
    [JsonPropertyName("event_type")]
    public long EventType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
