// <auto-generated />
// Table: config_minigame_ai (rows: 31)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameAi
{
    [JsonPropertyName("area")]
    public List<double>? Area { get; set; }
    [JsonPropertyName("decs")]
    public string? Decs { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("velocity_rate")]
    public double VelocityRate { get; set; }
}
