// <auto-generated />
// Table: config_camera_info_queue (rows: 3663)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCameraInfoQueue
{
    [JsonPropertyName("camera_path")]
    public string? CameraPath { get; set; }
    [JsonPropertyName("camera_path_index")]
    public long CameraPathIndex { get; set; }
    [JsonPropertyName("camera_target")]
    public string? CameraTarget { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("focus_path_index")]
    public long FocusPathIndex { get; set; }
    [JsonPropertyName("group")]
    public string? Group { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("queue")]
    public long Queue { get; set; }
}
