// <auto-generated />
// Table: config_skill_type (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillType
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
