// <auto-generated />
// Table: config_minigame_skill (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameSkill
{
    [JsonPropertyName("buff_id")]
    public long BuffId { get; set; }
    [JsonPropertyName("effect_path")]
    public string? EffectPath { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("parameter")]
    public List<double>? Parameter { get; set; }
    [JsonPropertyName("skill_area")]
    public List<List<double>>? SkillArea { get; set; }
    [JsonPropertyName("skill_cd")]
    public long SkillCd { get; set; }
    [JsonPropertyName("skill_delay_time")]
    public double SkillDelayTime { get; set; }
}
