// <auto-generated />
// Table: config_period (rows: 751)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPeriod
{
    [JsonPropertyName("duration")]
    public long Duration { get; set; }
    [JsonPropertyName("duration_list")]
    public List<long>? DurationList { get; set; }
    [JsonPropertyName("end_time")]
    public long EndTime { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("p1")]
    public long P1 { get; set; }
    [JsonPropertyName("p2")]
    public long P2 { get; set; }
    [JsonPropertyName("p3")]
    public long P3 { get; set; }
    [JsonPropertyName("p4")]
    public long P4 { get; set; }
    [JsonPropertyName("p5")]
    public long P5 { get; set; }
    [JsonPropertyName("p6")]
    public long P6 { get; set; }
    [JsonPropertyName("start_time")]
    public long StartTime { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
