// <auto-generated />
// Table: config_buildinginfo (rows: 35)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildinginfo
{
    [JsonPropertyName("addmood")]
    public long Addmood { get; set; }
    [JsonPropertyName("addworkerhp")]
    public long Addworkerhp { get; set; }
    [JsonPropertyName("building_scene_bgm")]
    public string? BuildingSceneBgm { get; set; }
    [JsonPropertyName("building_scene_res")]
    public string? BuildingSceneRes { get; set; }
    [JsonPropertyName("buildquantity")]
    public List<long>? Buildquantity { get; set; }
    [JsonPropertyName("characters")]
    public List<long>? Characters { get; set; }
    [JsonPropertyName("desc")]
    public long Desc { get; set; }
    [JsonPropertyName("englishname")]
    public string? Englishname { get; set; }
    [JsonPropertyName("foodcost")]
    public long Foodcost { get; set; }
    [JsonPropertyName("goldaddition")]
    public long Goldaddition { get; set; }
    [JsonPropertyName("group_id")]
    public long GroupId { get; set; }
    [JsonPropertyName("heroaddition")]
    public long Heroaddition { get; set; }
    [JsonPropertyName("heronumber")]
    public long Heronumber { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("moodcost")]
    public long Moodcost { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("oiladdition")]
    public long Oiladdition { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("powercost")]
    public long Powercost { get; set; }
    [JsonPropertyName("productid")]
    public List<long>? Productid { get; set; }
    [JsonPropertyName("productiontimeless")]
    public long Productiontimeless { get; set; }
    [JsonPropertyName("productivity")]
    public long Productivity { get; set; }
    [JsonPropertyName("productmax")]
    public long Productmax { get; set; }
    [JsonPropertyName("recipe_compose")]
    public List<long>? RecipeCompose { get; set; }
    [JsonPropertyName("recipeid")]
    public List<long>? Recipeid { get; set; }
    [JsonPropertyName("reducecost")]
    public long Reducecost { get; set; }
    [JsonPropertyName("showcharacters")]
    public List<long>? Showcharacters { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("typeicon")]
    public string? Typeicon { get; set; }
    [JsonPropertyName("unlockbuilding")]
    public long Unlockbuilding { get; set; }
}
