// <auto-generated />
// Table: config_battle_ai_fleet_support (rows: 245)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiFleetSupport
{
    [JsonPropertyName("baf_id")]
    public long BafId { get; set; }
    [JsonPropertyName("bafs_id")]
    public long BafsId { get; set; }
    [JsonPropertyName("call_for_support_time")]
    public long CallForSupportTime { get; set; }
    [JsonPropertyName("support_arg")]
    public string? SupportArg { get; set; }
    [JsonPropertyName("support_type")]
    public long SupportType { get; set; }
}
