// <auto-generated />
// Table: config_testship_task (rows: 41)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTestshipTask
{
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("go_up_to_parm")]
    public List<long>? GoUpToParm { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("task_goal")]
    public List<long>? TaskGoal { get; set; }
    [JsonPropertyName("test_name")]
    public string? TestName { get; set; }
    [JsonPropertyName("test_point")]
    public long TestPoint { get; set; }
    [JsonPropertyName("test_type")]
    public long TestType { get; set; }
    [JsonPropertyName("test_type_name")]
    public string? TestTypeName { get; set; }
}
