// <auto-generated />
// Table: config_assist_fleet (rows: 26)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAssistFleet
{
    [JsonPropertyName("assist_ship_info_id")]
    public List<long>? AssistShipInfoId { get; set; }
    [JsonPropertyName("default_threat")]
    public long DefaultThreat { get; set; }
    [JsonPropertyName("formation")]
    public long Formation { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("strategy")]
    public long Strategy { get; set; }
    [JsonPropertyName("threat_id")]
    public List<long>? ThreatId { get; set; }
    [JsonPropertyName("view_mode")]
    public long ViewMode { get; set; }
}
