// <auto-generated />
// Table: config_chapter_tower (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChapterTower
{
    [JsonPropertyName("area_pass_reward")]
    public List<long>? AreaPassReward { get; set; }
    [JsonPropertyName("basic_reward")]
    public long BasicReward { get; set; }
    [JsonPropertyName("battle_point_cost")]
    public long BattlePointCost { get; set; }
    [JsonPropertyName("battle_point_default")]
    public long BattlePointDefault { get; set; }
    [JsonPropertyName("battle_point_min")]
    public long BattlePointMin { get; set; }
    [JsonPropertyName("daily_battle_time")]
    public long DailyBattleTime { get; set; }
    [JsonPropertyName("desc_simplify")]
    public long DescSimplify { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("reset_chapter")]
    public long ResetChapter { get; set; }
    [JsonPropertyName("reset_period")]
    public long ResetPeriod { get; set; }
    [JsonPropertyName("ship_battle_time")]
    public long ShipBattleTime { get; set; }
    [JsonPropertyName("topic_visible")]
    public long TopicVisible { get; set; }
    [JsonPropertyName("tower_topic")]
    public List<long>? TowerTopic { get; set; }
}
