// <auto-generated />
// Table: config_askill_dict_prj_ctrl_move (rows: 2310)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAskillDictPrjCtrlMove
{
    [JsonPropertyName("face_dir_rotate_speed")]
    public string? FaceDirRotateSpeed { get; set; }
    [JsonPropertyName("face_dir_rotate_type")]
    public long FaceDirRotateType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("move_dir_rotate_speed")]
    public long MoveDirRotateSpeed { get; set; }
    [JsonPropertyName("move_params")]
    public string? MoveParams { get; set; }
    [JsonPropertyName("move_type")]
    public long MoveType { get; set; }
    [JsonPropertyName("speed")]
    public string? Speed { get; set; }
    [JsonPropertyName("speed_type")]
    public long SpeedType { get; set; }
}
