// <auto-generated />
// Table: config_extra_skill (rows: 16)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExtraSkill
{
    [JsonPropertyName("cd")]
    public long Cd { get; set; }
    [JsonPropertyName("delete_time")]
    public long DeleteTime { get; set; }
    [JsonPropertyName("icon_disable")]
    public string? IconDisable { get; set; }
    [JsonPropertyName("icon_normal")]
    public string? IconNormal { get; set; }
    [JsonPropertyName("icon_select")]
    public string? IconSelect { get; set; }
    [JsonPropertyName("limit_count")]
    public long LimitCount { get; set; }
    [JsonPropertyName("name")]
    public long Name { get; set; }
    [JsonPropertyName("pskil_group_array")]
    public List<long>? PskilGroupArray { get; set; }
    [JsonPropertyName("ship_copy")]
    public long ShipCopy { get; set; }
    [JsonPropertyName("skill_id")]
    public long SkillId { get; set; }
}
