// <auto-generated />
// Table: config_eca_condition (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEcaCondition
{
    [JsonPropertyName("condition")]
    public string? Condition { get; set; }
    [JsonPropertyName("condition_type")]
    public long ConditionType { get; set; }
    [JsonPropertyName("eca_condition_body_type")]
    public long EcaConditionBodyType { get; set; }
    [JsonPropertyName("eca_condition_display_type")]
    public long EcaConditionDisplayType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
