// <auto-generated />
// Table: config_ryza_alchemy_type (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRyzaAlchemyType
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("eff_normal")]
    public string? EffNormal { get; set; }
    [JsonPropertyName("eff_normal_back")]
    public string? EffNormalBack { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image_background")]
    public string? ImageBackground { get; set; }
    [JsonPropertyName("image_off")]
    public string? ImageOff { get; set; }
    [JsonPropertyName("image_on")]
    public string? ImageOn { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public string? Quality { get; set; }
}
