// <auto-generated />
// Table: config_cutin_blacklist (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCutinBlacklist
{
    [JsonPropertyName("ID")]
    public long ID { get; set; }
    [JsonPropertyName("ship_info_ID")]
    public long ShipInfoID { get; set; }
}
