// <auto-generated />
// Table: config_boss_copy_life (rows: 50)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBossCopyLife
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("life_reduce")]
    public long LifeReduce { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
}
