// <auto-generated />
// Table: config_scene_position (rows: 18685)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigScenePosition
{
    [JsonPropertyName("eluer_y")]
    public long EluerY { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("position_id")]
    public long PositionId { get; set; }
    [JsonPropertyName("position_x")]
    public long PositionX { get; set; }
    [JsonPropertyName("position_y")]
    public long PositionY { get; set; }
    [JsonPropertyName("position_z")]
    public long PositionZ { get; set; }
    [JsonPropertyName("sp_id")]
    public string? SpId { get; set; }
}
