// <auto-generated />
// Table: config_chat_send_interval (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChatSendInterval
{
    [JsonPropertyName("channel_id")]
    public long ChannelId { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
}
