// <auto-generated />
// Table: config_tower_prop (rows: 13)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTowerProp
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("language_id")]
    public long LanguageId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
}
