// <auto-generated />
// Table: config_ship_advance (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipAdvance
{
    [JsonPropertyName("initial_level")]
    public long InitialLevel { get; set; }
    [JsonPropertyName("max_level")]
    public long MaxLevel { get; set; }
    [JsonPropertyName("unlock_num")]
    public long UnlockNum { get; set; }
}
