// <auto-generated />
// Table: config_skill_release_project (rows: 93)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillReleaseProject
{
    [JsonPropertyName("acc_gravity")]
    public double AccGravity { get; set; }
    [JsonPropertyName("acc_speed")]
    public double AccSpeed { get; set; }
    [JsonPropertyName("collide_bind_paths")]
    public List<string>? CollideBindPaths { get; set; }
    [JsonPropertyName("collide_type")]
    public string? CollideType { get; set; }
    [JsonPropertyName("curve_type")]
    public string? CurveType { get; set; }
    [JsonPropertyName("curve_w2h")]
    public double CurveW2h { get; set; }
    [JsonPropertyName("effect_id")]
    public List<string>? EffectId { get; set; }
    [JsonPropertyName("hit_effect_id")]
    public List<string>? HitEffectId { get; set; }
    [JsonPropertyName("init_bind_path")]
    public string? InitBindPath { get; set; }
    [JsonPropertyName("init_center")]
    public long InitCenter { get; set; }
    [JsonPropertyName("init_offset_x")]
    public double InitOffsetX { get; set; }
    [JsonPropertyName("init_offset_y")]
    public double InitOffsetY { get; set; }
    [JsonPropertyName("init_offset_z")]
    public double InitOffsetZ { get; set; }
    [JsonPropertyName("run_type")]
    public long RunType { get; set; }
    [JsonPropertyName("speed")]
    public double Speed { get; set; }
    [JsonPropertyName("srp_id")]
    public string? SrpId { get; set; }
    [JsonPropertyName("target_center")]
    public long TargetCenter { get; set; }
    [JsonPropertyName("target_offset_x")]
    public double TargetOffsetX { get; set; }
    [JsonPropertyName("target_offset_y")]
    public double TargetOffsetY { get; set; }
    [JsonPropertyName("target_offset_z")]
    public double TargetOffsetZ { get; set; }
    [JsonPropertyName("target_random_offset_x")]
    public double TargetRandomOffsetX { get; set; }
    [JsonPropertyName("target_random_offset_y")]
    public double TargetRandomOffsetY { get; set; }
    [JsonPropertyName("target_random_offset_z")]
    public double TargetRandomOffsetZ { get; set; }
    [JsonPropertyName("time")]
    public double Time { get; set; }
}
