// <auto-generated />
// Table: config_skill (rows: 7888)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkill
{
    [JsonPropertyName("anim_project_group")]
    public string? AnimProjectGroup { get; set; }
    [JsonPropertyName("anim_project_group_start_time")]
    public double AnimProjectGroupStartTime { get; set; }
    [JsonPropertyName("before_bac_use_state")]
    public string? BeforeBacUseState { get; set; }
    [JsonPropertyName("behit_effect_bind_id")]
    public List<string>? BehitEffectBindId { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("hit_skill_anim_detail_id")]
    public string? HitSkillAnimDetailId { get; set; }
    [JsonPropertyName("normal_bac_use_state")]
    public string? NormalBacUseState { get; set; }
    [JsonPropertyName("qishe_camera_group")]
    public string? QisheCameraGroup { get; set; }
    [JsonPropertyName("release_group_id")]
    public string? ReleaseGroupId { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("search_plane_delay")]
    public double SearchPlaneDelay { get; set; }
    [JsonPropertyName("ship_id")]
    public string? ShipId { get; set; }
    [JsonPropertyName("simple_behit_effect_bind_id")]
    public List<string>? SimpleBehitEffectBindId { get; set; }
    [JsonPropertyName("skill_anim_type")]
    public long SkillAnimType { get; set; }
    [JsonPropertyName("skill_camera_group")]
    public string? SkillCameraGroup { get; set; }
    [JsonPropertyName("skill_effect_bind_id")]
    public List<object>? SkillEffectBindId { get; set; }
    [JsonPropertyName("skill_effect_start_time")]
    public double SkillEffectStartTime { get; set; }
    [JsonPropertyName("start_skill_anim_detail_id")]
    public string? StartSkillAnimDetailId { get; set; }
}
