// <auto-generated />
// Table: config_item_recycling (rows: 302)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigItemRecycling
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_need_recycle")]
    public List<long>? ItemNeedRecycle { get; set; }
    [JsonPropertyName("item_return")]
    public List<long>? ItemReturn { get; set; }
    [JsonPropertyName("recycle_type")]
    public long RecycleType { get; set; }
}
