// <auto-generated />
// Table: config_teaching_assess (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTeachingAssess
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("range")]
    public List<long>? Range { get; set; }
    [JsonPropertyName("student_reward")]
    public long StudentReward { get; set; }
    [JsonPropertyName("teacher_reward")]
    public long TeacherReward { get; set; }
    [JsonPropertyName("tips")]
    public string? Tips { get; set; }
    [JsonPropertyName("tips_icon")]
    public string? TipsIcon { get; set; }
}
