// <auto-generated />
// Table: config_barrage_library (rows: 27999)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBarrageLibrary
{
    [JsonPropertyName("barrage_library_id")]
    public long BarrageLibraryId { get; set; }
    [JsonPropertyName("is_orbital_colse")]
    public List<object>? IsOrbitalColse { get; set; }
    [JsonPropertyName("scene_id")]
    public long SceneId { get; set; }
    [JsonPropertyName("scene_id_type")]
    public long SceneIdType { get; set; }
}
