// <auto-generated />
// Table: config_starbox (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigStarbox
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("open_effect")]
    public string? OpenEffect { get; set; }
    [JsonPropertyName("open_icon")]
    public string? OpenIcon { get; set; }
    [JsonPropertyName("positionx")]
    public long Positionx { get; set; }
    [JsonPropertyName("positiony")]
    public long Positiony { get; set; }
    [JsonPropertyName("recieved_icon")]
    public string? RecievedIcon { get; set; }
    [JsonPropertyName("unopen_icon")]
    public string? UnopenIcon { get; set; }
}
