// <auto-generated />
// Table: config_evaluate (rows: 234)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEvaluate
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("require_condition")]
    public long RequireCondition { get; set; }
    [JsonPropertyName("require_condition_argument1")]
    public long RequireConditionArgument1 { get; set; }
    [JsonPropertyName("require_condition_argument2")]
    public long RequireConditionArgument2 { get; set; }
}
