// <auto-generated />
// Table: config_fashion (rows: 1376)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFashion
{
    [JsonPropertyName("belong_to_ship")]
    public long BelongToShip { get; set; }
    [JsonPropertyName("belong_to_ship_group")]
    public List<long>? BelongToShipGroup { get; set; }
    [JsonPropertyName("cv_show")]
    public string? CvShow { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("fashion_showicon")]
    public string? FashionShowicon { get; set; }
    [JsonPropertyName("get_id")]
    public long GetId { get; set; }
    [JsonPropertyName("get_language_id")]
    public long GetLanguageId { get; set; }
    [JsonPropertyName("get_p1")]
    public List<object>? GetP1 { get; set; }
    [JsonPropertyName("get_type")]
    public long GetTypeValue { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_ka")]
    public string? IconKa { get; set; }
    [JsonPropertyName("icon_small")]
    public string? IconSmall { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_appear")]
    public long IsAppear { get; set; }
    [JsonPropertyName("is_default")]
    public long IsDefault { get; set; }
    [JsonPropertyName("limit_p1")]
    public List<object>? LimitP1 { get; set; }
    [JsonPropertyName("limit_tip")]
    public string? LimitTip { get; set; }
    [JsonPropertyName("limit_type")]
    public long LimitType { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("quality_show")]
    public long QualityShow { get; set; }
    [JsonPropertyName("repeat_rewards")]
    public long RepeatRewards { get; set; }
    [JsonPropertyName("ship_show_id")]
    public long ShipShowId { get; set; }
    [JsonPropertyName("shop_id")]
    public long ShopId { get; set; }
    [JsonPropertyName("skill_fashion_id")]
    public List<long>? SkillFashionId { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("unlock_action")]
    public List<string>? UnlockAction { get; set; }
}
