// <auto-generated />
// Table: config_guildboxparam (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildboxparam
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("num")]
    public long Num { get; set; }
}
