// <auto-generated />
// Table: config_ship_talent_desc (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipTalentDesc
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
