// <auto-generated />
// Table: config_plot_episode_ship (rows: 449)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeShip
{
    [JsonPropertyName("euler")]
    public long Euler { get; set; }
    [JsonPropertyName("expression_point")]
    public List<long>? ExpressionPoint { get; set; }
    [JsonPropertyName("left_ship_center")]
    public List<double>? LeftShipCenter { get; set; }
    [JsonPropertyName("middle_ship_center")]
    public List<double>? MiddleShipCenter { get; set; }
    [JsonPropertyName("mirror_left_ship_center")]
    public List<double>? MirrorLeftShipCenter { get; set; }
    [JsonPropertyName("mirror_middle_ship_center")]
    public List<double>? MirrorMiddleShipCenter { get; set; }
    [JsonPropertyName("mirror_right_ship_center")]
    public List<double>? MirrorRightShipCenter { get; set; }
    [JsonPropertyName("right_ship_center")]
    public List<double>? RightShipCenter { get; set; }
    [JsonPropertyName("ship_id")]
    public long ShipId { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_res_path")]
    public string? ShipResPath { get; set; }
}
