// <auto-generated />
// Table: config_ship_transform_effect (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipTransformEffect
{
    [JsonPropertyName("cost")]
    public List<List<long>>? Cost { get; set; }
    [JsonPropertyName("cost_ship")]
    public List<object>? CostShip { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("effect")]
    public List<List<long>>? Effect { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("last_id")]
    public List<long>? LastId { get; set; }
    [JsonPropertyName("limit")]
    public List<long>? Limit { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
