// <auto-generated />
// Table: config_pskill_dict_buff_cb_con (rows: 47)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictBuffCbCon
{
    [JsonPropertyName("condition_type")]
    public long ConditionType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("target")]
    public long Target { get; set; }
    [JsonPropertyName("value")]
    public List<long>? Value { get; set; }
}
