// <auto-generated />
// Table: config_fleet_speed (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFleetSpeed
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("fatigue_a_speed")]
    public double FatigueASpeed { get; set; }
    [JsonPropertyName("fatigue_b_speed")]
    public double FatigueBSpeed { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rotate_speed_fac")]
    public double RotateSpeedFac { get; set; }
    [JsonPropertyName("speed_fac_pve")]
    public double SpeedFacPve { get; set; }
    [JsonPropertyName("speed_fac_pvp_battle")]
    public double SpeedFacPvpBattle { get; set; }
    [JsonPropertyName("speed_fac_pvp_search")]
    public double SpeedFacPvpSearch { get; set; }
}
