// <auto-generated />
// Table: config_scene (rows: 252)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigScene
{
    [JsonPropertyName("guide_mesh")]
    public string? GuideMesh { get; set; }
    [JsonPropertyName("island_ids")]
    public List<object>? IslandIds { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("scene_res_name")]
    public string? SceneResName { get; set; }
}
