// <auto-generated />
// Table: config_ship_info (rows: 1478)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipInfo
{
    [JsonPropertyName("attr_dock_show")]
    public List<long>? AttrDockShow { get; set; }
    [JsonPropertyName("attr_type_show")]
    public List<long>? AttrTypeShow { get; set; }
    [JsonPropertyName("build_time")]
    public long BuildTime { get; set; }
    [JsonPropertyName("constellation")]
    public long Constellation { get; set; }
    [JsonPropertyName("equip1")]
    public long Equip1 { get; set; }
    [JsonPropertyName("equip2")]
    public long Equip2 { get; set; }
    [JsonPropertyName("equip3")]
    public long Equip3 { get; set; }
    [JsonPropertyName("equip4")]
    public long Equip4 { get; set; }
    [JsonPropertyName("equip5")]
    public long Equip5 { get; set; }
    [JsonPropertyName("equip6")]
    public long Equip6 { get; set; }
    [JsonPropertyName("initial_ship_main_id")]
    public long InitialShipMainId { get; set; }
    [JsonPropertyName("max_ammunition")]
    public long MaxAmmunition { get; set; }
    [JsonPropertyName("max_gasoline")]
    public long MaxGasoline { get; set; }
    [JsonPropertyName("min_level")]
    public long MinLevel { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("remould_item")]
    public long RemouldItem { get; set; }
    [JsonPropertyName("remould_level")]
    public long RemouldLevel { get; set; }
    [JsonPropertyName("remould_skill")]
    public List<object>? RemouldSkill { get; set; }
    [JsonPropertyName("remould_template")]
    public List<long>? RemouldTemplate { get; set; }
    [JsonPropertyName("sf_id")]
    public long SfId { get; set; }
    [JsonPropertyName("ship_country")]
    public long ShipCountry { get; set; }
    [JsonPropertyName("ship_handbook_id")]
    public long ShipHandbookId { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("si_id")]
    public long SiId { get; set; }
    [JsonPropertyName("vow_item_mub")]
    public long VowItemMub { get; set; }
    [JsonPropertyName("vow_item_num_mub")]
    public long VowItemNumMub { get; set; }
}
