// <auto-generated />
// Table: config_plot_episode_branch (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeBranch
{
    [JsonPropertyName("branch_content")]
    public string? BranchContent { get; set; }
    [JsonPropertyName("branch_id")]
    public long BranchId { get; set; }
    [JsonPropertyName("branch_parameter")]
    public List<long>? BranchParameter { get; set; }
    [JsonPropertyName("branch_type")]
    public long BranchType { get; set; }
}
