// <auto-generated />
// Table: config_copytypemap (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopytypemap
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
