// <auto-generated />
// Table: config_search3d_item (rows: 29)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSearch3dItem
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("display_distence")]
    public long DisplayDistence { get; set; }
    [JsonPropertyName("display_mode")]
    public long DisplayMode { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_defult_icon")]
    public string? ItemDefultIcon { get; set; }
    [JsonPropertyName("item_defult_model_eb_id")]
    public List<string>? ItemDefultModelEbId { get; set; }
    [JsonPropertyName("item_effui_eb_id")]
    public List<object>? ItemEffuiEbId { get; set; }
    [JsonPropertyName("item_mini_icon")]
    public string? ItemMiniIcon { get; set; }
    [JsonPropertyName("item_range_eb_id")]
    public List<string>? ItemRangeEbId { get; set; }
    [JsonPropertyName("item_trigger_eb_id")]
    public List<string>? ItemTriggerEbId { get; set; }
    [JsonPropertyName("item_ui_root")]
    public string? ItemUiRoot { get; set; }
    [JsonPropertyName("playerfleet_trigger_eb_id")]
    public List<string>? PlayerfleetTriggerEbId { get; set; }
    [JsonPropertyName("warn_mode")]
    public long WarnMode { get; set; }
}
