// <auto-generated />
// Table: config_level_reward (rows: 19)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigLevelReward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("reward")]
    public List<List<long>>? Reward { get; set; }
}
