// <auto-generated />
// Table: config_building_character_story (rows: 216)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildingCharacterStory
{
    [JsonPropertyName("affection_value")]
    public long AffectionValue { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("open_time")]
    public long OpenTime { get; set; }
    [JsonPropertyName("plot_cover")]
    public string? PlotCover { get; set; }
    [JsonPropertyName("plot_title")]
    public string? PlotTitle { get; set; }
    [JsonPropertyName("plot_trigger_building")]
    public List<object>? PlotTriggerBuilding { get; set; }
    [JsonPropertyName("plot_trigger_id")]
    public long PlotTriggerId { get; set; }
    [JsonPropertyName("plot_trigger_type")]
    public long PlotTriggerType { get; set; }
    [JsonPropertyName("ship_fleet_id")]
    public long ShipFleetId { get; set; }
}
