// <auto-generated />
// Table: config_rewards (rows: 7193)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRewards
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rewards")]
    public List<List<long>>? Rewards { get; set; }
}
