// <auto-generated />
// Table: config_guildactivityrankreward (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildactivityrankreward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("ranklist")]
    public List<long>? Ranklist { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
}
