// <auto-generated />
// Table: config_voice_chat_err (rows: 100)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigVoiceChatErr
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("notice")]
    public string? Notice { get; set; }
}
