// <auto-generated />
// Table: config_plot_episode_expression (rows: 1903)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeExpression
{
    [JsonPropertyName("expression_des")]
    public string? ExpressionDes { get; set; }
    [JsonPropertyName("expression_id")]
    public long ExpressionId { get; set; }
    [JsonPropertyName("expression_res")]
    public string? ExpressionRes { get; set; }
    [JsonPropertyName("talker_id")]
    public long TalkerId { get; set; }
}
