// <auto-generated />
// Table: config_parameter_mail (rows: 86)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigParameterMail
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("mail_content")]
    public string? MailContent { get; set; }
    [JsonPropertyName("mail_title")]
    public string? MailTitle { get; set; }
    [JsonPropertyName("mail_title_eng")]
    public string? MailTitleEng { get; set; }
    [JsonPropertyName("related_system")]
    public string? RelatedSystem { get; set; }
}
