// <auto-generated />
// Table: config_daily_chapter (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDailyChapter
{
    [JsonPropertyName("advice")]
    public string? Advice { get; set; }
    [JsonPropertyName("challenge_time")]
    public long ChallengeTime { get; set; }
    [JsonPropertyName("copy_background")]
    public string? CopyBackground { get; set; }
    [JsonPropertyName("copy_button_deviation")]
    public long CopyButtonDeviation { get; set; }
    [JsonPropertyName("copy_dropinfo")]
    public string? CopyDropinfo { get; set; }
    [JsonPropertyName("copy_image")]
    public string? CopyImage { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_available")]
    public List<long>? IsAvailable { get; set; }
    [JsonPropertyName("month_extra_time")]
    public long MonthExtraTime { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("ship_level")]
    public long ShipLevel { get; set; }
    [JsonPropertyName("ship_level_type")]
    public long ShipLevelType { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("train_array_indexid")]
    public long TrainArrayIndexid { get; set; }
    [JsonPropertyName("train_chapter")]
    public long TrainChapter { get; set; }
}
