// <auto-generated />
// Table: config_plot_episode_effect (rows: 42)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeEffect
{
    [JsonPropertyName("effect_id")]
    public long EffectId { get; set; }
    [JsonPropertyName("effect_res")]
    public string? EffectRes { get; set; }
}
