// <auto-generated />
// Table: config_copy_grade_type (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopyGradeType
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
