// <auto-generated />
// Table: config_guildoffer_guildrankreward (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildofferGuildrankreward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("limitscore")]
    public long Limitscore { get; set; }
    [JsonPropertyName("rankid")]
    public List<long>? Rankid { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
}
