// <auto-generated />
// Table: config_skill_anim_detail_camera_target (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimDetailCameraTarget
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
