// <auto-generated />
// Table: config_ship_type (rows: 23)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipType
{
    [JsonPropertyName("defult_range")]
    public long DefultRange { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("father_type")]
    public long FatherType { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("safearea_quickbattle_languageId")]
    public long SafeareaQuickbattleLanguageId { get; set; }
    [JsonPropertyName("wordsimage")]
    public string? Wordsimage { get; set; }
}
