// <auto-generated />
// Table: config_achievement (rows: 745)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAchievement
{
    [JsonPropertyName("abandoned")]
    public long Abandoned { get; set; }
    [JsonPropertyName("count_type")]
    public long CountType { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("if_invisible")]
    public long IfInvisible { get; set; }
    [JsonPropertyName("last_achievement")]
    public long LastAchievement { get; set; }
    [JsonPropertyName("medal_id")]
    public long MedalId { get; set; }
    [JsonPropertyName("open_day")]
    public long OpenDay { get; set; }
    [JsonPropertyName("point")]
    public long Point { get; set; }
    [JsonPropertyName("progress")]
    public long Progress { get; set; }
    [JsonPropertyName("refresh_id")]
    public long RefreshId { get; set; }
    [JsonPropertyName("reward")]
    public List<List<long>>? Reward { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("show_reward_num")]
    public long ShowRewardNum { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("type_id")]
    public long TypeId { get; set; }
    [JsonPropertyName("visible_parm")]
    public long VisibleParm { get; set; }
}
