// <auto-generated />
// Table: config_skill_anim_detail_action_type (rows: 25)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimDetailActionType
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("params1")]
    public string? Params1 { get; set; }
    [JsonPropertyName("params1_content1")]
    public string? Params1Content1 { get; set; }
    [JsonPropertyName("params1_content2")]
    public string? Params1Content2 { get; set; }
    [JsonPropertyName("params1_content3")]
    public string? Params1Content3 { get; set; }
    [JsonPropertyName("params2")]
    public string? Params2 { get; set; }
    [JsonPropertyName("params3")]
    public string? Params3 { get; set; }
    [JsonPropertyName("params4")]
    public string? Params4 { get; set; }
    [JsonPropertyName("params5")]
    public string? Params5 { get; set; }
    [JsonPropertyName("params6")]
    public string? Params6 { get; set; }
}
