// <auto-generated />
// Table: config_character (rows: 128)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCharacter
{
    [JsonPropertyName("characteraddition")]
    public List<long>? Characteraddition { get; set; }
    [JsonPropertyName("charactersicon")]
    public string? Charactersicon { get; set; }
    [JsonPropertyName("desc")]
    public long Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("levelupaddition")]
    public List<long>? Levelupaddition { get; set; }
    [JsonPropertyName("leveluprecipeaddition")]
    public List<long>? Leveluprecipeaddition { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("recipeadd")]
    public List<long>? Recipeadd { get; set; }
    [JsonPropertyName("recipeaddition")]
    public List<long>? Recipeaddition { get; set; }
}
