// <auto-generated />
// Table: config_ship_equip (rows: 4803)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipEquip
{
    [JsonPropertyName("equip_attr_condition")]
    public List<List<long>>? EquipAttrCondition { get; set; }
    [JsonPropertyName("equip_attr_num_1")]
    public List<long>? EquipAttrNum1 { get; set; }
    [JsonPropertyName("equip_attr_num_2")]
    public List<long>? EquipAttrNum2 { get; set; }
    [JsonPropertyName("equip_attr_num_3")]
    public List<long>? EquipAttrNum3 { get; set; }
    [JsonPropertyName("equip_attr_num_4")]
    public List<long>? EquipAttrNum4 { get; set; }
    [JsonPropertyName("equip_attr_num_5")]
    public List<long>? EquipAttrNum5 { get; set; }
    [JsonPropertyName("equip_attr_num_6")]
    public List<long>? EquipAttrNum6 { get; set; }
    [JsonPropertyName("ewt_ids")]
    public List<string>? EwtIds { get; set; }
    [JsonPropertyName("plane_number")]
    public List<long>? PlaneNumber { get; set; }
    [JsonPropertyName("recommend_equip")]
    public List<long>? RecommendEquip { get; set; }
    [JsonPropertyName("se_id")]
    public long SeId { get; set; }
}
