// <auto-generated />
// Table: config_bd_prop1 (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBdProp1
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
