// <auto-generated />
// Table: config_task_main (rows: 174)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskMain
{
    [JsonPropertyName("copy_display_id")]
    public long CopyDisplayId { get; set; }
    [JsonPropertyName("count_type")]
    public long CountType { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("function_id")]
    public long FunctionId { get; set; }
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("next_task_id")]
    public long NextTaskId { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("player_level_max")]
    public long PlayerLevelMax { get; set; }
    [JsonPropertyName("player_level_min")]
    public long PlayerLevelMin { get; set; }
    [JsonPropertyName("reward")]
    public List<List<long>>? Reward { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
}
