// <auto-generated />
// Table: config_export_func (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExportFunc
{
    [JsonPropertyName("damage_formula")]
    public string? DamageFormula { get; set; }
    [JsonPropertyName("damage_type")]
    public long DamageType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
