// <auto-generated />
// Table: config_caption_access_list (rows: 7993)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCaptionAccessList
{
    [JsonPropertyName("behavior_type")]
    public string? BehaviorType { get; set; }
    [JsonPropertyName("caption_access")]
    public string? CaptionAccess { get; set; }
    [JsonPropertyName("caption_end")]
    public long CaptionEnd { get; set; }
    [JsonPropertyName("caption_open")]
    public double CaptionOpen { get; set; }
    [JsonPropertyName("cn_text")]
    public string? CnText { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("jp_text")]
    public string? JpText { get; set; }
    [JsonPropertyName("modle_name")]
    public string? ModleName { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
}
