// <auto-generated />
// Table: config_safearea (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSafearea
{
    [JsonPropertyName("change_time")]
    public long ChangeTime { get; set; }
    [JsonPropertyName("copy_text_color")]
    public string? CopyTextColor { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("effect_outline_color")]
    public List<long>? EffectOutlineColor { get; set; }
    [JsonPropertyName("effect_text_color")]
    public string? EffectTextColor { get; set; }
    [JsonPropertyName("explore_image")]
    public string? ExploreImage { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("imgbackground")]
    public string? Imgbackground { get; set; }
    [JsonPropertyName("imglock")]
    public string? Imglock { get; set; }
    [JsonPropertyName("levelup_effect")]
    public string? LevelupEffect { get; set; }
    [JsonPropertyName("slider_image")]
    public string? SliderImage { get; set; }
    [JsonPropertyName("small_slider_image")]
    public string? SmallSliderImage { get; set; }
    [JsonPropertyName("text_color")]
    public string? TextColor { get; set; }
}
