// <auto-generated />
// Table: config_skill_anim_detail_ios (rows: 1820)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimDetailIos
{
    [JsonPropertyName("action")]
    public long Action { get; set; }
    [JsonPropertyName("action_queue")]
    public long ActionQueue { get; set; }
    [JsonPropertyName("action_type")]
    public string? ActionType { get; set; }
    [JsonPropertyName("args1")]
    public string? Args1 { get; set; }
    [JsonPropertyName("camera_target")]
    public string? CameraTarget { get; set; }
    [JsonPropertyName("camera_type")]
    public string? CameraType { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("group")]
    public long Group { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("target_offset")]
    public string? TargetOffset { get; set; }
}
