// <auto-generated />
// Table: config_chat_set (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChatSet
{
    [JsonPropertyName("belong")]
    public long Belong { get; set; }
    [JsonPropertyName("channel")]
    public long Channel { get; set; }
    [JsonPropertyName("count")]
    public long Count { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("key")]
    public string? Key { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("value")]
    public long Value { get; set; }
}
