// <auto-generated />
// Table: config_access (rows: 200)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAccess
{
    [JsonPropertyName("activatetime")]
    public long Activatetime { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("period_id")]
    public List<long>? PeriodId { get; set; }
}
