// <auto-generated />
// Table: config_attribute (rows: 107)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAttribute
{
    [JsonPropertyName("attr_direction")]
    public string? AttrDirection { get; set; }
    [JsonPropertyName("attr_display")]
    public string? AttrDisplay { get; set; }
    [JsonPropertyName("attr_icon")]
    public string? AttrIcon { get; set; }
    [JsonPropertyName("attr_name")]
    public string? AttrName { get; set; }
    [JsonPropertyName("attr_type")]
    public long AttrType { get; set; }
    [JsonPropertyName("attr_unit")]
    public string? AttrUnit { get; set; }
    [JsonPropertyName("beizhu")]
    public string? Beizhu { get; set; }
    [JsonPropertyName("direction_if_show")]
    public long DirectionIfShow { get; set; }
    [JsonPropertyName("direction_show_sort")]
    public long DirectionShowSort { get; set; }
    [JsonPropertyName("equip_if_show")]
    public long EquipIfShow { get; set; }
    [JsonPropertyName("equip_show_sort")]
    public long EquipShowSort { get; set; }
    [JsonPropertyName("girl_if_show")]
    public long GirlIfShow { get; set; }
    [JsonPropertyName("girl_show_sort")]
    public long GirlShowSort { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("params")]
    public List<long>? Params { get; set; }
    [JsonPropertyName("remould_if_show")]
    public long RemouldIfShow { get; set; }
    [JsonPropertyName("remould_prop_formula")]
    public string? RemouldPropFormula { get; set; }
}
