// <auto-generated />
// Table: config_ship_hp_state (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipHpState
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("hp_min_percent")]
    public double HpMinPercent { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
