// <auto-generated />
// Table: config_battle_qte_pro (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleQtePro
{
    [JsonPropertyName("bqp_id")]
    public long BqpId { get; set; }
    [JsonPropertyName("duration_12")]
    public double Duration12 { get; set; }
    [JsonPropertyName("duration_23")]
    public double Duration23 { get; set; }
    [JsonPropertyName("duration_34")]
    public double Duration34 { get; set; }
    [JsonPropertyName("last_suration")]
    public double LastSuration { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("size_percent_1")]
    public double SizePercent1 { get; set; }
    [JsonPropertyName("size_percent_2")]
    public double SizePercent2 { get; set; }
    [JsonPropertyName("size_percent_3")]
    public double SizePercent3 { get; set; }
    [JsonPropertyName("size_percent_4")]
    public double SizePercent4 { get; set; }
}
