// <auto-generated />
// Table: config_shiplist_sequence (rows: 98)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShiplistSequence
{
    [JsonPropertyName("belong")]
    public long Belong { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("value")]
    public long Value { get; set; }
}
