// <auto-generated />
// Table: config_task_reward_modify (rows: 40)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskRewardModify
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rewards_modify")]
    public List<List<long>>? RewardsModify { get; set; }
}
