// <auto-generated />
// Table: config_prohibit_speed (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigProhibitSpeed
{
    [JsonPropertyName("prohibit_lv")]
    public long ProhibitLv { get; set; }
    [JsonPropertyName("prohibit_num")]
    public long ProhibitNum { get; set; }
    [JsonPropertyName("prohibit_switch")]
    public long ProhibitSwitch { get; set; }
    [JsonPropertyName("prohibit_time")]
    public long ProhibitTime { get; set; }
}
