// <auto-generated />
// Table: config_interaction_figurte (rows: 185)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigInteractionFigurte
{
    [JsonPropertyName("figure_icon")]
    public string? FigureIcon { get; set; }
    [JsonPropertyName("figure_name")]
    public string? FigureName { get; set; }
    [JsonPropertyName("figure_order")]
    public long FigureOrder { get; set; }
    [JsonPropertyName("figure_quality")]
    public long FigureQuality { get; set; }
    [JsonPropertyName("figure_scale")]
    public List<double>? FigureScale { get; set; }
    [JsonPropertyName("figure_type")]
    public long FigureType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_drawable")]
    public long IsDrawable { get; set; }
    [JsonPropertyName("origional_ship_required")]
    public long OrigionalShipRequired { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
}
