// <auto-generated />
// Table: config_item_exchange (rows: 117)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigItemExchange
{
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("change_count")]
    public long ChangeCount { get; set; }
    [JsonPropertyName("condition_desc")]
    public string? ConditionDesc { get; set; }
    [JsonPropertyName("exchange_condition")]
    public List<object>? ExchangeCondition { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_consume")]
    public List<List<long>>? ItemConsume { get; set; }
    [JsonPropertyName("item_reward")]
    public List<List<long>>? ItemReward { get; set; }
    [JsonPropertyName("refresh_id")]
    public long RefreshId { get; set; }
}
