// <auto-generated />
// Table: config_skill_trap_group (rows: 386)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTrapGroup
{
    [JsonPropertyName("begin_scale_percent")]
    public double BeginScalePercent { get; set; }
    [JsonPropertyName("create_range_max")]
    public long CreateRangeMax { get; set; }
    [JsonPropertyName("create_range_min")]
    public long CreateRangeMin { get; set; }
    [JsonPropertyName("create_type")]
    public long CreateType { get; set; }
    [JsonPropertyName("fill_time")]
    public long FillTime { get; set; }
    [JsonPropertyName("move_type")]
    public long MoveType { get; set; }
    [JsonPropertyName("persuit_time")]
    public long PersuitTime { get; set; }
    [JsonPropertyName("scale_could_move")]
    public long ScaleCouldMove { get; set; }
    [JsonPropertyName("scale_time")]
    public long ScaleTime { get; set; }
    [JsonPropertyName("skill_type")]
    public long SkillType { get; set; }
    [JsonPropertyName("speed")]
    public double Speed { get; set; }
    [JsonPropertyName("stg_id")]
    public long StgId { get; set; }
    [JsonPropertyName("trap_group_type")]
    public long TrapGroupType { get; set; }
    [JsonPropertyName("trap_items")]
    public List<long>? TrapItems { get; set; }
}
