// <auto-generated />
// Table: config_testship_reward (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTestshipReward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("task_point")]
    public long TaskPoint { get; set; }
    [JsonPropertyName("task_point_total")]
    public long TaskPointTotal { get; set; }
}
