// <auto-generated />
// Table: config_counting (rows: 87)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCounting
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max")]
    public long Max { get; set; }
    [JsonPropertyName("refreshid")]
    public List<long>? Refreshid { get; set; }
}
