// <auto-generated />
// Table: config_support_fleet_item (rows: 29)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSupportFleetItem
{
    [JsonPropertyName("at_least_number")]
    public long AtLeastNumber { get; set; }
    [JsonPropertyName("base_award")]
    public List<List<long>>? BaseAward { get; set; }
    [JsonPropertyName("big_sucess_base_award")]
    public List<List<long>>? BigSucessBaseAward { get; set; }
    [JsonPropertyName("big_sucess_extra_drop_id")]
    public long BigSucessExtraDropId { get; set; }
    [JsonPropertyName("big_sucess_ratio")]
    public long BigSucessRatio { get; set; }
    [JsonPropertyName("complete_item")]
    public List<long>? CompleteItem { get; set; }
    [JsonPropertyName("condition_add")]
    public List<object>? ConditionAdd { get; set; }
    [JsonPropertyName("condition_add2")]
    public List<List<long>>? ConditionAdd2 { get; set; }
    [JsonPropertyName("consumption")]
    public List<object>? Consumption { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("extra_drop_id")]
    public long ExtraDropId { get; set; }
    [JsonPropertyName("get")]
    public string? Get { get; set; }
    [JsonPropertyName("group")]
    public long Group { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("ship_id_available")]
    public List<object>? ShipIdAvailable { get; set; }
    [JsonPropertyName("ship_num_limit")]
    public long ShipNumLimit { get; set; }
    [JsonPropertyName("ship_types_available")]
    public List<object>? ShipTypesAvailable { get; set; }
    [JsonPropertyName("ships_available")]
    public List<object>? ShipsAvailable { get; set; }
    [JsonPropertyName("ships_recommend_type")]
    public List<long>? ShipsRecommendType { get; set; }
    [JsonPropertyName("support_fleet_average_level_min")]
    public long SupportFleetAverageLevelMin { get; set; }
    [JsonPropertyName("support_fleet_few_level_min")]
    public List<object>? SupportFleetFewLevelMin { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
    [JsonPropertyName("use_count")]
    public long UseCount { get; set; }
}
