// <auto-generated />
// Table: config_guildlevel (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildlevel
{
    [JsonPropertyName("addition_reward_list")]
    public List<List<long>>? AdditionRewardList { get; set; }
    [JsonPropertyName("enter_num")]
    public List<long>? EnterNum { get; set; }
    [JsonPropertyName("guildlevelupexp")]
    public long Guildlevelupexp { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_exp")]
    public long MaxExp { get; set; }
    [JsonPropertyName("playernum")]
    public long Playernum { get; set; }
    [JsonPropertyName("reward_weight")]
    public List<List<long>>? RewardWeight { get; set; }
    [JsonPropertyName("tasknum")]
    public long Tasknum { get; set; }
}
