// <auto-generated />
// Table: config_chapter_training (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChapterTraining
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("open_level")]
    public long OpenLevel { get; set; }
    [JsonPropertyName("star_need")]
    public List<long>? StarNeed { get; set; }
    [JsonPropertyName("star_reward")]
    public List<long>? StarReward { get; set; }
    [JsonPropertyName("training_level_list")]
    public List<List<long>>? TrainingLevelList { get; set; }
    [JsonPropertyName("training_level_name_list")]
    public List<string>? TrainingLevelNameList { get; set; }
    [JsonPropertyName("training_reward_show")]
    public long TrainingRewardShow { get; set; }
}
