// <auto-generated />
// Table: config_mission (rows: 14)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMission
{
    [JsonPropertyName("acceptmission_action")]
    public List<long>? AcceptmissionAction { get; set; }
    [JsonPropertyName("finish_type")]
    public long FinishType { get; set; }
    [JsonPropertyName("finishmission_action")]
    public List<long>? FinishmissionAction { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("mission_display_id")]
    public long MissionDisplayId { get; set; }
    [JsonPropertyName("mission_eca_id")]
    public List<long>? MissionEcaId { get; set; }
    [JsonPropertyName("mission_eca_type")]
    public long MissionEcaType { get; set; }
    [JsonPropertyName("nextmission")]
    public List<long>? Nextmission { get; set; }
}
