// <auto-generated />
// Table: config_affection_change (rows: 14)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAffectionChange
{
    [JsonPropertyName("affection_add")]
    public long AffectionAdd { get; set; }
    [JsonPropertyName("affection_change_sort")]
    public long AffectionChangeSort { get; set; }
    [JsonPropertyName("affection_flagship_add")]
    public long AffectionFlagshipAdd { get; set; }
    [JsonPropertyName("affection_mvp_add")]
    public long AffectionMvpAdd { get; set; }
    [JsonPropertyName("affection_reduce")]
    public long AffectionReduce { get; set; }
    [JsonPropertyName("mood_reduce")]
    public long MoodReduce { get; set; }
    [JsonPropertyName("mood_shipwrecks_reduce")]
    public long MoodShipwrecksReduce { get; set; }
    [JsonPropertyName("not_effect_curriculum_vitae")]
    public long NotEffectCurriculumVitae { get; set; }
}
