// <auto-generated />
// Table: config_report (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigReport
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("min_last_time")]
    public long MinLastTime { get; set; }
    [JsonPropertyName("normal_last_time")]
    public long NormalLastTime { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
