// <auto-generated />
// Table: config_buff_show (rows: 669)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuffShow
{
    [JsonPropertyName("buff_display_ebs")]
    public List<string>? BuffDisplayEbs { get; set; }
    [JsonPropertyName("buff_display_ebs_belong")]
    public long BuffDisplayEbsBelong { get; set; }
    [JsonPropertyName("buff_display_show_state")]
    public long BuffDisplayShowState { get; set; }
    [JsonPropertyName("buff_display_ui_eb_id")]
    public List<string>? BuffDisplayUiEbId { get; set; }
    [JsonPropertyName("buff_display_ui_effect_root")]
    public string? BuffDisplayUiEffectRoot { get; set; }
    [JsonPropertyName("buff_display_ui_effect_roots")]
    public List<string>? BuffDisplayUiEffectRoots { get; set; }
    [JsonPropertyName("buff_display_ui_effect_uri")]
    public string? BuffDisplayUiEffectUri { get; set; }
    [JsonPropertyName("buff_display_ui_path")]
    public List<string>? BuffDisplayUiPath { get; set; }
    [JsonPropertyName("buff_display_work_effect_uri")]
    public string? BuffDisplayWorkEffectUri { get; set; }
    [JsonPropertyName("buff_resttime_text")]
    public string? BuffResttimeText { get; set; }
    [JsonPropertyName("buff_shield")]
    public long BuffShield { get; set; }
    [JsonPropertyName("buff_show_delay_type")]
    public long BuffShowDelayType { get; set; }
    [JsonPropertyName("buff_show_rule")]
    public long BuffShowRule { get; set; }
    [JsonPropertyName("buff_show_type_id")]
    public long BuffShowTypeId { get; set; }
    [JsonPropertyName("buff_stack")]
    public long BuffStack { get; set; }
    [JsonPropertyName("buff_statistics_text_page_path")]
    public string? BuffStatisticsTextPagePath { get; set; }
    [JsonPropertyName("buff_statistics_ui_effect_text")]
    public string? BuffStatisticsUiEffectText { get; set; }
    [JsonPropertyName("buff_statistics_ui_effect_uri")]
    public string? BuffStatisticsUiEffectUri { get; set; }
    [JsonPropertyName("buff_tips")]
    public long BuffTips { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("team_buff_desc")]
    public string? TeamBuffDesc { get; set; }
    [JsonPropertyName("team_buff_icon")]
    public string? TeamBuffIcon { get; set; }
    [JsonPropertyName("team_buff_name")]
    public string? TeamBuffName { get; set; }
}
