// <auto-generated />
// Table: config_expedition_task (rows: 411)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExpeditionTask
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("extra_require")]
    public List<object>? ExtraRequire { get; set; }
    [JsonPropertyName("extra_require_desc")]
    public List<string>? ExtraRequireDesc { get; set; }
    [JsonPropertyName("fast_finish_item")]
    public List<long>? FastFinishItem { get; set; }
    [JsonPropertyName("fixed_reward_number")]
    public long FixedRewardNumber { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level_max")]
    public long LevelMax { get; set; }
    [JsonPropertyName("level_min")]
    public long LevelMin { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("need_one_ship_level")]
    public long NeedOneShipLevel { get; set; }
    [JsonPropertyName("random_reward")]
    public List<long>? RandomReward { get; set; }
    [JsonPropertyName("random_reward_probability")]
    public long RandomRewardProbability { get; set; }
    [JsonPropertyName("random_reward_rewise")]
    public List<long>? RandomRewardRewise { get; set; }
    [JsonPropertyName("regular_reward1")]
    public List<long>? RegularReward1 { get; set; }
    [JsonPropertyName("regular_reward1_revise")]
    public List<object>? RegularReward1Revise { get; set; }
    [JsonPropertyName("regular_reward2")]
    public List<long>? RegularReward2 { get; set; }
    [JsonPropertyName("regular_reward2_revise")]
    public List<object>? RegularReward2Revise { get; set; }
    [JsonPropertyName("regular_reward3")]
    public List<long>? RegularReward3 { get; set; }
    [JsonPropertyName("regular_reward3_revise")]
    public List<object>? RegularReward3Revise { get; set; }
    [JsonPropertyName("regular_reward4")]
    public List<object>? RegularReward4 { get; set; }
    [JsonPropertyName("regular_reward4_revise")]
    public List<object>? RegularReward4Revise { get; set; }
    [JsonPropertyName("resources")]
    public List<long>? Resources { get; set; }
    [JsonPropertyName("show_level")]
    public long ShowLevel { get; set; }
    [JsonPropertyName("team_ship_count")]
    public long TeamShipCount { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
    [JsonPropertyName("time_limit")]
    public long TimeLimit { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
