// <auto-generated />
// Table: config_affection_mood (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAffectionMood
{
    [JsonPropertyName("mood_affection_add")]
    public long MoodAffectionAdd { get; set; }
    [JsonPropertyName("mood_describe")]
    public string? MoodDescribe { get; set; }
    [JsonPropertyName("mood_exp_up")]
    public long MoodExpUp { get; set; }
    [JsonPropertyName("mood_icon")]
    public string? MoodIcon { get; set; }
    [JsonPropertyName("mood_icon_xiao")]
    public string? MoodIconXiao { get; set; }
    [JsonPropertyName("mood_id")]
    public long MoodId { get; set; }
    [JsonPropertyName("mood_max")]
    public long MoodMax { get; set; }
    [JsonPropertyName("mood_min")]
    public long MoodMin { get; set; }
}
