// <auto-generated />
// Table: config_skill_trap_ratio (rows: 37)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTrapRatio
{
    [JsonPropertyName("left_euler")]
    public long LeftEuler { get; set; }
    [JsonPropertyName("right_euler")]
    public long RightEuler { get; set; }
    [JsonPropertyName("str_id")]
    public long StrId { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
