// <auto-generated />
// Table: config_pskill_dict_flag (rows: 111)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictFlag
{
    [JsonPropertyName("fid")]
    public long Fid { get; set; }
    [JsonPropertyName("force_clean_flag")]
    public long ForceCleanFlag { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("value_num")]
    public long ValueNum { get; set; }
}
