// <auto-generated />
// Table: config_ship_model (rows: 468)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipModel
{
    [JsonPropertyName("animoji_switch")]
    public long AnimojiSwitch { get; set; }
    [JsonPropertyName("ar_sec_clear")]
    public double ArSecClear { get; set; }
    [JsonPropertyName("build_shot")]
    public long BuildShot { get; set; }
    [JsonPropertyName("camera_target")]
    public long CameraTarget { get; set; }
    [JsonPropertyName("cv_resources")]
    public long CvResources { get; set; }
    [JsonPropertyName("head_type")]
    public long HeadType { get; set; }
    [JsonPropertyName("hide_incamera_radius")]
    public double HideIncameraRadius { get; set; }
    [JsonPropertyName("hit_miss_camera_path")]
    public string? HitMissCameraPath { get; set; }
    [JsonPropertyName("model")]
    public string? Model { get; set; }
    [JsonPropertyName("model_high")]
    public double ModelHigh { get; set; }
    [JsonPropertyName("nude_type")]
    public long NudeType { get; set; }
    [JsonPropertyName("offset_position_x")]
    public double OffsetPositionX { get; set; }
    [JsonPropertyName("offset_position_y")]
    public double OffsetPositionY { get; set; }
    [JsonPropertyName("offset_position_z")]
    public double OffsetPositionZ { get; set; }
    [JsonPropertyName("position_y_bathroom")]
    public double PositionYBathroom { get; set; }
    [JsonPropertyName("scale_bathroom")]
    public double ScaleBathroom { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("show_incamera_radius")]
    public double ShowIncameraRadius { get; set; }
    [JsonPropertyName("sink_camera_path")]
    public string? SinkCameraPath { get; set; }
    [JsonPropertyName("sm_id")]
    public string? SmId { get; set; }
    [JsonPropertyName("standard_bathroom")]
    public long StandardBathroom { get; set; }
    [JsonPropertyName("standard_dapo")]
    public long StandardDapo { get; set; }
    [JsonPropertyName("standard_normal")]
    public long StandardNormal { get; set; }
}
