// <auto-generated />
// Table: config_building_tv_res (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildingTvRes
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("play_weight")]
    public long PlayWeight { get; set; }
    [JsonPropertyName("tv_key")]
    public string? TvKey { get; set; }
    [JsonPropertyName("tv_res")]
    public string? TvRes { get; set; }
}
