// <auto-generated />
// Table: config_askill_dict_projectile (rows: 906)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAskillDictProjectile
{
    [JsonPropertyName("act_after_target_death")]
    public long ActAfterTargetDeath { get; set; }
    [JsonPropertyName("could_silence")]
    public long CouldSilence { get; set; }
    [JsonPropertyName("create_delta_euler")]
    public long CreateDeltaEuler { get; set; }
    [JsonPropertyName("create_pos_range")]
    public List<long>? CreatePosRange { get; set; }
    [JsonPropertyName("create_pos_type")]
    public long CreatePosType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("life_circle")]
    public long LifeCircle { get; set; }
    [JsonPropertyName("mix")]
    public long Mix { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("prj_class")]
    public long PrjClass { get; set; }
    [JsonPropertyName("projectile_ctrl")]
    public List<long>? ProjectileCtrl { get; set; }
    [JsonPropertyName("projectile_type")]
    public long ProjectileType { get; set; }
    [JsonPropertyName("random_weight")]
    public long RandomWeight { get; set; }
    [JsonPropertyName("select_mode")]
    public long SelectMode { get; set; }
    [JsonPropertyName("skill_type")]
    public long SkillType { get; set; }
    [JsonPropertyName("special")]
    public long Special { get; set; }
}
