// <auto-generated />
// Table: config_scene_weather (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSceneWeather
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("sw_id")]
    public long SwId { get; set; }
    [JsonPropertyName("weather_echange_light_id")]
    public List<object>? WeatherEchangeLightId { get; set; }
    [JsonPropertyName("weather_exchange_particle_id_s")]
    public List<object>? WeatherExchangeParticleIdS { get; set; }
    [JsonPropertyName("weather_type")]
    public string? WeatherType { get; set; }
}
