// <auto-generated />
// Table: config_activity_bgm_period (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigActivityBgmPeriod
{
    [JsonPropertyName("envir_bgm")]
    public string? EnvirBgm { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("weights")]
    public long Weights { get; set; }
}
