// <auto-generated />
// Table: config_battle_air_control_coefficient (rows: 19)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAirControlCoefficient
{
    [JsonPropertyName("air_control_state")]
    public long AirControlState { get; set; }
    [JsonPropertyName("bacc_id")]
    public string? BaccId { get; set; }
    [JsonPropertyName("damage_rate")]
    public double DamageRate { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("injured_rate")]
    public double InjuredRate { get; set; }
    [JsonPropertyName("max_range")]
    public double MaxRange { get; set; }
    [JsonPropertyName("min_range")]
    public double MinRange { get; set; }
}
