// <auto-generated />
// Table: config_activity_extract (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigActivityExtract
{
    [JsonPropertyName("drop_reward_id")]
    public List<List<long>>? DropRewardId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_cost")]
    public List<long>? ItemCost { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("reward_key")]
    public List<long>? RewardKey { get; set; }
}
