// <auto-generated />
// Table: config_gift (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGift
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("gift_type")]
    public long GiftType { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("match_value_group")]
    public List<long>? MatchValueGroup { get; set; }
    [JsonPropertyName("match_value_power")]
    public List<long>? MatchValuePower { get; set; }
    [JsonPropertyName("match_valueup_rate")]
    public long MatchValueupRate { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("not_match_value_group")]
    public List<long>? NotMatchValueGroup { get; set; }
    [JsonPropertyName("not_match_value_power")]
    public List<long>? NotMatchValuePower { get; set; }
    [JsonPropertyName("notmatch_valueup_rate")]
    public long NotmatchValueupRate { get; set; }
    [JsonPropertyName("price")]
    public List<long>? Price { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("quility_background")]
    public string? QuilityBackground { get; set; }
}
