// <auto-generated />
// Table: config_equip_levelbreak_item (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipLevelbreakItem
{
    [JsonPropertyName("item_cost")]
    public List<List<long>>? ItemCost { get; set; }
    [JsonPropertyName("level_id")]
    public long LevelId { get; set; }
    [JsonPropertyName("level_rank")]
    public List<long>? LevelRank { get; set; }
    [JsonPropertyName("unlock_item")]
    public List<long>? UnlockItem { get; set; }
}
