// <auto-generated />
// Table: config_ship_break (rows: 5277)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipBreak
{
    [JsonPropertyName("break_item")]
    public List<object>? BreakItem { get; set; }
    [JsonPropertyName("break_item_mub")]
    public List<long>? BreakItemMub { get; set; }
    [JsonPropertyName("break_to")]
    public string? BreakTo { get; set; }
    [JsonPropertyName("break_usableitem_mub")]
    public List<long>? BreakUsableitemMub { get; set; }
    [JsonPropertyName("currency_cost")]
    public List<long>? CurrencyCost { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("min_level")]
    public long MinLevel { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("remould_item")]
    public List<object>? RemouldItem { get; set; }
    [JsonPropertyName("remould_to")]
    public string? RemouldTo { get; set; }
    [JsonPropertyName("sb_id")]
    public long SbId { get; set; }
    [JsonPropertyName("ship_break_effect_id_list")]
    public List<long>? ShipBreakEffectIdList { get; set; }
    [JsonPropertyName("value_effect_id_list")]
    public List<long>? ValueEffectIdList { get; set; }
    [JsonPropertyName("value_effect_power_list")]
    public List<long>? ValueEffectPowerList { get; set; }
}
