// <auto-generated />
// Table: config_pskill_dict_select_item (rows: 67)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictSelectItem
{
    [JsonPropertyName("condition_func")]
    public string? ConditionFunc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("param")]
    public string? Param { get; set; }
    [JsonPropertyName("select_condition")]
    public long SelectCondition { get; set; }
    [JsonPropertyName("select_prop_id")]
    public long SelectPropId { get; set; }
    [JsonPropertyName("select_value")]
    public double SelectValue { get; set; }
    [JsonPropertyName("select_value_lvadd")]
    public double SelectValueLvadd { get; set; }
    [JsonPropertyName("select_value_type")]
    public long SelectValueType { get; set; }
    [JsonPropertyName("value_compare_type")]
    public long ValueCompareType { get; set; }
}
