// <auto-generated />
// Table: config_building_wall_res (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildingWallRes
{
    [JsonPropertyName("total_layer")]
    public long TotalLayer { get; set; }
    [JsonPropertyName("wall_id")]
    public long WallId { get; set; }
    [JsonPropertyName("wall_res")]
    public string? WallRes { get; set; }
    [JsonPropertyName("wall_type")]
    public long WallType { get; set; }
}
