// <auto-generated />
// Table: config_sportsmeet_score (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSportsmeetScore
{
    [JsonPropertyName("desc")]
    public List<List<string>>? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("if_rank")]
    public long IfRank { get; set; }
    [JsonPropertyName("score")]
    public List<List<long>>? Score { get; set; }
    [JsonPropertyName("score_type")]
    public long ScoreType { get; set; }
    [JsonPropertyName("sport_type")]
    public long SportType { get; set; }
}
