// <auto-generated />
// Table: config_plot_episode_wedding (rows: 680)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeWedding
{
    [JsonPropertyName("Gradually_appear")]
    public List<List<double>>? GraduallyAppear { get; set; }
    [JsonPropertyName("Gradually_disappear")]
    public List<List<double>>? GraduallyDisappear { get; set; }
    [JsonPropertyName("auto_next_time")]
    public long AutoNextTime { get; set; }
    [JsonPropertyName("auto_read")]
    public long AutoRead { get; set; }
    [JsonPropertyName("barrage_ctrl")]
    public long BarrageCtrl { get; set; }
    [JsonPropertyName("bg_animation")]
    public List<object>? BgAnimation { get; set; }
    [JsonPropertyName("black_scene")]
    public List<object>? BlackScene { get; set; }
    [JsonPropertyName("black_scene_color")]
    public string? BlackSceneColor { get; set; }
    [JsonPropertyName("black_scene_timing")]
    public long BlackSceneTiming { get; set; }
    [JsonPropertyName("branch1_parameter")]
    public List<long>? Branch1Parameter { get; set; }
    [JsonPropertyName("branch2_parameter")]
    public List<object>? Branch2Parameter { get; set; }
    [JsonPropertyName("branch3_parameter")]
    public List<object>? Branch3Parameter { get; set; }
    [JsonPropertyName("branch4_parameter")]
    public List<object>? Branch4Parameter { get; set; }
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("cut_bg_animation")]
    public long CutBgAnimation { get; set; }
    [JsonPropertyName("cut_scentence")]
    public long CutScentence { get; set; }
    [JsonPropertyName("cut_screen_effect")]
    public long CutScreenEffect { get; set; }
    [JsonPropertyName("dialog_animation")]
    public List<object>? DialogAnimation { get; set; }
    [JsonPropertyName("initial_position_offset")]
    public List<object>? InitialPositionOffset { get; set; }
    [JsonPropertyName("is_mask")]
    public List<object>? IsMask { get; set; }
    [JsonPropertyName("log")]
    public long Log { get; set; }
    [JsonPropertyName("meanwhile_ship")]
    public List<object>? MeanwhileShip { get; set; }
    [JsonPropertyName("mirror")]
    public List<object>? Mirror { get; set; }
    [JsonPropertyName("multistep_branch")]
    public string? MultistepBranch { get; set; }
    [JsonPropertyName("new_screen_effect")]
    public List<object>? NewScreenEffect { get; set; }
    [JsonPropertyName("other_talker_next_position")]
    public List<object>? OtherTalkerNextPosition { get; set; }
    [JsonPropertyName("plot_episode_branch1_name")]
    public string? PlotEpisodeBranch1Name { get; set; }
    [JsonPropertyName("plot_episode_branch2_name")]
    public string? PlotEpisodeBranch2Name { get; set; }
    [JsonPropertyName("plot_episode_branch3_name")]
    public string? PlotEpisodeBranch3Name { get; set; }
    [JsonPropertyName("plot_episode_branch4_name")]
    public string? PlotEpisodeBranch4Name { get; set; }
    [JsonPropertyName("plot_episode_end_event")]
    public List<object>? PlotEpisodeEndEvent { get; set; }
    [JsonPropertyName("plot_episode_id")]
    public long PlotEpisodeId { get; set; }
    [JsonPropertyName("plot_episode_skip")]
    public long PlotEpisodeSkip { get; set; }
    [JsonPropertyName("plot_episode_step_id")]
    public long PlotEpisodeStepId { get; set; }
    [JsonPropertyName("plot_episode_type")]
    public long PlotEpisodeType { get; set; }
    [JsonPropertyName("scene_res_path")]
    public string? SceneResPath { get; set; }
    [JsonPropertyName("scene_type")]
    public string? SceneType { get; set; }
    [JsonPropertyName("screen_animation")]
    public List<object>? ScreenAnimation { get; set; }
    [JsonPropertyName("screen_effect")]
    public string? ScreenEffect { get; set; }
    [JsonPropertyName("ship_scale")]
    public List<object>? ShipScale { get; set; }
    [JsonPropertyName("show_dialog")]
    public long ShowDialog { get; set; }
    [JsonPropertyName("static_scene_res_path")]
    public string? StaticSceneResPath { get; set; }
    [JsonPropertyName("step")]
    public long Step { get; set; }
    [JsonPropertyName("talker_expression")]
    public List<object>? TalkerExpression { get; set; }
    [JsonPropertyName("talker_id")]
    public long TalkerId { get; set; }
    [JsonPropertyName("talker_initial_position")]
    public List<long>? TalkerInitialPosition { get; set; }
    [JsonPropertyName("talker_name")]
    public string? TalkerName { get; set; }
    [JsonPropertyName("talker_next_position")]
    public List<long>? TalkerNextPosition { get; set; }
    [JsonPropertyName("talker_tween")]
    public List<object>? TalkerTween { get; set; }
    [JsonPropertyName("text_size")]
    public long TextSize { get; set; }
}
