// <auto-generated />
// Table: config_guildwar_rank (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildwarRank
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("range")]
    public List<long>? Range { get; set; }
    [JsonPropertyName("range_desc")]
    public string? RangeDesc { get; set; }
    [JsonPropertyName("rank_name")]
    public string? RankName { get; set; }
    [JsonPropertyName("rank_pic")]
    public string? RankPic { get; set; }
    [JsonPropertyName("rank_reward")]
    public long RankReward { get; set; }
}
