// <auto-generated />
// Table: config_value_effect (rows: 85)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigValueEffect
{
    [JsonPropertyName("activity_effect_desc")]
    public string? ActivityEffectDesc { get; set; }
    [JsonPropertyName("activity_effect_type")]
    public long ActivityEffectType { get; set; }
    [JsonPropertyName("activity_value_show")]
    public List<double>? ActivityValueShow { get; set; }
    [JsonPropertyName("buff_background")]
    public string? BuffBackground { get; set; }
    [JsonPropertyName("buff_icon")]
    public string? BuffIcon { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
    [JsonPropertyName("type_show")]
    public string? TypeShow { get; set; }
    [JsonPropertyName("value_show")]
    public string? ValueShow { get; set; }
    [JsonPropertyName("values")]
    public string? Values { get; set; }
}
