// <auto-generated />
// Table: config_item_info (rows: 731)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigItemInfo
{
    [JsonPropertyName("blind_box_id")]
    public List<long>? BlindBoxId { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("eff_time")]
    public double EffTime { get; set; }
    [JsonPropertyName("effect_name")]
    public string? EffectName { get; set; }
    [JsonPropertyName("existtime")]
    public long Existtime { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_small")]
    public string? IconSmall { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("nation_text")]
    public List<long>? NationText { get; set; }
    [JsonPropertyName("open_type")]
    public long OpenType { get; set; }
    [JsonPropertyName("prefab_type")]
    public long PrefabType { get; set; }
    [JsonPropertyName("price")]
    public List<List<long>>? Price { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("recommend_bg1")]
    public string? RecommendBg1 { get; set; }
    [JsonPropertyName("recommend_bg2")]
    public string? RecommendBg2 { get; set; }
    [JsonPropertyName("ryza_formula_id")]
    public long RyzaFormulaId { get; set; }
    [JsonPropertyName("ryza_type")]
    public List<long>? RyzaType { get; set; }
    [JsonPropertyName("ryza_type_num")]
    public long RyzaTypeNum { get; set; }
    [JsonPropertyName("saleable")]
    public long Saleable { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
    [JsonPropertyName("shop_bg")]
    public string? ShopBg { get; set; }
    [JsonPropertyName("show_in_shop")]
    public long ShowInShop { get; set; }
    [JsonPropertyName("show_type")]
    public long ShowType { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
