// <auto-generated />
// Table: config_bd_limited (rows: 24)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBdLimited
{
    [JsonPropertyName("bd_class")]
    public long BdClass { get; set; }
    [JsonPropertyName("bd_number")]
    public long BdNumber { get; set; }
    [JsonPropertyName("bd_obj")]
    public long BdObj { get; set; }
    [JsonPropertyName("bd_obj1")]
    public long BdObj1 { get; set; }
    [JsonPropertyName("bd_prop")]
    public long BdProp { get; set; }
    [JsonPropertyName("bd_prop1")]
    public long BdProp1 { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("limit_type")]
    public string? LimitType { get; set; }
    [JsonPropertyName("operation")]
    public long Operation { get; set; }
}
