// <auto-generated />
// Table: config_mission_display (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMissionDisplay
{
    [JsonPropertyName("desc")]
    public long Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("mission_eca_desc")]
    public long MissionEcaDesc { get; set; }
    [JsonPropertyName("mission_eca_desc_type")]
    public long MissionEcaDescType { get; set; }
    [JsonPropertyName("name")]
    public long Name { get; set; }
}
