// <auto-generated />
// Table: config_building_camera_parameters (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildingCameraParameters
{
    [JsonPropertyName("angle_speed")]
    public double AngleSpeed { get; set; }
    [JsonPropertyName("angle_x_max")]
    public long AngleXMax { get; set; }
    [JsonPropertyName("angle_x_min")]
    public double AngleXMin { get; set; }
    [JsonPropertyName("angle_y_max")]
    public long AngleYMax { get; set; }
    [JsonPropertyName("angle_y_min")]
    public long AngleYMin { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("lerp_accel")]
    public long LerpAccel { get; set; }
    [JsonPropertyName("max_distance")]
    public long MaxDistance { get; set; }
    [JsonPropertyName("min_distance")]
    public long MinDistance { get; set; }
    [JsonPropertyName("move_speed")]
    public double MoveSpeed { get; set; }
    [JsonPropertyName("pos_x_max")]
    public double PosXMax { get; set; }
    [JsonPropertyName("pos_x_min")]
    public long PosXMin { get; set; }
    [JsonPropertyName("pos_z_max")]
    public double PosZMax { get; set; }
    [JsonPropertyName("pos_z_min")]
    public long PosZMin { get; set; }
    [JsonPropertyName("rotation_mode")]
    public long RotationMode { get; set; }
    [JsonPropertyName("scene_resources")]
    public string? SceneResources { get; set; }
    [JsonPropertyName("scroll_speed")]
    public double ScrollSpeed { get; set; }
}
