// <auto-generated />
// Table: config_guildboxscore (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildboxscore
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("maxnum")]
    public long Maxnum { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
}
