// <auto-generated />
// Table: config_battle_fleet_show (rows: 63)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleFleetShow
{
    [JsonPropertyName("head")]
    public string? Head { get; set; }
    [JsonPropertyName("head_in_field")]
    public string? HeadInField { get; set; }
    [JsonPropertyName("head_in_field_sel")]
    public string? HeadInFieldSel { get; set; }
    [JsonPropertyName("head_sel")]
    public string? HeadSel { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
