// <auto-generated />
// Table: config_island (rows: 1087)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigIsland
{
    [JsonPropertyName("disappear_effect")]
    public string? DisappearEffect { get; set; }
    [JsonPropertyName("i_id")]
    public long IId { get; set; }
    [JsonPropertyName("icon_name")]
    public string? IconName { get; set; }
    [JsonPropertyName("icon_scale")]
    public double IconScale { get; set; }
    [JsonPropertyName("model")]
    public string? Model { get; set; }
    [JsonPropertyName("model_scale")]
    public double ModelScale { get; set; }
    [JsonPropertyName("sp_id")]
    public string? SpId { get; set; }
    [JsonPropertyName("uicon_Inmap")]
    public string? UiconInmap { get; set; }
}
