// <auto-generated />
// Table: config_strategy (rows: 17)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigStrategy
{
    [JsonPropertyName("activation_cost")]
    public long ActivationCost { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("lineup")]
    public List<long>? Lineup { get; set; }
    [JsonPropertyName("num_add")]
    public string? NumAdd { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("recommend")]
    public List<long>? Recommend { get; set; }
    [JsonPropertyName("skillgroup1")]
    public string? Skillgroup1 { get; set; }
    [JsonPropertyName("skillgroup2")]
    public string? Skillgroup2 { get; set; }
    [JsonPropertyName("skillgroup3")]
    public string? Skillgroup3 { get; set; }
    [JsonPropertyName("skillgroup_pos1")]
    public string? SkillgroupPos1 { get; set; }
    [JsonPropertyName("skillgroup_pos2")]
    public string? SkillgroupPos2 { get; set; }
    [JsonPropertyName("skillgroup_pos3")]
    public string? SkillgroupPos3 { get; set; }
    [JsonPropertyName("skillgroup_pos4")]
    public string? SkillgroupPos4 { get; set; }
    [JsonPropertyName("skillgroup_pos5")]
    public string? SkillgroupPos5 { get; set; }
    [JsonPropertyName("skillgroup_pos6")]
    public string? SkillgroupPos6 { get; set; }
    [JsonPropertyName("strategy1_condition")]
    public List<long>? Strategy1Condition { get; set; }
    [JsonPropertyName("strategy2_condition")]
    public List<object>? Strategy2Condition { get; set; }
    [JsonPropertyName("strategy3_condition")]
    public List<object>? Strategy3Condition { get; set; }
    [JsonPropertyName("strategy_ai_id")]
    public long StrategyAiId { get; set; }
    [JsonPropertyName("strategy_ai_priority")]
    public long StrategyAiPriority { get; set; }
    [JsonPropertyName("strategy_dec1")]
    public string? StrategyDec1 { get; set; }
    [JsonPropertyName("strategy_dec2")]
    public string? StrategyDec2 { get; set; }
    [JsonPropertyName("strategy_dec3")]
    public string? StrategyDec3 { get; set; }
    [JsonPropertyName("strategy_flag")]
    public long StrategyFlag { get; set; }
    [JsonPropertyName("strategy_icon")]
    public string? StrategyIcon { get; set; }
    [JsonPropertyName("strategy_limit_p1")]
    public List<long>? StrategyLimitP1 { get; set; }
    [JsonPropertyName("strategy_limit_type")]
    public List<long>? StrategyLimitType { get; set; }
    [JsonPropertyName("strategy_name")]
    public string? StrategyName { get; set; }
    [JsonPropertyName("talent_type")]
    public List<long>? TalentType { get; set; }
    [JsonPropertyName("tip")]
    public List<string>? Tip { get; set; }
    [JsonPropertyName("tip1")]
    public string? Tip1 { get; set; }
    [JsonPropertyName("tip2")]
    public string? Tip2 { get; set; }
    [JsonPropertyName("tip3")]
    public string? Tip3 { get; set; }
}
