// <auto-generated />
// Table: config_drop_item (rows: 2499)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDropItem
{
    [JsonPropertyName("drop")]
    public List<List<long>>? Drop { get; set; }
    [JsonPropertyName("drop_alone")]
    public List<List<long>>? DropAlone { get; set; }
    [JsonPropertyName("drop_alone_count")]
    public long DropAloneCount { get; set; }
    [JsonPropertyName("drop_count")]
    public long DropCount { get; set; }
    [JsonPropertyName("drop_rate")]
    public long DropRate { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_put_back")]
    public long IsPutBack { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("no_gain_first")]
    public long NoGainFirst { get; set; }
    [JsonPropertyName("used_count")]
    public long UsedCount { get; set; }
}
