// <auto-generated />
// Table: config_ship_fleet (rows: 378)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipFleet
{
    [JsonPropertyName("air_defence")]
    public long AirDefence { get; set; }
    [JsonPropertyName("break_num")]
    public long BreakNum { get; set; }
    [JsonPropertyName("cannot_marry")]
    public long CannotMarry { get; set; }
    [JsonPropertyName("combination_open")]
    public long CombinationOpen { get; set; }
    [JsonPropertyName("common_break_item")]
    public long CommonBreakItem { get; set; }
    [JsonPropertyName("equip_fashion_type")]
    public List<long>? EquipFashionType { get; set; }
    [JsonPropertyName("forbidden_id")]
    public List<long>? ForbiddenId { get; set; }
    [JsonPropertyName("gun")]
    public long Gun { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("init_star")]
    public long InitStar { get; set; }
    [JsonPropertyName("is_open_fashion")]
    public long IsOpenFashion { get; set; }
    [JsonPropertyName("lock_type")]
    public long LockType { get; set; }
    [JsonPropertyName("maneuver")]
    public long Maneuver { get; set; }
    [JsonPropertyName("max_star")]
    public long MaxStar { get; set; }
    [JsonPropertyName("plane")]
    public long Plane { get; set; }
    [JsonPropertyName("plot_cover")]
    public string? PlotCover { get; set; }
    [JsonPropertyName("power_type")]
    public long PowerType { get; set; }
    [JsonPropertyName("remould")]
    public List<long>? Remould { get; set; }
    [JsonPropertyName("remould_icon")]
    public List<string>? RemouldIcon { get; set; }
    [JsonPropertyName("remould_num")]
    public long RemouldNum { get; set; }
    [JsonPropertyName("same_character")]
    public List<long>? SameCharacter { get; set; }
    [JsonPropertyName("sf_special_bgm")]
    public List<string>? SfSpecialBgm { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("survival")]
    public long Survival { get; set; }
    [JsonPropertyName("torpedo")]
    public long Torpedo { get; set; }
    [JsonPropertyName("valentine_gift")]
    public long ValentineGift { get; set; }
}
