// <auto-generated />
// Table: config_worker (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigWorker
{
    [JsonPropertyName("addworkerhp")]
    public long Addworkerhp { get; set; }
    [JsonPropertyName("addworkerhptime")]
    public long Addworkerhptime { get; set; }
    [JsonPropertyName("chargehp")]
    public List<long>? Chargehp { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("workerhplevelup")]
    public List<long>? Workerhplevelup { get; set; }
    [JsonPropertyName("workerhpmax")]
    public long Workerhpmax { get; set; }
}
