// <auto-generated />
// Table: config_minigame_ai_type (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameAiType
{
    [JsonPropertyName("decs")]
    public string? Decs { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
