// <auto-generated />
// Table: config_pskill_dict_group (rows: 2845)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictGroup
{
    [JsonPropertyName("active_condition")]
    public List<object>? ActiveCondition { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("desc2")]
    public string? Desc2 { get; set; }
    [JsonPropertyName("desc_color")]
    public List<object>? DescColor { get; set; }
    [JsonPropertyName("desc_val")]
    public List<object>? DescVal { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("intial_level")]
    public long IntialLevel { get; set; }
    [JsonPropertyName("is_callback")]
    public long IsCallback { get; set; }
    [JsonPropertyName("level_value_effect")]
    public List<long>? LevelValueEffect { get; set; }
    [JsonPropertyName("max_level")]
    public long MaxLevel { get; set; }
    [JsonPropertyName("param_list")]
    public List<List<long>>? ParamList { get; set; }
    [JsonPropertyName("pskill_body")]
    public long PskillBody { get; set; }
    [JsonPropertyName("pskill_dict_display_id")]
    public long PskillDictDisplayId { get; set; }
    [JsonPropertyName("script_list")]
    public List<string>? ScriptList { get; set; }
    [JsonPropertyName("skill_desc")]
    public string? SkillDesc { get; set; }
    [JsonPropertyName("skill_id_array")]
    public List<long>? SkillIdArray { get; set; }
    [JsonPropertyName("skill_replace")]
    public List<List<long>>? SkillReplace { get; set; }
    [JsonPropertyName("talent_name")]
    public string? TalentName { get; set; }
    [JsonPropertyName("talent_type")]
    public long TalentType { get; set; }
    [JsonPropertyName("upgrade_materials")]
    public List<List<long>>? UpgradeMaterials { get; set; }
    [JsonPropertyName("upgrade_materials_mub")]
    public List<List<List<long>>>? UpgradeMaterialsMub { get; set; }
}
