// <auto-generated />
// Table: config_tower_activity (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTowerActivity
{
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("battle_point_cost")]
    public long BattlePointCost { get; set; }
    [JsonPropertyName("battle_point_default")]
    public long BattlePointDefault { get; set; }
    [JsonPropertyName("battle_point_min")]
    public long BattlePointMin { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("load_copy")]
    public long LoadCopy { get; set; }
    [JsonPropertyName("page_name")]
    public string? PageName { get; set; }
    [JsonPropertyName("quick_copy_s")]
    public long QuickCopyS { get; set; }
    [JsonPropertyName("quick_pass")]
    public List<long>? QuickPass { get; set; }
    [JsonPropertyName("reset_buff_times")]
    public long ResetBuffTimes { get; set; }
    [JsonPropertyName("reset_period")]
    public long ResetPeriod { get; set; }
}
