// <auto-generated />
// Table: config_form_change (rows: 20)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFormChange
{
    [JsonPropertyName("base_point")]
    public long BasePoint { get; set; }
    [JsonPropertyName("fc_id")]
    public string? FcId { get; set; }
    [JsonPropertyName("form_from")]
    public long FormFrom { get; set; }
    [JsonPropertyName("form_target")]
    public long FormTarget { get; set; }
    [JsonPropertyName("play_duration")]
    public long PlayDuration { get; set; }
}
