// <auto-generated />
// Table: config_plot_episode (rows: 2341)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisode
{
    [JsonPropertyName("Gradually_appear")]
    public List<List<double>>? GraduallyAppear { get; set; }
    [JsonPropertyName("Gradually_disappear")]
    public List<List<double>>? GraduallyDisappear { get; set; }
    [JsonPropertyName("auto_next_time")]
    public double AutoNextTime { get; set; }
    [JsonPropertyName("auto_read")]
    public long AutoRead { get; set; }
    [JsonPropertyName("barrage_ctrl")]
    public long BarrageCtrl { get; set; }
    [JsonPropertyName("black_scene")]
    public List<double>? BlackScene { get; set; }
    [JsonPropertyName("black_scene_timing")]
    public long BlackSceneTiming { get; set; }
    [JsonPropertyName("branch1_parameter")]
    public List<long>? Branch1Parameter { get; set; }
    [JsonPropertyName("branch2_parameter")]
    public List<long>? Branch2Parameter { get; set; }
    [JsonPropertyName("branch3_parameter")]
    public List<long>? Branch3Parameter { get; set; }
    [JsonPropertyName("branch4_parameter")]
    public List<object>? Branch4Parameter { get; set; }
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("cut_scentence")]
    public long CutScentence { get; set; }
    [JsonPropertyName("dialog_animation")]
    public List<long>? DialogAnimation { get; set; }
    [JsonPropertyName("initial_position_offset")]
    public List<List<long>>? InitialPositionOffset { get; set; }
    [JsonPropertyName("is_mask")]
    public List<long>? IsMask { get; set; }
    [JsonPropertyName("log")]
    public long Log { get; set; }
    [JsonPropertyName("meanwhile_ship")]
    public List<List<long>>? MeanwhileShip { get; set; }
    [JsonPropertyName("mirror")]
    public List<object>? Mirror { get; set; }
    [JsonPropertyName("other_talker_next_position")]
    public List<List<long>>? OtherTalkerNextPosition { get; set; }
    [JsonPropertyName("plot_episode_branch1_name")]
    public string? PlotEpisodeBranch1Name { get; set; }
    [JsonPropertyName("plot_episode_branch2_name")]
    public string? PlotEpisodeBranch2Name { get; set; }
    [JsonPropertyName("plot_episode_branch3_name")]
    public string? PlotEpisodeBranch3Name { get; set; }
    [JsonPropertyName("plot_episode_branch4_name")]
    public string? PlotEpisodeBranch4Name { get; set; }
    [JsonPropertyName("plot_episode_end_event")]
    public List<object>? PlotEpisodeEndEvent { get; set; }
    [JsonPropertyName("plot_episode_id")]
    public long PlotEpisodeId { get; set; }
    [JsonPropertyName("plot_episode_skip")]
    public long PlotEpisodeSkip { get; set; }
    [JsonPropertyName("plot_episode_step_id")]
    public long PlotEpisodeStepId { get; set; }
    [JsonPropertyName("plot_episode_type")]
    public long PlotEpisodeType { get; set; }
    [JsonPropertyName("scene_res_path")]
    public string? SceneResPath { get; set; }
    [JsonPropertyName("scene_type")]
    public string? SceneType { get; set; }
    [JsonPropertyName("screen_animation")]
    public List<long>? ScreenAnimation { get; set; }
    [JsonPropertyName("screen_effect")]
    public string? ScreenEffect { get; set; }
    [JsonPropertyName("step")]
    public long Step { get; set; }
    [JsonPropertyName("talker_expression")]
    public List<List<long>>? TalkerExpression { get; set; }
    [JsonPropertyName("talker_id")]
    public long TalkerId { get; set; }
    [JsonPropertyName("talker_initial_position")]
    public List<long>? TalkerInitialPosition { get; set; }
    [JsonPropertyName("talker_name")]
    public string? TalkerName { get; set; }
    [JsonPropertyName("talker_next_position")]
    public List<long>? TalkerNextPosition { get; set; }
    [JsonPropertyName("talker_tween")]
    public List<List<long>>? TalkerTween { get; set; }
    [JsonPropertyName("text_size")]
    public long TextSize { get; set; }
}
