// <auto-generated />
// Table: config_teaching_personal_info (rows: 23)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTeachingPersonalInfo
{
    [JsonPropertyName("group")]
    public long Group { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
}
