// <auto-generated />
// Table: config_example (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExample
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("require_condition_list")]
    public List<List<object>>? RequireConditionList { get; set; }
}
