// <auto-generated />
// Table: config_plot_episode_tween (rows: 255)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeTween
{
    [JsonPropertyName("delay_time")]
    public double DelayTime { get; set; }
    [JsonPropertyName("talker_action_from")]
    public long TalkerActionFrom { get; set; }
    [JsonPropertyName("talker_action_number")]
    public long TalkerActionNumber { get; set; }
    [JsonPropertyName("talker_action_oncetime")]
    public double TalkerActionOncetime { get; set; }
    [JsonPropertyName("talker_action_to")]
    public long TalkerActionTo { get; set; }
    [JsonPropertyName("talker_action_type")]
    public long TalkerActionType { get; set; }
    [JsonPropertyName("talker_action_x")]
    public List<double>? TalkerActionX { get; set; }
    [JsonPropertyName("talker_action_y")]
    public List<double>? TalkerActionY { get; set; }
    [JsonPropertyName("talker_action_z")]
    public List<long>? TalkerActionZ { get; set; }
    [JsonPropertyName("talker_tween_type")]
    public long TalkerTweenType { get; set; }
    [JsonPropertyName("tween_id")]
    public long TweenId { get; set; }
}
