// <auto-generated />
// Table: config_minigame_buff_type (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameBuffType
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("effect_path")]
    public string? EffectPath { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
