// <auto-generated />
// Table: config_ship_talent_activate_condition (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipTalentActivateCondition
{
    [JsonPropertyName("client_ignore")]
    public long ClientIgnore { get; set; }
    [JsonPropertyName("condition_name")]
    public string? ConditionName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
