// <auto-generated />
// Table: config_ship_class_index (rows: 78)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipClassIndex
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("ship_class")]
    public string? ShipClass { get; set; }
    [JsonPropertyName("ship_speed")]
    public double ShipSpeed { get; set; }
}
