// <auto-generated />
// Table: config_formation_pos (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFormationPos
{
    [JsonPropertyName("delta_x")]
    public double DeltaX { get; set; }
    [JsonPropertyName("delta_y")]
    public double DeltaY { get; set; }
    [JsonPropertyName("f_id")]
    public long FId { get; set; }
    [JsonPropertyName("fp_id")]
    public long FpId { get; set; }
    [JsonPropertyName("p_id")]
    public long PId { get; set; }
}
