// <auto-generated />
// Table: config_currency (rows: 33)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCurrency
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_multilevel_small")]
    public List<string>? IconMultilevelSmall { get; set; }
    [JsonPropertyName("icon_small")]
    public string? IconSmall { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
}
