// <auto-generated />
// Table: config_ship_behaviour_and_camera_info (rows: 542)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipBehaviourAndCameraInfo
{
    [JsonPropertyName("anim_voice_access")]
    public List<string>? AnimVoiceAccess { get; set; }
    [JsonPropertyName("be_formula")]
    public string? BeFormula { get; set; }
    [JsonPropertyName("behavior_time")]
    public long BehaviorTime { get; set; }
    [JsonPropertyName("behaviour_info_group")]
    public string? BehaviourInfoGroup { get; set; }
    [JsonPropertyName("camera_info_group")]
    public string? CameraInfoGroup { get; set; }
    [JsonPropertyName("caption_access")]
    public List<string>? CaptionAccess { get; set; }
    [JsonPropertyName("combat_resources")]
    public long CombatResources { get; set; }
    [JsonPropertyName("countenance_resource")]
    public List<string>? CountenanceResource { get; set; }
    [JsonPropertyName("cv_cutoff")]
    public long CvCutoff { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("shader_Controller")]
    public string? ShaderController { get; set; }
    [JsonPropertyName("ship_id")]
    public string? ShipId { get; set; }
    [JsonPropertyName("shock_time")]
    public List<object>? ShockTime { get; set; }
    [JsonPropertyName("transition_meltdown")]
    public long TransitionMeltdown { get; set; }
    [JsonPropertyName("use_state")]
    public string? UseState { get; set; }
    [JsonPropertyName("vibration_time")]
    public List<object>? VibrationTime { get; set; }
    [JsonPropertyName("voice_access")]
    public List<string>? VoiceAccess { get; set; }
}
