// <auto-generated />
// Table: config_air_attack_spe (rows: 75)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAirAttackSpe
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("radius")]
    public long Radius { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("speed_time")]
    public long SpeedTime { get; set; }
}
