// <auto-generated />
// Table: config_minigame_copy (rows: 123)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameCopy
{
    [JsonPropertyName("bgm")]
    public string? Bgm { get; set; }
    [JsonPropertyName("camera_info")]
    public List<List<double>>? CameraInfo { get; set; }
    [JsonPropertyName("camera_size")]
    public double CameraSize { get; set; }
    [JsonPropertyName("camera_speed")]
    public long CameraSpeed { get; set; }
    [JsonPropertyName("copy_order")]
    public long CopyOrder { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_num_show")]
    public List<long>? ItemNumShow { get; set; }
    [JsonPropertyName("item_random")]
    public List<List<long>>? ItemRandom { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("next_copy")]
    public long NextCopy { get; set; }
    [JsonPropertyName("player_life")]
    public long PlayerLife { get; set; }
    [JsonPropertyName("scenes")]
    public string? Scenes { get; set; }
    [JsonPropertyName("score_desc")]
    public long ScoreDesc { get; set; }
    [JsonPropertyName("skill_id")]
    public long SkillId { get; set; }
    [JsonPropertyName("special_area")]
    public List<long>? SpecialArea { get; set; }
    [JsonPropertyName("tips_image")]
    public string? TipsImage { get; set; }
    [JsonPropertyName("victory_condition")]
    public long VictoryCondition { get; set; }
}
