// <auto-generated />
// Table: config_loading (rows: 22)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigLoading
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("loading_down")]
    public string? LoadingDown { get; set; }
    [JsonPropertyName("loading_up")]
    public string? LoadingUp { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
