// <auto-generated />
// Table: config_equip_skill_type (rows: 22)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipSkillType
{
    [JsonPropertyName("aerial_attack")]
    public long AerialAttack { get; set; }
    [JsonPropertyName("aerial_bomb")]
    public long AerialBomb { get; set; }
    [JsonPropertyName("aerial_search")]
    public long AerialSearch { get; set; }
    [JsonPropertyName("aerial_torpedo")]
    public long AerialTorpedo { get; set; }
    [JsonPropertyName("bomb")]
    public long Bomb { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("equip_type_id")]
    public long EquipTypeId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("main_gun")]
    public long MainGun { get; set; }
    [JsonPropertyName("second_gun")]
    public long SecondGun { get; set; }
    [JsonPropertyName("show_name")]
    public string? ShowName { get; set; }
    [JsonPropertyName("to_air")]
    public long ToAir { get; set; }
    [JsonPropertyName("torpedo")]
    public long Torpedo { get; set; }
}
