// <auto-generated />
// Table: config_support_effect (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSupportEffect
{
    [JsonPropertyName("effect_name")]
    public string? EffectName { get; set; }
    [JsonPropertyName("effect_type")]
    public long EffectType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("parameter1")]
    public long Parameter1 { get; set; }
    [JsonPropertyName("parameter2")]
    public long Parameter2 { get; set; }
    [JsonPropertyName("parameter3")]
    public long Parameter3 { get; set; }
    [JsonPropertyName("support_id")]
    public long SupportId { get; set; }
}
