// <auto-generated />
// Table: config_specialdraw (rows: 407)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSpecialdraw
{
    [JsonPropertyName("close_script")]
    public string? CloseScript { get; set; }
    [JsonPropertyName("close_script_param")]
    public List<long>? CloseScriptParam { get; set; }
    [JsonPropertyName("cycle_param")]
    public long CycleParam { get; set; }
    [JsonPropertyName("cycle_type")]
    public List<long>? CycleType { get; set; }
    [JsonPropertyName("drop_item")]
    public long DropItem { get; set; }
    [JsonPropertyName("enter_reset_type")]
    public long EnterResetType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_show_num")]
    public long MaxShowNum { get; set; }
    [JsonPropertyName("priority")]
    public long Priority { get; set; }
    [JsonPropertyName("probability_script")]
    public string? ProbabilityScript { get; set; }
    [JsonPropertyName("probability_script_param")]
    public List<long>? ProbabilityScriptParam { get; set; }
    [JsonPropertyName("reset_ssr_type")]
    public long ResetSsrType { get; set; }
    [JsonPropertyName("ssr_reset_num")]
    public long SsrResetNum { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
