// <auto-generated />
// Table: config_prop (rows: 484)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigProp
{
    [JsonPropertyName("attack_coefficient")]
    public List<long>? AttackCoefficient { get; set; }
    [JsonPropertyName("attack_value")]
    public List<long>? AttackValue { get; set; }
    [JsonPropertyName("default_value")]
    public double DefaultValue { get; set; }
    [JsonPropertyName("defense_coefficient")]
    public List<long>? DefenseCoefficient { get; set; }
    [JsonPropertyName("defense_value")]
    public List<long>? DefenseValue { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("prop_value_type")]
    public long PropValueType { get; set; }
}
