// <auto-generated />
// Table: config_ui_battlepage_config_ios (rows: 81)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigUiBattlepageConfigIos
{
    [JsonPropertyName("game_type")]
    public long GameType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("part_name")]
    public string? PartName { get; set; }
    [JsonPropertyName("part_path")]
    public string? PartPath { get; set; }
    [JsonPropertyName("show_time")]
    public List<double>? ShowTime { get; set; }
    [JsonPropertyName("switch_mode")]
    public long SwitchMode { get; set; }
}
