// <auto-generated />
// Table: config_ship_gained_way (rows: 97)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipGainedWay
{
    [JsonPropertyName("gained_way")]
    public string? GainedWay { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
