// <auto-generated />
// Table: config_rank (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRank
{
    [JsonPropertyName("copy_id")]
    public List<long>? CopyId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
