// <auto-generated />
// Table: config_emoji (rows: 96)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEmoji
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_id")]
    public long ItemId { get; set; }
    [JsonPropertyName("item_unlock")]
    public long ItemUnlock { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("picture")]
    public string? Picture { get; set; }
    [JsonPropertyName("plot_id")]
    public List<long>? PlotId { get; set; }
    [JsonPropertyName("unlock_tip")]
    public long UnlockTip { get; set; }
}
