// <auto-generated />
// Table: config_minigame_special_area (rows: 98)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameSpecialArea
{
    [JsonPropertyName("area")]
    public List<List<double>>? Area { get; set; }
    [JsonPropertyName("buff_id")]
    public long BuffId { get; set; }
    [JsonPropertyName("decs")]
    public string? Decs { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
