// <auto-generated />
// Table: config_rechargecondition (rows: 20)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRechargecondition
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("param1")]
    public long Param1 { get; set; }
    [JsonPropertyName("param2")]
    public long Param2 { get; set; }
    [JsonPropertyName("param3")]
    public long Param3 { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
