// <auto-generated />
// Table: config_activity_extract_ur (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigActivityExtractUr
{
    [JsonPropertyName("chapter_id")]
    public long ChapterId { get; set; }
    [JsonPropertyName("copy_display_id")]
    public long CopyDisplayId { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("drop_reward_id")]
    public List<List<long>>? DropRewardId { get; set; }
    [JsonPropertyName("fragment_id")]
    public long FragmentId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_cost")]
    public List<long>? ItemCost { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("next_card_id")]
    public long NextCardId { get; set; }
    [JsonPropertyName("reward_key")]
    public List<long>? RewardKey { get; set; }
    [JsonPropertyName("special_drop")]
    public List<object>? SpecialDrop { get; set; }
    [JsonPropertyName("special_drop_times")]
    public long SpecialDropTimes { get; set; }
    [JsonPropertyName("surprise_drop")]
    public List<long>? SurpriseDrop { get; set; }
}
