// <auto-generated />
// Table: config_game_limits (rows: 570)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGameLimits
{
    [JsonPropertyName("client_ignore")]
    public long ClientIgnore { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("limit_param")]
    public List<long>? LimitParam { get; set; }
    [JsonPropertyName("limit_type")]
    public long LimitType { get; set; }
    [JsonPropertyName("next_level_id")]
    public long NextLevelId { get; set; }
    [JsonPropertyName("operation")]
    public long Operation { get; set; }
    [JsonPropertyName("script_name")]
    public string? ScriptName { get; set; }
}
