// <auto-generated />
// Table: config_copy_rank_drop (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopyRankDrop
{
    [JsonPropertyName("drop_group")]
    public List<List<long>>? DropGroup { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
