// <auto-generated />
// Table: config_fleet_patrol_pos (rows: 1311)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFleetPatrolPos
{
    [JsonPropertyName("f_id")]
    public long FId { get; set; }
    [JsonPropertyName("fpr_id")]
    public long FprId { get; set; }
    [JsonPropertyName("sp_id")]
    public List<string>? SpId { get; set; }
}
