// <auto-generated />
// Table: config_special_buff (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSpecialBuff
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("language_id")]
    public long LanguageId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
