// <auto-generated />
// Table: config_flag_res (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFlagRes
{
    [JsonPropertyName("number")]
    public long Number { get; set; }
    [JsonPropertyName("res_path")]
    public string? ResPath { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
