// <auto-generated />
// Table: config_draw (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDraw
{
    [JsonPropertyName("denominator")]
    public long Denominator { get; set; }
    [JsonPropertyName("draw_time")]
    public long DrawTime { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
