// <auto-generated />
// Table: config_ship_formation_coefficient (rows: 80)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipFormationCoefficient
{
    [JsonPropertyName("formation_id")]
    public long FormationId { get; set; }
    [JsonPropertyName("prop_id")]
    public long PropId { get; set; }
    [JsonPropertyName("stpc_id")]
    public long StpcId { get; set; }
    [JsonPropertyName("value_coe")]
    public double ValueCoe { get; set; }
    [JsonPropertyName("weather_type")]
    public long WeatherType { get; set; }
}
