// <auto-generated />
// Table: config_pskill_dict_change (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictChange
{
    [JsonPropertyName("buff_factor_export_type")]
    public long BuffFactorExportType { get; set; }
    [JsonPropertyName("buff_factor_id")]
    public long BuffFactorId { get; set; }
    [JsonPropertyName("buff_factor_type")]
    public long BuffFactorType { get; set; }
    [JsonPropertyName("buff_id")]
    public long BuffId { get; set; }
    [JsonPropertyName("buff_type")]
    public long BuffType { get; set; }
    [JsonPropertyName("change_dict_id")]
    public long ChangeDictId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("operation_type")]
    public long OperationType { get; set; }
    [JsonPropertyName("skill_export_type")]
    public long SkillExportType { get; set; }
    [JsonPropertyName("skill_id")]
    public long SkillId { get; set; }
}
