// <auto-generated />
// Table: config_country_info (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCountryInfo
{
    [JsonPropertyName("country_name")]
    public string? CountryName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
