// <auto-generated />
// Table: config_music (rows: 13)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMusic
{
    [JsonPropertyName("clear_other")]
    public long ClearOther { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("event_name")]
    public string? EventName { get; set; }
    [JsonPropertyName("m_id")]
    public string? MId { get; set; }
    [JsonPropertyName("music_model")]
    public string? MusicModel { get; set; }
    [JsonPropertyName("music_name")]
    public string? MusicName { get; set; }
    [JsonPropertyName("param")]
    public long Param { get; set; }
    [JsonPropertyName("play")]
    public long Play { get; set; }
    [JsonPropertyName("volume")]
    public long Volume { get; set; }
}
