// <auto-generated />
// Table: config_shop (rows: 104)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShop
{
    [JsonPropertyName("activatetime")]
    public long Activatetime { get; set; }
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("bg")]
    public string? Bg { get; set; }
    [JsonPropertyName("cumulate_times")]
    public long CumulateTimes { get; set; }
    [JsonPropertyName("currency_show")]
    public List<List<long>>? CurrencyShow { get; set; }
    [JsonPropertyName("currency_type")]
    public long CurrencyType { get; set; }
    [JsonPropertyName("dependence_id")]
    public long DependenceId { get; set; }
    [JsonPropertyName("display_type")]
    public long DisplayType { get; set; }
    [JsonPropertyName("fun_type")]
    public long FunType { get; set; }
    [JsonPropertyName("functionid")]
    public long Functionid { get; set; }
    [JsonPropertyName("grid_count")]
    public long GridCount { get; set; }
    [JsonPropertyName("help")]
    public long Help { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_select")]
    public string? IconSelect { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("init_times")]
    public long InitTimes { get; set; }
    [JsonPropertyName("is_hide")]
    public long IsHide { get; set; }
    [JsonPropertyName("is_random")]
    public long IsRandom { get; set; }
    [JsonPropertyName("jump_shop_id")]
    public long JumpShopId { get; set; }
    [JsonPropertyName("level_deblocking")]
    public long LevelDeblocking { get; set; }
    [JsonPropertyName("limit")]
    public List<object>? Limit { get; set; }
    [JsonPropertyName("max_count")]
    public long MaxCount { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("open_period")]
    public long OpenPeriod { get; set; }
    [JsonPropertyName("open_period_area")]
    public List<long>? OpenPeriodArea { get; set; }
    [JsonPropertyName("open_type")]
    public string? OpenType { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("platform")]
    public long Platform { get; set; }
    [JsonPropertyName("price")]
    public List<long>? Price { get; set; }
    [JsonPropertyName("quick_buy")]
    public long QuickBuy { get; set; }
    [JsonPropertyName("recovery_time")]
    public long RecoveryTime { get; set; }
    [JsonPropertyName("red_dot")]
    public List<long>? RedDot { get; set; }
    [JsonPropertyName("refresh_time")]
    public List<long>? RefreshTime { get; set; }
    [JsonPropertyName("shelf")]
    public long Shelf { get; set; }
    [JsonPropertyName("shelf_list")]
    public List<long>? ShelfList { get; set; }
    [JsonPropertyName("shop_type")]
    public long ShopType { get; set; }
    [JsonPropertyName("sold_out")]
    public long SoldOut { get; set; }
    [JsonPropertyName("time_after_server_start")]
    public long TimeAfterServerStart { get; set; }
    [JsonPropertyName("unlock_before_shop_id")]
    public long UnlockBeforeShopId { get; set; }
}
