// <auto-generated />
// Table: config_fleet (rows: 3589)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFleet
{
    [JsonPropertyName("ai_battle_limit_length")]
    public long AiBattleLimitLength { get; set; }
    [JsonPropertyName("air_attack_plane_speed")]
    public long AirAttackPlaneSpeed { get; set; }
    [JsonPropertyName("air_search_plane_speed")]
    public long AirSearchPlaneSpeed { get; set; }
    [JsonPropertyName("baf_id")]
    public long BafId { get; set; }
    [JsonPropertyName("battle_assess")]
    public long BattleAssess { get; set; }
    [JsonPropertyName("battle_center_pos")]
    public string? BattleCenterPos { get; set; }
    [JsonPropertyName("battle_radiu")]
    public long BattleRadiu { get; set; }
    [JsonPropertyName("battle_time")]
    public long BattleTime { get; set; }
    [JsonPropertyName("battlefield_info")]
    public long BattlefieldInfo { get; set; }
    [JsonPropertyName("birth_sp_id")]
    public string? BirthSpId { get; set; }
    [JsonPropertyName("chase_speed")]
    public long ChaseSpeed { get; set; }
    [JsonPropertyName("copy_attacheds")]
    public List<object>? CopyAttacheds { get; set; }
    [JsonPropertyName("copy_attacheds_formation")]
    public long CopyAttachedsFormation { get; set; }
    [JsonPropertyName("copy_enemys")]
    public List<long>? CopyEnemys { get; set; }
    [JsonPropertyName("copy_enemys_formation")]
    public long CopyEnemysFormation { get; set; }
    [JsonPropertyName("copy_type")]
    public long CopyType { get; set; }
    [JsonPropertyName("daily_extra_drop")]
    public long DailyExtraDrop { get; set; }
    [JsonPropertyName("day_battle_anim")]
    public long DayBattleAnim { get; set; }
    [JsonPropertyName("day_bgm")]
    public string? DayBgm { get; set; }
    [JsonPropertyName("default_threat")]
    public long DefaultThreat { get; set; }
    [JsonPropertyName("detect_air_cd")]
    public long DetectAirCd { get; set; }
    [JsonPropertyName("detect_air_range")]
    public long DetectAirRange { get; set; }
    [JsonPropertyName("detect_air_view_radius")]
    public long DetectAirViewRadius { get; set; }
    [JsonPropertyName("display_name")]
    public string? DisplayName { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("f_id")]
    public long FId { get; set; }
    [JsonPropertyName("fleet_icon")]
    public string? FleetIcon { get; set; }
    [JsonPropertyName("fleet_ui_eb_id")]
    public List<object>? FleetUiEbId { get; set; }
    [JsonPropertyName("fleet_ui_effect_roots")]
    public List<object>? FleetUiEffectRoots { get; set; }
    [JsonPropertyName("is_influence_by_evaluate")]
    public long IsInfluenceByEvaluate { get; set; }
    [JsonPropertyName("is_last_fleet")]
    public long IsLastFleet { get; set; }
    [JsonPropertyName("is_plane_continental")]
    public long IsPlaneContinental { get; set; }
    [JsonPropertyName("lighting_shells_cd")]
    public long LightingShellsCd { get; set; }
    [JsonPropertyName("longNight_battle_time")]
    public long LongNightBattleTime { get; set; }
    [JsonPropertyName("long_health_enemys")]
    public List<object>? LongHealthEnemys { get; set; }
    [JsonPropertyName("long_night_bgm")]
    public string? LongNightBgm { get; set; }
    [JsonPropertyName("night_battle_anim")]
    public long NightBattleAnim { get; set; }
    [JsonPropertyName("night_battle_time")]
    public long NightBattleTime { get; set; }
    [JsonPropertyName("night_bgm")]
    public string? NightBgm { get; set; }
    [JsonPropertyName("other_drop_arg")]
    public List<long>? OtherDropArg { get; set; }
    [JsonPropertyName("other_drop_id")]
    public long OtherDropId { get; set; }
    [JsonPropertyName("other_drop_ids")]
    public List<long>? OtherDropIds { get; set; }
    [JsonPropertyName("patrol_speed")]
    public long PatrolSpeed { get; set; }
    [JsonPropertyName("plane_attack_cd")]
    public long PlaneAttackCd { get; set; }
    [JsonPropertyName("player_exp")]
    public long PlayerExp { get; set; }
    [JsonPropertyName("random_factor")]
    public List<long>? RandomFactor { get; set; }
    [JsonPropertyName("recommend_ce")]
    public string? RecommendCe { get; set; }
    [JsonPropertyName("search3d_item_id")]
    public long Search3dItemId { get; set; }
    [JsonPropertyName("settle_drop_arg")]
    public List<long>? SettleDropArg { get; set; }
    [JsonPropertyName("settle_drop_id")]
    public long SettleDropId { get; set; }
    [JsonPropertyName("settle_drop_ids")]
    public List<long>? SettleDropIds { get; set; }
    [JsonPropertyName("settlement_assess")]
    public long SettlementAssess { get; set; }
    [JsonPropertyName("ship_exp")]
    public long ShipExp { get; set; }
    [JsonPropertyName("supple_consumption")]
    public long SuppleConsumption { get; set; }
    [JsonPropertyName("support_speed")]
    public long SupportSpeed { get; set; }
    [JsonPropertyName("team_attack_switch")]
    public long TeamAttackSwitch { get; set; }
    [JsonPropertyName("threat_id")]
    public List<object>? ThreatId { get; set; }
}
