// <auto-generated />
// Table: config_tower_topic (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTowerTopic
{
    [JsonPropertyName("area_final_copy")]
    public List<List<long>>? AreaFinalCopy { get; set; }
    [JsonPropertyName("copy_list")]
    public List<List<long>>? CopyList { get; set; }
    [JsonPropertyName("copy_list_name")]
    public List<string>? CopyListName { get; set; }
    [JsonPropertyName("features_list")]
    public List<List<string>>? FeaturesList { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("tower_map")]
    public string? TowerMap { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
