// <auto-generated />
// Table: config_guildoffer_info (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildofferInfo
{
    [JsonPropertyName("apply_max_num")]
    public long ApplyMaxNum { get; set; }
    [JsonPropertyName("guildrewardmail")]
    public long Guildrewardmail { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("maxbuytime")]
    public long Maxbuytime { get; set; }
    [JsonPropertyName("noguild_name")]
    public string? NoguildName { get; set; }
    [JsonPropertyName("personrewardmail")]
    public long Personrewardmail { get; set; }
    [JsonPropertyName("priceincrease")]
    public long Priceincrease { get; set; }
    [JsonPropertyName("quality_task_num")]
    public List<List<long>>? QualityTaskNum { get; set; }
    [JsonPropertyName("rank_minscore")]
    public long RankMinscore { get; set; }
    [JsonPropertyName("task_bg")]
    public List<string>? TaskBg { get; set; }
    [JsonPropertyName("ticketprice")]
    public List<long>? Ticketprice { get; set; }
}
