// <auto-generated />
// Table: config_pskill_dict_main (rows: 4564)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictMain
{
    [JsonPropertyName("condition_id_array")]
    public string? ConditionIdArray { get; set; }
    [JsonPropertyName("condition_ids")]
    public string? ConditionIds { get; set; }
    [JsonPropertyName("event_order")]
    public long EventOrder { get; set; }
    [JsonPropertyName("event_params")]
    public string? EventParams { get; set; }
    [JsonPropertyName("event_target")]
    public long EventTarget { get; set; }
    [JsonPropertyName("event_type")]
    public long EventType { get; set; }
    [JsonPropertyName("execute_count")]
    public long ExecuteCount { get; set; }
    [JsonPropertyName("export_func")]
    public string? ExportFunc { get; set; }
    [JsonPropertyName("export_odds_add")]
    public double ExportOddsAdd { get; set; }
    [JsonPropertyName("export_odds_base")]
    public double ExportOddsBase { get; set; }
    [JsonPropertyName("export_target_prop_id")]
    public long ExportTargetPropId { get; set; }
    [JsonPropertyName("export_type")]
    public long ExportType { get; set; }
    [JsonPropertyName("general_formula")]
    public long GeneralFormula { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("operation_buff_dict_id")]
    public List<long>? OperationBuffDictId { get; set; }
    [JsonPropertyName("operation_flag_dict_id")]
    public List<long>? OperationFlagDictId { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("pskill_change")]
    public string? PskillChange { get; set; }
    [JsonPropertyName("pskill_change_info")]
    public long PskillChangeInfo { get; set; }
    [JsonPropertyName("pskill_delay")]
    public long PskillDelay { get; set; }
    [JsonPropertyName("pskill_delay_target_mode")]
    public long PskillDelayTargetMode { get; set; }
    [JsonPropertyName("pskill_factors")]
    public List<long>? PskillFactors { get; set; }
    [JsonPropertyName("pskill_factors_probability")]
    public List<object>? PskillFactorsProbability { get; set; }
    [JsonPropertyName("pskill_type_group")]
    public List<long>? PskillTypeGroup { get; set; }
    [JsonPropertyName("release_cd")]
    public long ReleaseCd { get; set; }
    [JsonPropertyName("release_cd_type")]
    public long ReleaseCdType { get; set; }
    [JsonPropertyName("release_max_operation")]
    public long ReleaseMaxOperation { get; set; }
    [JsonPropertyName("release_num_limit_count")]
    public long ReleaseNumLimitCount { get; set; }
    [JsonPropertyName("release_num_limit_type")]
    public long ReleaseNumLimitType { get; set; }
    [JsonPropertyName("release_type")]
    public long ReleaseType { get; set; }
    [JsonPropertyName("select_target_array")]
    public List<long>? SelectTargetArray { get; set; }
    [JsonPropertyName("skill_show_switch")]
    public long SkillShowSwitch { get; set; }
    [JsonPropertyName("trigger_probability")]
    public long TriggerProbability { get; set; }
    [JsonPropertyName("trigger_probability_group")]
    public string? TriggerProbabilityGroup { get; set; }
}
