// <auto-generated />
// Table: config_sportsmeet_achieve (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSportsmeetAchieve
{
    [JsonPropertyName("achieve_type")]
    public long AchieveType { get; set; }
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("sport_type")]
    public long SportType { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
}
