// <auto-generated />
// Table: config_battlepass_level (rows: 50)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattlepassLevel
{
    [JsonPropertyName("free_level_reward")]
    public long FreeLevelReward { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("level_exp")]
    public long LevelExp { get; set; }
    [JsonPropertyName("pay_level_reward")]
    public long PayLevelReward { get; set; }
    [JsonPropertyName("target_reward")]
    public long TargetReward { get; set; }
}
