// <auto-generated />
// Table: config_mask_word_test (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMaskWordTest
{
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
