// <auto-generated />
// Table: config_parameter (rows: 429)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigParameter
{
    [JsonPropertyName("arrValue")]
    public List<object>? ArrValue { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("parameter")]
    public string? Parameter { get; set; }
    [JsonPropertyName("value")]
    public long Value { get; set; }
}
