// <auto-generated />
// Table: config_pskill_dict_buff_factor_args (rows: 34)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictBuffFactorArgs
{
    [JsonPropertyName("arg_type")]
    public long ArgType { get; set; }
    [JsonPropertyName("arg_value")]
    public long ArgValue { get; set; }
    [JsonPropertyName("arg_value_add")]
    public long ArgValueAdd { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
