// <auto-generated />
// Table: config_skill_anim_detail_group (rows: 740)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimDetailGroup
{
    [JsonPropertyName("anim_speedup")]
    public long AnimSpeedup { get; set; }
    [JsonPropertyName("group")]
    public long Group { get; set; }
    [JsonPropertyName("skip_next_group")]
    public long SkipNextGroup { get; set; }
}
