// <auto-generated />
// Table: config_anniversary_video (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAnniversaryVideo
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("link")]
    public string? Link { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
}
