// <auto-generated />
// Table: config_days_activity_limited (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDaysActivityLimited
{
    [JsonPropertyName("bg")]
    public string? Bg { get; set; }
    [JsonPropertyName("count")]
    public long Count { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("outlinecolor")]
    public List<long>? Outlinecolor { get; set; }
    [JsonPropertyName("picture")]
    public string? Picture { get; set; }
    [JsonPropertyName("selected")]
    public string? Selected { get; set; }
    [JsonPropertyName("shop_goods")]
    public List<object>? ShopGoods { get; set; }
    [JsonPropertyName("shop_id")]
    public long ShopId { get; set; }
    [JsonPropertyName("task_activity")]
    public List<long>? TaskActivity { get; set; }
    [JsonPropertyName("task_stage")]
    public long TaskStage { get; set; }
    [JsonPropertyName("textcolor")]
    public string? Textcolor { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
