// <auto-generated />
// Table: config_battle_ammounition_effect (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAmmounitionEffect
{
    [JsonPropertyName("ammounition_max")]
    public long AmmounitionMax { get; set; }
    [JsonPropertyName("ammounition_min")]
    public long AmmounitionMin { get; set; }
    [JsonPropertyName("bae_id")]
    public long BaeId { get; set; }
    [JsonPropertyName("prop_id")]
    public long PropId { get; set; }
    [JsonPropertyName("value")]
    public double Value { get; set; }
}
