// <auto-generated />
// Table: config_equip_activity_extrapoint (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipActivityExtrapoint
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("extra_point_rate")]
    public long ExtraPointRate { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("parameter")]
    public List<long>? Parameter { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
