// <auto-generated />
// Table: config_ship_handbook (rows: 216)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipHandbook
{
    [JsonPropertyName("activatetime")]
    public long Activatetime { get; set; }
    [JsonPropertyName("activity")]
    public long Activity { get; set; }
    [JsonPropertyName("air_defence")]
    public long AirDefence { get; set; }
    [JsonPropertyName("enter_wish_time")]
    public long EnterWishTime { get; set; }
    [JsonPropertyName("gun")]
    public long Gun { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_wish")]
    public long IsWish { get; set; }
    [JsonPropertyName("magazine_tag")]
    public List<long>? MagazineTag { get; set; }
    [JsonPropertyName("maneuver")]
    public long Maneuver { get; set; }
    [JsonPropertyName("plane")]
    public long Plane { get; set; }
    [JsonPropertyName("pskill_show_id")]
    public List<long>? PskillShowId { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("ship_character_voice")]
    public string? ShipCharacterVoice { get; set; }
    [JsonPropertyName("ship_country")]
    public long ShipCountry { get; set; }
    [JsonPropertyName("ship_data_id")]
    public long ShipDataId { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_order")]
    public long ShipOrder { get; set; }
    [JsonPropertyName("ship_recommend")]
    public long ShipRecommend { get; set; }
    [JsonPropertyName("ship_setting")]
    public string? ShipSetting { get; set; }
    [JsonPropertyName("ship_skill")]
    public List<long>? ShipSkill { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("ship_voice_tag")]
    public long ShipVoiceTag { get; set; }
    [JsonPropertyName("show_state")]
    public long ShowState { get; set; }
    [JsonPropertyName("show_tag")]
    public long ShowTag { get; set; }
    [JsonPropertyName("survival")]
    public long Survival { get; set; }
    [JsonPropertyName("torpedo")]
    public long Torpedo { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("wish_activatetime")]
    public long WishActivatetime { get; set; }
    [JsonPropertyName("word_gained")]
    public List<long>? WordGained { get; set; }
    [JsonPropertyName("word_reconmend")]
    public string? WordReconmend { get; set; }
}
