// <auto-generated />
// Table: config_bathroom_item (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBathroomItem
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("frequency")]
    public long Frequency { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("once_exp")]
    public long OnceExp { get; set; }
    [JsonPropertyName("price")]
    public long Price { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
}
