// <auto-generated />
// Table: config_ryza_alchemy_item (rows: 564)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRyzaAlchemyItem
{
    [JsonPropertyName("back_item")]
    public List<long>? BackItem { get; set; }
    [JsonPropertyName("effect")]
    public List<List<object>>? Effect { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_type")]
    public long ItemType { get; set; }
    [JsonPropertyName("materials")]
    public List<long>? Materials { get; set; }
    [JsonPropertyName("position")]
    public List<long>? Position { get; set; }
    [JsonPropertyName("pre_item")]
    public List<long>? PreItem { get; set; }
}
