// <auto-generated />
// Table: config_battlefield_resource_blood (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattlefieldResourceBlood
{
    [JsonPropertyName("brFilterType")]
    public long BrFilterType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("numberRule")]
    public long NumberRule { get; set; }
    [JsonPropertyName("vals")]
    public List<long>? Vals { get; set; }
    [JsonPropertyName("value_or_percentage")]
    public long ValueOrPercentage { get; set; }
}
