// <auto-generated />
// Table: config_battle_ai_ship_info (rows: 95)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiShipInfo
{
    [JsonPropertyName("aerial_attack_weight")]
    public long AerialAttackWeight { get; set; }
    [JsonPropertyName("basi_id")]
    public long BasiId { get; set; }
    [JsonPropertyName("best_distance")]
    public long BestDistance { get; set; }
    [JsonPropertyName("best_distance_weight")]
    public long BestDistanceWeight { get; set; }
    [JsonPropertyName("main_gun_weight")]
    public long MainGunWeight { get; set; }
    [JsonPropertyName("second_gun_weight")]
    public long SecondGunWeight { get; set; }
    [JsonPropertyName("torpedo_weight")]
    public long TorpedoWeight { get; set; }
}
