// <auto-generated />
// Table: config_talenteffect (rows: 130)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTalenteffect
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("p1")]
    public long P1 { get; set; }
    [JsonPropertyName("p2")]
    public long P2 { get; set; }
    [JsonPropertyName("p3")]
    public long P3 { get; set; }
    [JsonPropertyName("p4")]
    public long P4 { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
