// <auto-generated />
// Table: config_plot_episode_audio_event (rows: 8607)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeAudioEvent
{
    [JsonPropertyName("audio_effect")]
    public string? AudioEffect { get; set; }
    [JsonPropertyName("audio_id")]
    public string? AudioId { get; set; }
    [JsonPropertyName("background_music")]
    public string? BackgroundMusic { get; set; }
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("exchange_music")]
    public string? ExchangeMusic { get; set; }
    [JsonPropertyName("plot_episode_id")]
    public long PlotEpisodeId { get; set; }
    [JsonPropertyName("plot_episode_step_id")]
    public long PlotEpisodeStepId { get; set; }
    [JsonPropertyName("preload")]
    public string? Preload { get; set; }
    [JsonPropertyName("scene_type")]
    public string? SceneType { get; set; }
    [JsonPropertyName("step")]
    public long Step { get; set; }
    [JsonPropertyName("talker_name")]
    public string? TalkerName { get; set; }
}
