// <auto-generated />
// Table: config_ship_consumption (rows: 1962)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipConsumption
{
    [JsonPropertyName("*")]
    public string? Value { get; set; }
    [JsonPropertyName("ammo")]
    public long Ammo { get; set; }
    [JsonPropertyName("fuel")]
    public long Fuel { get; set; }
    [JsonPropertyName("repair_item")]
    public List<string>? RepairItem { get; set; }
    [JsonPropertyName("sc_id")]
    public long ScId { get; set; }
}
