// <auto-generated />
// Table: config_pushnotice (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPushnotice
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("notice")]
    public string? Notice { get; set; }
    [JsonPropertyName("text")]
    public string? Text { get; set; }
}
