// <auto-generated />
// Table: config_ar_battle_range (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigArBattleRange
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("dis_max")]
    public long DisMax { get; set; }
    [JsonPropertyName("dis_min")]
    public long DisMin { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
