// <auto-generated />
// Table: config_skill_anim_detail_group_count (rows: 39)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimDetailGroupCount
{
    [JsonPropertyName("anim_class")]
    public string? AnimClass { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("skill_anim_group")]
    public long SkillAnimGroup { get; set; }
    [JsonPropertyName("skill_anim_type")]
    public long SkillAnimType { get; set; }
    [JsonPropertyName("sta_id")]
    public long StaId { get; set; }
}
