// <auto-generated />
// Table: config_skill_fashion (rows: 71)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillFashion
{
    [JsonPropertyName("equip_fashion_show_type")]
    public long EquipFashionShowType { get; set; }
    [JsonPropertyName("equip_wear_type")]
    public long EquipWearType { get; set; }
    [JsonPropertyName("gunbattle_hit_skill_anim_detail_id")]
    public string? GunbattleHitSkillAnimDetailId { get; set; }
    [JsonPropertyName("gunbattle_start_skill_anim_detail_id")]
    public string? GunbattleStartSkillAnimDetailId { get; set; }
    [JsonPropertyName("search_hit_skill_anim_detail_id")]
    public string? SearchHitSkillAnimDetailId { get; set; }
    [JsonPropertyName("search_start_skill_anim_detail_id")]
    public string? SearchStartSkillAnimDetailId { get; set; }
    [JsonPropertyName("show_picture")]
    public string? ShowPicture { get; set; }
    [JsonPropertyName("skill_anim_eb_id")]
    public List<string>? SkillAnimEbId { get; set; }
    [JsonPropertyName("skill_fashion_id")]
    public long SkillFashionId { get; set; }
    [JsonPropertyName("skill_fashion_name")]
    public string? SkillFashionName { get; set; }
    [JsonPropertyName("srp_effect_id")]
    public List<string>? SrpEffectId { get; set; }
    [JsonPropertyName("trap_ste_id")]
    public long TrapSteId { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
