// <auto-generated />
// Table: config_minigame_infinite_copy (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameInfiniteCopy
{
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
