// <auto-generated />
// Table: config_form_change_point (rows: 255)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFormChangePoint
{
    [JsonPropertyName("base_point")]
    public long BasePoint { get; set; }
    [JsonPropertyName("delta_x_percent")]
    public double DeltaXPercent { get; set; }
    [JsonPropertyName("delta_z_percent")]
    public double DeltaZPercent { get; set; }
    [JsonPropertyName("fc_id")]
    public string? FcId { get; set; }
    [JsonPropertyName("fcp_id")]
    public string? FcpId { get; set; }
    [JsonPropertyName("move_point")]
    public long MovePoint { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("time_percent")]
    public double TimePercent { get; set; }
}
