// <auto-generated />
// Table: config_ship_model_animation (rows: 716)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipModelAnimation
{
    [JsonPropertyName("animLength")]
    public double AnimLength { get; set; }
    [JsonPropertyName("animName")]
    public string? AnimName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_battle")]
    public long IsBattle { get; set; }
    [JsonPropertyName("modelName")]
    public string? ModelName { get; set; }
}
