// <auto-generated />
// Table: config_equip_enhance_item (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipEnhanceItem
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("enhance_level_limit")]
    public List<long>? EnhanceLevelLimit { get; set; }
    [JsonPropertyName("exp")]
    public long Exp { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
}
