// <auto-generated />
// Table: config_ship (rows: 13)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShip
{
    [JsonPropertyName("angle_spped")]
    public long AngleSpped { get; set; }
    [JsonPropertyName("anti_crit")]
    public long AntiCrit { get; set; }
    [JsonPropertyName("attack")]
    public long Attack { get; set; }
    [JsonPropertyName("attack_levelup")]
    public long AttackLevelup { get; set; }
    [JsonPropertyName("battle_angle_speed")]
    public long BattleAngleSpeed { get; set; }
    [JsonPropertyName("carry_airplane_count")]
    public long CarryAirplaneCount { get; set; }
    [JsonPropertyName("crit")]
    public long Crit { get; set; }
    [JsonPropertyName("defense")]
    public long Defense { get; set; }
    [JsonPropertyName("defense_levelup")]
    public long DefenseLevelup { get; set; }
    [JsonPropertyName("dodge")]
    public long Dodge { get; set; }
    [JsonPropertyName("equip_attr_num_1")]
    public long EquipAttrNum1 { get; set; }
    [JsonPropertyName("equip_attr_num_2")]
    public long EquipAttrNum2 { get; set; }
    [JsonPropertyName("equip_attr_num_3")]
    public long EquipAttrNum3 { get; set; }
    [JsonPropertyName("equip_attr_num_4")]
    public long EquipAttrNum4 { get; set; }
    [JsonPropertyName("ewt_ids")]
    public List<string>? EwtIds { get; set; }
    [JsonPropertyName("fate")]
    public long Fate { get; set; }
    [JsonPropertyName("gun_range_type")]
    public long GunRangeType { get; set; }
    [JsonPropertyName("hit")]
    public long Hit { get; set; }
    [JsonPropertyName("hp")]
    public long Hp { get; set; }
    [JsonPropertyName("hp_levelup")]
    public long HpLevelup { get; set; }
    [JsonPropertyName("init_star")]
    public long InitStar { get; set; }
    [JsonPropertyName("max_star")]
    public long MaxStar { get; set; }
    [JsonPropertyName("model")]
    public string? Model { get; set; }
    [JsonPropertyName("model_height")]
    public long ModelHeight { get; set; }
    [JsonPropertyName("model_radius")]
    public long ModelRadius { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("ship_air_control")]
    public long ShipAirControl { get; set; }
    [JsonPropertyName("ship_air_control_levelup")]
    public long ShipAirControlLevelup { get; set; }
    [JsonPropertyName("ship_bomb_attack")]
    public long ShipBombAttack { get; set; }
    [JsonPropertyName("ship_bomb_attack_levelup")]
    public long ShipBombAttackLevelup { get; set; }
    [JsonPropertyName("ship_county")]
    public long ShipCounty { get; set; }
    [JsonPropertyName("ship_icon")]
    public string? ShipIcon { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_torpedo_attack")]
    public long ShipTorpedoAttack { get; set; }
    [JsonPropertyName("ship_torpedo_attack_levelup")]
    public long ShipTorpedoAttackLevelup { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("to_air_attack")]
    public long ToAirAttack { get; set; }
    [JsonPropertyName("to_air_attack_levelup")]
    public long ToAirAttackLevelup { get; set; }
    [JsonPropertyName("to_torpedo_attack")]
    public long ToTorpedoAttack { get; set; }
    [JsonPropertyName("to_torpedo_attack_levelup")]
    public long ToTorpedoAttackLevelup { get; set; }
    [JsonPropertyName("torpedo_attack")]
    public long TorpedoAttack { get; set; }
    [JsonPropertyName("torpedo_attack_levelup")]
    public long TorpedoAttackLevelup { get; set; }
    [JsonPropertyName("torpedo_defense")]
    public long TorpedoDefense { get; set; }
    [JsonPropertyName("torpedo_defense_levelup")]
    public long TorpedoDefenseLevelup { get; set; }
    [JsonPropertyName("view_range")]
    public long ViewRange { get; set; }
}
