// <auto-generated />
// Table: config_combination_ship (rows: 370)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCombinationShip
{
    [JsonPropertyName("before_id")]
    public long BeforeId { get; set; }
    [JsonPropertyName("break_item")]
    public List<List<long>>? BreakItem { get; set; }
    [JsonPropertyName("break_prop_up")]
    public List<object>? BreakPropUp { get; set; }
    [JsonPropertyName("break_prop_up_percent")]
    public List<List<long>>? BreakPropUpPercent { get; set; }
    [JsonPropertyName("break_star")]
    public long BreakStar { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public List<long>? Level { get; set; }
    [JsonPropertyName("levelup_item")]
    public List<List<long>>? LevelupItem { get; set; }
    [JsonPropertyName("next_id")]
    public long NextId { get; set; }
    [JsonPropertyName("prop_up")]
    public List<object>? PropUp { get; set; }
    [JsonPropertyName("prop_up_percent")]
    public List<List<long>>? PropUpPercent { get; set; }
    [JsonPropertyName("sf_id")]
    public long SfId { get; set; }
    [JsonPropertyName("skill_id")]
    public List<long>? SkillId { get; set; }
    [JsonPropertyName("star")]
    public long Star { get; set; }
}
