// <auto-generated />
// Table: config_eca_action (rows: 21)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEcaAction
{
    [JsonPropertyName("action_type")]
    public long ActionType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("param")]
    public List<long>? Param { get; set; }
}
