// <auto-generated />
// Table: config_island_group (rows: 537)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigIslandGroup
{
    [JsonPropertyName("ig_id")]
    public long IgId { get; set; }
    [JsonPropertyName("island_array")]
    public List<long>? IslandArray { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("points")]
    public List<string>? Points { get; set; }
}
