// <auto-generated />
// Table: config_random_last_name_ja (rows: 95)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRandomLastNameJa
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("lastName")]
    public string? LastName { get; set; }
}
