// <auto-generated />
// Table: config_buildinglevelup (rows: 35)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildinglevelup
{
    [JsonPropertyName("cleartime")]
    public List<object>? Cleartime { get; set; }
    [JsonPropertyName("costmoney")]
    public long Costmoney { get; set; }
    [JsonPropertyName("costwork")]
    public long Costwork { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("leveluptime")]
    public long Leveluptime { get; set; }
    [JsonPropertyName("officelevel")]
    public long Officelevel { get; set; }
    [JsonPropertyName("rawmaterial1")]
    public List<long>? Rawmaterial1 { get; set; }
    [JsonPropertyName("rawmaterial2")]
    public List<object>? Rawmaterial2 { get; set; }
    [JsonPropertyName("rawmaterial3")]
    public List<long>? Rawmaterial3 { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
