// <auto-generated />
// Table: config_treaty_buff (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTreatyBuff
{
    [JsonPropertyName("buff_icon")]
    public string? BuffIcon { get; set; }
    [JsonPropertyName("buff_star")]
    public long BuffStar { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("flag_new")]
    public long FlagNew { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("treaty_atk")]
    public string? TreatyAtk { get; set; }
    [JsonPropertyName("treaty_buff")]
    public List<long>? TreatyBuff { get; set; }
    [JsonPropertyName("treaty_hp")]
    public string? TreatyHp { get; set; }
}
