// <auto-generated />
// Table: config_pet_pskill_display (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPetPskillDisplay
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("pet_main_id")]
    public long PetMainId { get; set; }
    [JsonPropertyName("pskill_main_id")]
    public long PskillMainId { get; set; }
    [JsonPropertyName("skill_release_group_id")]
    public string? SkillReleaseGroupId { get; set; }
    [JsonPropertyName("use_state")]
    public string? UseState { get; set; }
}
