// <auto-generated />
// Table: config_task_guildoffer (rows: 34)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskGuildoffer
{
    [JsonPropertyName("applynum")]
    public long Applynum { get; set; }
    [JsonPropertyName("count_type")]
    public long CountType { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("limittime")]
    public long Limittime { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("qualitybg")]
    public string? Qualitybg { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
