// <auto-generated />
// Table: config_room (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRoom
{
    [JsonPropertyName("chapter_id")]
    public long ChapterId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("player_number")]
    public long PlayerNumber { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("zone_id")]
    public long ZoneId { get; set; }
}
