// <auto-generated />
// Table: config_sp_settings_dict (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSpSettingsDict
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
