// <auto-generated />
// Table: config_ui_config (rows: 421)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigUiConfig
{
    [JsonPropertyName("allwaysInMemery")]
    public long AllwaysInMemery { get; set; }
    [JsonPropertyName("bgm")]
    public string? Bgm { get; set; }
    [JsonPropertyName("canShowScene")]
    public long CanShowScene { get; set; }
    [JsonPropertyName("hide_type")]
    public long HideType { get; set; }
    [JsonPropertyName("hierarchy")]
    public long Hierarchy { get; set; }
    [JsonPropertyName("info")]
    public string? Info { get; set; }
    [JsonPropertyName("lua_class_path")]
    public string? LuaClassPath { get; set; }
    [JsonPropertyName("page_type")]
    public long PageType { get; set; }
    [JsonPropertyName("res_path")]
    public string? ResPath { get; set; }
    [JsonPropertyName("subGroup")]
    public long SubGroup { get; set; }
    [JsonPropertyName("topName")]
    public string? TopName { get; set; }
    [JsonPropertyName("ui_id")]
    public string? UiId { get; set; }
}
