// <auto-generated />
// Table: config_effect (rows: 517)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEffect
{
    [JsonPropertyName("audio_switch")]
    public long AudioSwitch { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("e_id")]
    public string? EId { get; set; }
    [JsonPropertyName("effect_model")]
    public string? EffectModel { get; set; }
    [JsonPropertyName("max_num")]
    public long MaxNum { get; set; }
}
