// <auto-generated />
// Table: config_askill_dict_prj_ctrl_logic (rows: 971)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAskillDictPrjCtrlLogic
{
    [JsonPropertyName("behaviour_params")]
    public string? BehaviourParams { get; set; }
    [JsonPropertyName("behaviour_target")]
    public long BehaviourTarget { get; set; }
    [JsonPropertyName("exe_delay")]
    public long ExeDelay { get; set; }
    [JsonPropertyName("exe_loading_time")]
    public long ExeLoadingTime { get; set; }
    [JsonPropertyName("exe_time")]
    public long ExeTime { get; set; }
    [JsonPropertyName("exe_type")]
    public long ExeType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("logic_behaviour")]
    public long LogicBehaviour { get; set; }
}
