// <auto-generated />
// Table: config_loading_tips (rows: 30)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigLoadingTips
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public List<long>? Level { get; set; }
    [JsonPropertyName("pl")]
    public List<long>? Pl { get; set; }
    [JsonPropertyName("tips")]
    public string? Tips { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
