// <auto-generated />
// Table: config_ship_hp_prop_change (rows: 180)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipHpPropChange
{
    [JsonPropertyName("hp_state")]
    public long HpState { get; set; }
    [JsonPropertyName("prop_id")]
    public long PropId { get; set; }
    [JsonPropertyName("stid")]
    public long Stid { get; set; }
    [JsonPropertyName("stpc_id")]
    public long StpcId { get; set; }
    [JsonPropertyName("value_coe")]
    public double ValueCoe { get; set; }
    [JsonPropertyName("weather_type")]
    public long WeatherType { get; set; }
}
