// <auto-generated />
// Table: config_skill_trigger (rows: 32)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTrigger
{
    [JsonPropertyName("skill_type")]
    public long SkillType { get; set; }
    [JsonPropertyName("st_id")]
    public long StId { get; set; }
    [JsonPropertyName("stg_id")]
    public long StgId { get; set; }
    [JsonPropertyName("trigger_cd")]
    public long TriggerCd { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
