// <auto-generated />
// Table: config_recipe_compose (rows: 16)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRecipeCompose
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item")]
    public List<long>? Item { get; set; }
    [JsonPropertyName("rawmaterial1")]
    public List<long>? Rawmaterial1 { get; set; }
    [JsonPropertyName("rawmaterial2")]
    public List<long>? Rawmaterial2 { get; set; }
    [JsonPropertyName("rawmaterial3")]
    public List<object>? Rawmaterial3 { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("typename")]
    public string? Typename { get; set; }
    [JsonPropertyName("unlocklevel")]
    public long Unlocklevel { get; set; }
}
