// <auto-generated />
// Table: config_skill_anim_type (rows: 17)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimType
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
