// <auto-generated />
// Table: config_battle_ai_escape (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiEscape
{
    [JsonPropertyName("ba_id")]
    public string? BaId { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("escape_target")]
    public string? EscapeTarget { get; set; }
    [JsonPropertyName("escape_type")]
    public long EscapeType { get; set; }
    [JsonPropertyName("escape_weight")]
    public long EscapeWeight { get; set; }
    [JsonPropertyName("fleet_id")]
    public string? FleetId { get; set; }
}
