// <auto-generated />
// Table: config_talentmain (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTalentmain
{
    [JsonPropertyName("background")]
    public string? Background { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("talentlist")]
    public List<long>? Talentlist { get; set; }
}
