// <auto-generated />
// Table: config_copy_demo (rows: 86)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopyDemo
{
    [JsonPropertyName("battlefield_id")]
    public long BattlefieldId { get; set; }
    [JsonPropertyName("copy_center")]
    public string? CopyCenter { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("palyer_birth")]
    public string? PalyerBirth { get; set; }
    [JsonPropertyName("player_path")]
    public List<List<string>>? PlayerPath { get; set; }
    [JsonPropertyName("scale_value")]
    public long ScaleValue { get; set; }
    [JsonPropertyName("ship_enemy_birth")]
    public List<List<long>>? ShipEnemyBirth { get; set; }
    [JsonPropertyName("ship_enemy_path")]
    public List<List<string>>? ShipEnemyPath { get; set; }
}
