// <auto-generated />
// Table: config_minigame_npc_info (rows: 45)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameNpcInfo
{
    [JsonPropertyName("ai")]
    public List<long>? Ai { get; set; }
    [JsonPropertyName("drop_item")]
    public List<long>? DropItem { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("size")]
    public List<double>? Size { get; set; }
    [JsonPropertyName("velocity")]
    public List<double>? Velocity { get; set; }
}
