// <auto-generated />
// Table: config_task_guild (rows: 102)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskGuild
{
    [JsonPropertyName("auto_reject_time")]
    public long AutoRejectTime { get; set; }
    [JsonPropertyName("count_type")]
    public long CountType { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("drop_show_id")]
    public List<long>? DropShowId { get; set; }
    [JsonPropertyName("extra_reward")]
    public long ExtraReward { get; set; }
    [JsonPropertyName("extra_reward_desc")]
    public string? ExtraRewardDesc { get; set; }
    [JsonPropertyName("extra_reward_ship_condition")]
    public List<long>? ExtraRewardShipCondition { get; set; }
    [JsonPropertyName("extra_reward_ship_num")]
    public long ExtraRewardShipNum { get; set; }
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("guild_exp_rewards")]
    public long GuildExpRewards { get; set; }
    [JsonPropertyName("guild_finish_num_max")]
    public long GuildFinishNumMax { get; set; }
    [JsonPropertyName("guild_finish_num_min")]
    public long GuildFinishNumMin { get; set; }
    [JsonPropertyName("guild_rewards")]
    public long GuildRewards { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_apply_num")]
    public long MaxApplyNum { get; set; }
    [JsonPropertyName("max_player_goal_num")]
    public long MaxPlayerGoalNum { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("per_contr_num")]
    public long PerContrNum { get; set; }
    [JsonPropertyName("player_level_max")]
    public long PlayerLevelMax { get; set; }
    [JsonPropertyName("player_level_min")]
    public long PlayerLevelMin { get; set; }
    [JsonPropertyName("player_rewards")]
    public long PlayerRewards { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
