// <auto-generated />
// Table: config_guide_compensation (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuideCompensation
{
    [JsonPropertyName("compensation_list")]
    public List<List<double>>? CompensationList { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("step_interval")]
    public List<long>? StepInterval { get; set; }
}
