// <auto-generated />
// Table: config_action_audio_bind (rows: 50)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigActionAudioBind
{
    [JsonPropertyName("action_name")]
    public string? ActionName { get; set; }
    [JsonPropertyName("audio_id")]
    public string? AudioId { get; set; }
    [JsonPropertyName("delay_time")]
    public long DelayTime { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("role_id")]
    public string? RoleId { get; set; }
}
