// <auto-generated />
// Table: config_behaviour_info_queue (rows: 1773)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBehaviourInfoQueue
{
    [JsonPropertyName("anim_name")]
    public string? AnimName { get; set; }
    [JsonPropertyName("bind_effect")]
    public List<string>? BindEffect { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("effect_closure")]
    public long EffectClosure { get; set; }
    [JsonPropertyName("effect_opentime")]
    public double EffectOpentime { get; set; }
    [JsonPropertyName("group")]
    public string? Group { get; set; }
    [JsonPropertyName("head_control_param")]
    public string? HeadControlParam { get; set; }
    [JsonPropertyName("head_control_type")]
    public long HeadControlType { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("is_loop")]
    public long IsLoop { get; set; }
    [JsonPropertyName("queue")]
    public long Queue { get; set; }
    [JsonPropertyName("repeat_play")]
    public long RepeatPlay { get; set; }
    [JsonPropertyName("speed")]
    public double Speed { get; set; }
}
