// <auto-generated />
// Table: config_extract_ship (rows: 183)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExtractShip
{
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("btn_num")]
    public long BtnNum { get; set; }
    [JsonPropertyName("btn_one_text")]
    public string? BtnOneText { get; set; }
    [JsonPropertyName("btn_ten_text")]
    public string? BtnTenText { get; set; }
    [JsonPropertyName("button_effect")]
    public List<object>? ButtonEffect { get; set; }
    [JsonPropertyName("button_image")]
    public List<string>? ButtonImage { get; set; }
    [JsonPropertyName("change_desc")]
    public List<long>? ChangeDesc { get; set; }
    [JsonPropertyName("change_show_pic")]
    public List<string>? ChangeShowPic { get; set; }
    [JsonPropertyName("change_type")]
    public List<long>? ChangeType { get; set; }
    [JsonPropertyName("change_up_name")]
    public List<List<long>>? ChangeUpName { get; set; }
    [JsonPropertyName("changetime")]
    public List<long>? Changetime { get; set; }
    [JsonPropertyName("close_draw_id")]
    public List<long>? CloseDrawId { get; set; }
    [JsonPropertyName("close_draw_num")]
    public long CloseDrawNum { get; set; }
    [JsonPropertyName("close_ship_id")]
    public List<long>? CloseShipId { get; set; }
    [JsonPropertyName("close_time")]
    public long CloseTime { get; set; }
    [JsonPropertyName("desc")]
    public List<long>? Desc { get; set; }
    [JsonPropertyName("drop_item_id")]
    public long DropItemId { get; set; }
    [JsonPropertyName("expend")]
    public List<List<long>>? Expend { get; set; }
    [JsonPropertyName("explore_image")]
    public List<string>? ExploreImage { get; set; }
    [JsonPropertyName("extract_reset_type")]
    public long ExtractResetType { get; set; }
    [JsonPropertyName("extract_type")]
    public long ExtractType { get; set; }
    [JsonPropertyName("force_open_time")]
    public long ForceOpenTime { get; set; }
    [JsonPropertyName("free_explore_period")]
    public long FreeExplorePeriod { get; set; }
    [JsonPropertyName("free_explore_refresh")]
    public long FreeExploreRefresh { get; set; }
    [JsonPropertyName("free_explore_type")]
    public long FreeExploreType { get; set; }
    [JsonPropertyName("free_ten_explore_refresh")]
    public long FreeTenExploreRefresh { get; set; }
    [JsonPropertyName("helpinfo_title")]
    public List<long>? HelpinfoTitle { get; set; }
    [JsonPropertyName("hundred_reward")]
    public List<List<long>>? HundredReward { get; set; }
    [JsonPropertyName("hundred_tips_image")]
    public List<string>? HundredTipsImage { get; set; }
    [JsonPropertyName("hundredleasttentimedesc")]
    public long Hundredleasttentimedesc { get; set; }
    [JsonPropertyName("hundredrewarddesc")]
    public long Hundredrewarddesc { get; set; }
    [JsonPropertyName("hundredtenrewarddesc")]
    public long Hundredtenrewarddesc { get; set; }
    [JsonPropertyName("hundredtimedesc")]
    public long Hundredtimedesc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_preview")]
    public long IsPreview { get; set; }
    [JsonPropertyName("is_show_time")]
    public long IsShowTime { get; set; }
    [JsonPropertyName("isshow_special_desc")]
    public long IsshowSpecialDesc { get; set; }
    [JsonPropertyName("name")]
    public List<string>? Name { get; set; }
    [JsonPropertyName("name_pic")]
    public List<string>? NamePic { get; set; }
    [JsonPropertyName("new_period")]
    public List<long>? NewPeriod { get; set; }
    [JsonPropertyName("new_period_area")]
    public List<List<long>>? NewPeriodArea { get; set; }
    [JsonPropertyName("new_ten_expend")]
    public List<long>? NewTenExpend { get; set; }
    [JsonPropertyName("newtwentyleasttentimedesc")]
    public long Newtwentyleasttentimedesc { get; set; }
    [JsonPropertyName("newtwentyrewarddesc")]
    public long Newtwentyrewarddesc { get; set; }
    [JsonPropertyName("newtwentytenrewarddesc")]
    public long Newtwentytenrewarddesc { get; set; }
    [JsonPropertyName("newtwentytimedesc")]
    public long Newtwentytimedesc { get; set; }
    [JsonPropertyName("onetimedesc")]
    public long Onetimedesc { get; set; }
    [JsonPropertyName("open_by_boss")]
    public long OpenByBoss { get; set; }
    [JsonPropertyName("open_daily_condition")]
    public long OpenDailyCondition { get; set; }
    [JsonPropertyName("open_limit")]
    public long OpenLimit { get; set; }
    [JsonPropertyName("reset_type")]
    public long ResetType { get; set; }
    [JsonPropertyName("reward_name")]
    public List<string>? RewardName { get; set; }
    [JsonPropertyName("reward_tips_image")]
    public List<string>? RewardTipsImage { get; set; }
    [JsonPropertyName("reward_type")]
    public List<List<long>>? RewardType { get; set; }
    [JsonPropertyName("ship_image")]
    public List<object>? ShipImage { get; set; }
    [JsonPropertyName("show_appear_num")]
    public long ShowAppearNum { get; set; }
    [JsonPropertyName("show_draw_id")]
    public long ShowDrawId { get; set; }
    [JsonPropertyName("show_order")]
    public List<long>? ShowOrder { get; set; }
    [JsonPropertyName("show_pic")]
    public List<string>? ShowPic { get; set; }
    [JsonPropertyName("show_ship")]
    public List<object>? ShowShip { get; set; }
    [JsonPropertyName("special_change_reward")]
    public List<long>? SpecialChangeReward { get; set; }
    [JsonPropertyName("special_draw_id")]
    public List<long>? SpecialDrawId { get; set; }
    [JsonPropertyName("special_info")]
    public string? SpecialInfo { get; set; }
    [JsonPropertyName("special_reward")]
    public long SpecialReward { get; set; }
    [JsonPropertyName("speical_ship_id")]
    public List<long>? SpeicalShipId { get; set; }
    [JsonPropertyName("sr_up_ship_info")]
    public List<List<long>>? SrUpShipInfo { get; set; }
    [JsonPropertyName("ssr_up_ship_info")]
    public List<List<long>>? SsrUpShipInfo { get; set; }
    [JsonPropertyName("statue")]
    public long Statue { get; set; }
    [JsonPropertyName("tag_duration")]
    public List<string>? TagDuration { get; set; }
    [JsonPropertyName("tag_group")]
    public long TagGroup { get; set; }
    [JsonPropertyName("tag_name")]
    public List<string>? TagName { get; set; }
    [JsonPropertyName("tentimedesc")]
    public long Tentimedesc { get; set; }
    [JsonPropertyName("time_desc")]
    public long TimeDesc { get; set; }
    [JsonPropertyName("toggle_bg")]
    public List<string>? ToggleBg { get; set; }
    [JsonPropertyName("toggle_check")]
    public List<string>? ToggleCheck { get; set; }
    [JsonPropertyName("twenty_drop")]
    public List<List<long>>? TwentyDrop { get; set; }
    [JsonPropertyName("twenty_drop_name")]
    public List<string>? TwentyDropName { get; set; }
    [JsonPropertyName("twentyleasttentimedesc")]
    public long Twentyleasttentimedesc { get; set; }
    [JsonPropertyName("twentyrewarddesc")]
    public long Twentyrewarddesc { get; set; }
    [JsonPropertyName("twentytenrewarddesc")]
    public long Twentytenrewarddesc { get; set; }
    [JsonPropertyName("twentytimedesc")]
    public long Twentytimedesc { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("up")]
    public List<double>? Up { get; set; }
    [JsonPropertyName("up_list")]
    public List<long>? UpList { get; set; }
    [JsonPropertyName("up_name")]
    public List<long>? UpName { get; set; }
    [JsonPropertyName("up_type")]
    public long UpType { get; set; }
}
