// <auto-generated />
// Table: config_formation_pos_ui (rows: 98)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFormationPosUi
{
    [JsonPropertyName("delta_x")]
    public double DeltaX { get; set; }
    [JsonPropertyName("delta_y")]
    public double DeltaY { get; set; }
    [JsonPropertyName("form_id")]
    public long FormId { get; set; }
    [JsonPropertyName("fpu_id")]
    public long FpuId { get; set; }
    [JsonPropertyName("order_id")]
    public long OrderId { get; set; }
    [JsonPropertyName("scale")]
    public double Scale { get; set; }
    [JsonPropertyName("ship_num")]
    public long ShipNum { get; set; }
}
