// <auto-generated />
// Table: config_ship_need_power_exp (rows: 4815)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipNeedPowerExp
{
    [JsonPropertyName("enhance_type")]
    public long EnhanceType { get; set; }
    [JsonPropertyName("need_power_exp")]
    public List<List<long>>? NeedPowerExp { get; set; }
    [JsonPropertyName("snp_id")]
    public long SnpId { get; set; }
}
