// <auto-generated />
// Table: config_equip_fashion_type (rows: 39)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipFashionType
{
    [JsonPropertyName("equip_type")]
    public long EquipType { get; set; }
    [JsonPropertyName("equippicture_type")]
    public long EquippictureType { get; set; }
    [JsonPropertyName("type_id")]
    public long TypeId { get; set; }
    [JsonPropertyName("type_name")]
    public string? TypeName { get; set; }
}
