// <auto-generated />
// Table: config_ship_damage_coefficient (rows: 42)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipDamageCoefficient
{
    [JsonPropertyName("air_coefficient")]
    public long AirCoefficient { get; set; }
    [JsonPropertyName("clamp")]
    public long Clamp { get; set; }
    [JsonPropertyName("environment_type")]
    public long EnvironmentType { get; set; }
    [JsonPropertyName("main_gun_coefficient")]
    public long MainGunCoefficient { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("sm_id")]
    public long SmId { get; set; }
    [JsonPropertyName("torpedo_coefficient")]
    public long TorpedoCoefficient { get; set; }
    [JsonPropertyName("vice_gun_coefficient")]
    public long ViceGunCoefficient { get; set; }
}
