// <auto-generated />
// Table: config_behavior_info (rows: 1146)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBehaviorInfo
{
    [JsonPropertyName("behavior_type")]
    public string? BehaviorType { get; set; }
    [JsonPropertyName("cn_text")]
    public string? CnText { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("effect_bind_id")]
    public string? EffectBindId { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("modle_name")]
    public string? ModleName { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
}
