// <auto-generated />
// Table: config_guildoffer_rankreward (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildofferRankreward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rankid")]
    public List<long>? Rankid { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
}
