// <auto-generated />
// Table: config_guildwar_reward (rows: 16)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildwarReward
{
    [JsonPropertyName("base_id")]
    public long BaseId { get; set; }
    [JsonPropertyName("battle_reward")]
    public long BattleReward { get; set; }
    [JsonPropertyName("damage_rate")]
    public List<long>? DamageRate { get; set; }
    [JsonPropertyName("damage_rate_reward")]
    public List<long>? DamageRateReward { get; set; }
    [JsonPropertyName("guild_reward")]
    public long GuildReward { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("kill_reward")]
    public long KillReward { get; set; }
    [JsonPropertyName("stage")]
    public long Stage { get; set; }
}
