// <auto-generated />
// Table: config_countenance_info_queue (rows: 134)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCountenanceInfoQueue
{
    [JsonPropertyName("countenance_name")]
    public string? CountenanceName { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("duration")]
    public double Duration { get; set; }
    [JsonPropertyName("group")]
    public string? Group { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("is_loop")]
    public long IsLoop { get; set; }
    [JsonPropertyName("queue")]
    public long Queue { get; set; }
}
