// <auto-generated />
// Table: config_home_page (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigHomePage
{
    [JsonPropertyName("function_id")]
    public List<string>? FunctionId { get; set; }
    [JsonPropertyName("hp_id")]
    public string? HpId { get; set; }
    [JsonPropertyName("zone_id")]
    public string? ZoneId { get; set; }
}
