// <auto-generated />
// Table: config_extract_mail (rows: 19)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExtractMail
{
    [JsonPropertyName("extract_id")]
    public long ExtractId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
