// <auto-generated />
// Table: config_help_text (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigHelpText
{
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("systemName")]
    public string? SystemName { get; set; }
}
