// <auto-generated />
// Table: config_air_search_spe (rows: 147)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAirSearchSpe
{
    [JsonPropertyName("birth_pos")]
    public string? BirthPos { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("patrol_pos_array")]
    public List<string>? PatrolPosArray { get; set; }
    [JsonPropertyName("radius")]
    public long Radius { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
}
