// <auto-generated />
// Table: config_minigame_victory_condition (rows: 33)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameVictoryCondition
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("parameter")]
    public List<long>? Parameter { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
