// <auto-generated />
// Table: config_team (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTeam
{
    [JsonPropertyName("chapterid")]
    public long Chapterid { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("team_type")]
    public long TeamType { get; set; }
}
