// <auto-generated />
// Table: config_expand_item (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExpandItem
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("expand_num")]
    public long ExpandNum { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("reward")]
    public List<List<long>>? Reward { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
