// <auto-generated />
// Table: config_fleet_auto (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFleetAuto
{
    [JsonPropertyName("avoid_torpedo_duration")]
    public long AvoidTorpedoDuration { get; set; }
    [JsonPropertyName("battle_speed")]
    public long BattleSpeed { get; set; }
    [JsonPropertyName("cd_range_switch")]
    public long CdRangeSwitch { get; set; }
    [JsonPropertyName("cd_skill")]
    public double CdSkill { get; set; }
    [JsonPropertyName("cd_skill_begin")]
    public double CdSkillBegin { get; set; }
    [JsonPropertyName("fa_id")]
    public long FaId { get; set; }
    [JsonPropertyName("search_auto_air_attack_a1")]
    public long SearchAutoAirAttackA1 { get; set; }
    [JsonPropertyName("search_auto_air_attack_a2")]
    public double SearchAutoAirAttackA2 { get; set; }
    [JsonPropertyName("search_auto_air_attack_a3")]
    public double SearchAutoAirAttackA3 { get; set; }
    [JsonPropertyName("search_auto_air_attack_b1")]
    public double SearchAutoAirAttackB1 { get; set; }
    [JsonPropertyName("search_auto_air_attack_b2")]
    public double SearchAutoAirAttackB2 { get; set; }
    [JsonPropertyName("search_auto_air_attack_b3")]
    public double SearchAutoAirAttackB3 { get; set; }
    [JsonPropertyName("search_auto_airattack_switch")]
    public long SearchAutoAirattackSwitch { get; set; }
    [JsonPropertyName("search_auto_explore_switch")]
    public long SearchAutoExploreSwitch { get; set; }
    [JsonPropertyName("search_fatigue_threshold")]
    public double SearchFatigueThreshold { get; set; }
    [JsonPropertyName("search_speed")]
    public long SearchSpeed { get; set; }
    [JsonPropertyName("weight_additionalSkill")]
    public long WeightAdditionalSkill { get; set; }
    [JsonPropertyName("weight_air_attack")]
    public long WeightAirAttack { get; set; }
    [JsonPropertyName("weight_dive")]
    public long WeightDive { get; set; }
    [JsonPropertyName("weight_main_gun")]
    public long WeightMainGun { get; set; }
    [JsonPropertyName("weight_range_far")]
    public long WeightRangeFar { get; set; }
    [JsonPropertyName("weight_range_middle")]
    public long WeightRangeMiddle { get; set; }
    [JsonPropertyName("weight_range_near")]
    public long WeightRangeNear { get; set; }
    [JsonPropertyName("weight_torpedo")]
    public long WeightTorpedo { get; set; }
    [JsonPropertyName("weight_vice_gun")]
    public long WeightViceGun { get; set; }
}
