// <auto-generated />
// Table: config_skill_trap_effect (rows: 166)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTrapEffect
{
    [JsonPropertyName("fill_prefab_path")]
    public string? FillPrefabPath { get; set; }
    [JsonPropertyName("hit_prefab_path")]
    public string? HitPrefabPath { get; set; }
    [JsonPropertyName("ste_id")]
    public long SteId { get; set; }
    [JsonPropertyName("trigger_prefab_path")]
    public string? TriggerPrefabPath { get; set; }
}
