// <auto-generated />
// Table: config_pskill_dict_buff_factor (rows: 1835)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictBuffFactor
{
    [JsonPropertyName("args")]
    public List<long>? Args { get; set; }
    [JsonPropertyName("buff_export_type")]
    public long BuffExportType { get; set; }
    [JsonPropertyName("buff_factor_type")]
    public long BuffFactorType { get; set; }
    [JsonPropertyName("buff_trigger_type")]
    public long BuffTriggerType { get; set; }
    [JsonPropertyName("callback_condition")]
    public List<long>? CallbackCondition { get; set; }
    [JsonPropertyName("callback_skill_condition")]
    public List<long>? CallbackSkillCondition { get; set; }
    [JsonPropertyName("could_sink")]
    public long CouldSink { get; set; }
    [JsonPropertyName("dot_begin_cycle")]
    public long DotBeginCycle { get; set; }
    [JsonPropertyName("dot_cycle")]
    public long DotCycle { get; set; }
    [JsonPropertyName("dot_max_num")]
    public long DotMaxNum { get; set; }
    [JsonPropertyName("dot_pskill_begin")]
    public long DotPskillBegin { get; set; }
    [JsonPropertyName("dot_pskill_dot")]
    public long DotPskillDot { get; set; }
    [JsonPropertyName("dot_pskill_end")]
    public long DotPskillEnd { get; set; }
    [JsonPropertyName("dot_pskill_kill")]
    public long DotPskillKill { get; set; }
    [JsonPropertyName("export_func")]
    public string? ExportFunc { get; set; }
    [JsonPropertyName("general_formula")]
    public long GeneralFormula { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("properties_snapshot")]
    public string? PropertiesSnapshot { get; set; }
    [JsonPropertyName("str_args")]
    public string? StrArgs { get; set; }
    [JsonPropertyName("target_prop_id")]
    public long TargetPropId { get; set; }
}
