// <auto-generated />
// Table: config_battlepass_param (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattlepassParam
{
    [JsonPropertyName("advance_price_1")]
    public List<long>? AdvancePrice1 { get; set; }
    [JsonPropertyName("advance_price_2")]
    public List<long>? AdvancePrice2 { get; set; }
    [JsonPropertyName("advance_reward_1")]
    public long AdvanceReward1 { get; set; }
    [JsonPropertyName("advance_reward_2")]
    public long AdvanceReward2 { get; set; }
    [JsonPropertyName("advance_reward_desc_1")]
    public List<object>? AdvanceRewardDesc1 { get; set; }
    [JsonPropertyName("advance_reward_desc_2")]
    public List<long>? AdvanceRewardDesc2 { get; set; }
    [JsonPropertyName("advance_reward_level_2")]
    public long AdvanceRewardLevel2 { get; set; }
    [JsonPropertyName("buy_level_price")]
    public List<long>? BuyLevelPrice { get; set; }
    [JsonPropertyName("free_icon")]
    public string? FreeIcon { get; set; }
    [JsonPropertyName("free_refresh_count")]
    public long FreeRefreshCount { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_recycling_id")]
    public long ItemRecyclingId { get; set; }
    [JsonPropertyName("pay_icon")]
    public string? PayIcon { get; set; }
    [JsonPropertyName("pay_refresh_count")]
    public long PayRefreshCount { get; set; }
    [JsonPropertyName("pay_refresh_price")]
    public List<long>? PayRefreshPrice { get; set; }
    [JsonPropertyName("recycle_mail_id")]
    public long RecycleMailId { get; set; }
    [JsonPropertyName("reward_mail_id")]
    public long RewardMailId { get; set; }
    [JsonPropertyName("shop_id")]
    public long ShopId { get; set; }
    [JsonPropertyName("weekly_task_num")]
    public long WeeklyTaskNum { get; set; }
}
