// <auto-generated />
// Table: config_copy (rows: 1401)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopy
{
    [JsonPropertyName("aerialaeconnaissance_cd")]
    public long AerialaeconnaissanceCd { get; set; }
    [JsonPropertyName("airattack_cd")]
    public long AirattackCd { get; set; }
    [JsonPropertyName("angleView")]
    public List<long>? AngleView { get; set; }
    [JsonPropertyName("battle_airattack_cd")]
    public long BattleAirattackCd { get; set; }
    [JsonPropertyName("battle_anim")]
    public long BattleAnim { get; set; }
    [JsonPropertyName("battle_time")]
    public long BattleTime { get; set; }
    [JsonPropertyName("blood_range_lower")]
    public long BloodRangeLower { get; set; }
    [JsonPropertyName("blood_range_upper")]
    public long BloodRangeUpper { get; set; }
    [JsonPropertyName("born_sp_id")]
    public List<string>? BornSpId { get; set; }
    [JsonPropertyName("close_nigh_battle")]
    public long CloseNighBattle { get; set; }
    [JsonPropertyName("copy_finish_type")]
    public long CopyFinishType { get; set; }
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("copy_scene_length")]
    public long CopySceneLength { get; set; }
    [JsonPropertyName("copy_scene_width")]
    public long CopySceneWidth { get; set; }
    [JsonPropertyName("copy_type")]
    public long CopyType { get; set; }
    [JsonPropertyName("cycle_day")]
    public long CycleDay { get; set; }
    [JsonPropertyName("cycle_night")]
    public long CycleNight { get; set; }
    [JsonPropertyName("dayNight_switch")]
    public long DayNightSwitch { get; set; }
    [JsonPropertyName("fleet_id")]
    public List<long>? FleetId { get; set; }
    [JsonPropertyName("fleet_supple")]
    public long FleetSupple { get; set; }
    [JsonPropertyName("initially_dayNight")]
    public string? InitiallyDayNight { get; set; }
    [JsonPropertyName("logic_trigger_array")]
    public List<long>? LogicTriggerArray { get; set; }
    [JsonPropertyName("map_fog_hide")]
    public long MapFogHide { get; set; }
    [JsonPropertyName("match_player_num")]
    public long MatchPlayerNum { get; set; }
    [JsonPropertyName("match_type")]
    public long MatchType { get; set; }
    [JsonPropertyName("mission_id")]
    public List<object>? MissionId { get; set; }
    [JsonPropertyName("r_id")]
    public long RId { get; set; }
    [JsonPropertyName("random_weight")]
    public long RandomWeight { get; set; }
    [JsonPropertyName("recommend")]
    public List<long>? Recommend { get; set; }
    [JsonPropertyName("report_type")]
    public List<object>? ReportType { get; set; }
    [JsonPropertyName("resource_id")]
    public List<long>? ResourceId { get; set; }
    [JsonPropertyName("running_fight_evaluation")]
    public long RunningFightEvaluation { get; set; }
    [JsonPropertyName("running_fight_level_id")]
    public long RunningFightLevelId { get; set; }
    [JsonPropertyName("running_fight_rate")]
    public long RunningFightRate { get; set; }
    [JsonPropertyName("scene_id")]
    public string? SceneId { get; set; }
    [JsonPropertyName("sea_area_name")]
    public string? SeaAreaName { get; set; }
    [JsonPropertyName("search_airattack_cd")]
    public long SearchAirattackCd { get; set; }
    [JsonPropertyName("search_bgm")]
    public string? SearchBgm { get; set; }
    [JsonPropertyName("series_fleet")]
    public List<long>? SeriesFleet { get; set; }
    [JsonPropertyName("team_attack_num")]
    public long TeamAttackNum { get; set; }
    [JsonPropertyName("type_parameter")]
    public List<object>? TypeParameter { get; set; }
    [JsonPropertyName("weather_group")]
    public List<object>? WeatherGroup { get; set; }
}
