// <auto-generated />
// Table: config_task_teaching_group (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskTeachingGroup
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("last_group_id")]
    public long LastGroupId { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("next_group_id")]
    public long NextGroupId { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("rewards_for_teacher")]
    public long RewardsForTeacher { get; set; }
    [JsonPropertyName("task_assess_id")]
    public List<long>? TaskAssessId { get; set; }
    [JsonPropertyName("task_daily_id")]
    public List<long>? TaskDailyId { get; set; }
    [JsonPropertyName("task_daily_limit")]
    public long TaskDailyLimit { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
}
