// <auto-generated />
// Table: config_shiplist_option (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShiplistOption
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("shiplist_sequence_id")]
    public List<long>? ShiplistSequenceId { get; set; }
}
