// <auto-generated />
// Table: config_minigame_item_template (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameItemTemplate
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
