// <auto-generated />
// Table: config_model_camera_config (rows: 245)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigModelCameraConfig
{
    [JsonPropertyName("animojiCameraRelativePos")]
    public List<double>? AnimojiCameraRelativePos { get; set; }
    [JsonPropertyName("animojiCameraRelativeRot")]
    public List<double>? AnimojiCameraRelativeRot { get; set; }
    [JsonPropertyName("animojiSize")]
    public double AnimojiSize { get; set; }
    [JsonPropertyName("detailsCameraRelativePos")]
    public List<double>? DetailsCameraRelativePos { get; set; }
    [JsonPropertyName("detailsCameraRelativeRot")]
    public List<long>? DetailsCameraRelativeRot { get; set; }
    [JsonPropertyName("detailsSize")]
    public double DetailsSize { get; set; }
    [JsonPropertyName("getCameraRelativePos")]
    public List<double>? GetCameraRelativePos { get; set; }
    [JsonPropertyName("getCameraRelativeRot")]
    public List<long>? GetCameraRelativeRot { get; set; }
    [JsonPropertyName("getSize")]
    public double GetSize { get; set; }
    [JsonPropertyName("model")]
    public string? Model { get; set; }
    [JsonPropertyName("schoolCameraRelativePos")]
    public List<double>? SchoolCameraRelativePos { get; set; }
    [JsonPropertyName("schoolCameraRelativeRot")]
    public List<long>? SchoolCameraRelativeRot { get; set; }
    [JsonPropertyName("schoolSize")]
    public double SchoolSize { get; set; }
    [JsonPropertyName("setCameraRelativePos")]
    public List<double>? SetCameraRelativePos { get; set; }
    [JsonPropertyName("setCameraRelativeRot")]
    public List<long>? SetCameraRelativeRot { get; set; }
    [JsonPropertyName("setSize")]
    public double SetSize { get; set; }
}
