// <auto-generated />
// Table: config_daily_register (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDailyRegister
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rewards")]
    public List<long>? Rewards { get; set; }
}
