// <auto-generated />
// Table: config_home_activity_enter (rows: 36)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigHomeActivityEnter
{
    [JsonPropertyName("activity_copyenter")]
    public long ActivityCopyenter { get; set; }
    [JsonPropertyName("activity_icon")]
    public string? ActivityIcon { get; set; }
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("activity_name")]
    public string? ActivityName { get; set; }
    [JsonPropertyName("chapter_type")]
    public List<long>? ChapterType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("jump_function")]
    public long JumpFunction { get; set; }
    [JsonPropertyName("jump_para")]
    public List<long>? JumpPara { get; set; }
    [JsonPropertyName("reddot_id")]
    public List<long>? ReddotId { get; set; }
    [JsonPropertyName("reddot_param")]
    public List<List<long>>? ReddotParam { get; set; }
    [JsonPropertyName("special_enter")]
    public long SpecialEnter { get; set; }
}
