// <auto-generated />
// Table: config_ship_enemy (rows: 10717)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipEnemy
{
    [JsonPropertyName("angle_speed")]
    public long AngleSpeed { get; set; }
    [JsonPropertyName("anti_crit")]
    public long AntiCrit { get; set; }
    [JsonPropertyName("attack")]
    public long Attack { get; set; }
    [JsonPropertyName("backup_plane_count")]
    public long BackupPlaneCount { get; set; }
    [JsonPropertyName("basi_id")]
    public long BasiId { get; set; }
    [JsonPropertyName("battle_angle_speed")]
    public long BattleAngleSpeed { get; set; }
    [JsonPropertyName("carry_plane_count")]
    public long CarryPlaneCount { get; set; }
    [JsonPropertyName("chase_speed")]
    public long ChaseSpeed { get; set; }
    [JsonPropertyName("conversion_blood_loss")]
    public long ConversionBloodLoss { get; set; }
    [JsonPropertyName("crit")]
    public long Crit { get; set; }
    [JsonPropertyName("damage_coefficient_of_special_air")]
    public long DamageCoefficientOfSpecialAir { get; set; }
    [JsonPropertyName("damage_coefficient_of_special_maingun")]
    public long DamageCoefficientOfSpecialMaingun { get; set; }
    [JsonPropertyName("damage_coefficient_of_special_torpedo")]
    public long DamageCoefficientOfSpecialTorpedo { get; set; }
    [JsonPropertyName("defense")]
    public long Defense { get; set; }
    [JsonPropertyName("dodge")]
    public long Dodge { get; set; }
    [JsonPropertyName("fail_score_percent")]
    public List<object>? FailScorePercent { get; set; }
    [JsonPropertyName("fate")]
    public long Fate { get; set; }
    [JsonPropertyName("hit")]
    public long Hit { get; set; }
    [JsonPropertyName("hp")]
    public long Hp { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("isonlyspecial")]
    public long Isonlyspecial { get; set; }
    [JsonPropertyName("large_blood_loss")]
    public long LargeBloodLoss { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("lighting_shells_available")]
    public long LightingShellsAvailable { get; set; }
    [JsonPropertyName("main_gun_available")]
    public long MainGunAvailable { get; set; }
    [JsonPropertyName("main_gun_cd")]
    public long MainGunCd { get; set; }
    [JsonPropertyName("main_gun_range")]
    public long MainGunRange { get; set; }
    [JsonPropertyName("main_gun_target_num")]
    public long MainGunTargetNum { get; set; }
    [JsonPropertyName("medium_blood_loss")]
    public long MediumBloodLoss { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("number_of_special_air_attacks")]
    public long NumberOfSpecialAirAttacks { get; set; }
    [JsonPropertyName("number_of_special_maingun_attacks")]
    public long NumberOfSpecialMaingunAttacks { get; set; }
    [JsonPropertyName("number_of_special_torpedo_attacks")]
    public long NumberOfSpecialTorpedoAttacks { get; set; }
    [JsonPropertyName("patrol_speed")]
    public long PatrolSpeed { get; set; }
    [JsonPropertyName("plane_bomb")]
    public long PlaneBomb { get; set; }
    [JsonPropertyName("plane_health")]
    public long PlaneHealth { get; set; }
    [JsonPropertyName("plane_target_num")]
    public long PlaneTargetNum { get; set; }
    [JsonPropertyName("plane_to_air")]
    public long PlaneToAir { get; set; }
    [JsonPropertyName("plane_torpedo")]
    public long PlaneTorpedo { get; set; }
    [JsonPropertyName("projectiles")]
    public List<long>? Projectiles { get; set; }
    [JsonPropertyName("projectiles_cd")]
    public string? ProjectilesCd { get; set; }
    [JsonPropertyName("pskill_id_array")]
    public List<long>? PskillIdArray { get; set; }
    [JsonPropertyName("safe_score")]
    public List<List<long>>? SafeScore { get; set; }
    [JsonPropertyName("second_gun_available")]
    public long SecondGunAvailable { get; set; }
    [JsonPropertyName("ship_air_control")]
    public long ShipAirControl { get; set; }
    [JsonPropertyName("ship_bomb_attack")]
    public long ShipBombAttack { get; set; }
    [JsonPropertyName("ship_country")]
    public long ShipCountry { get; set; }
    [JsonPropertyName("ship_info_id")]
    public long ShipInfoId { get; set; }
    [JsonPropertyName("ship_torpedo_attack")]
    public long ShipTorpedoAttack { get; set; }
    [JsonPropertyName("sink_blood_loss")]
    public long SinkBloodLoss { get; set; }
    [JsonPropertyName("small_blood_loss")]
    public long SmallBloodLoss { get; set; }
    [JsonPropertyName("special_air_range")]
    public long SpecialAirRange { get; set; }
    [JsonPropertyName("special_maingun_range")]
    public long SpecialMaingunRange { get; set; }
    [JsonPropertyName("special_projectiles")]
    public List<long>? SpecialProjectiles { get; set; }
    [JsonPropertyName("special_projectiles_count")]
    public List<long>? SpecialProjectilesCount { get; set; }
    [JsonPropertyName("special_projectiles_times")]
    public List<long>? SpecialProjectilesTimes { get; set; }
    [JsonPropertyName("special_torpedo_range")]
    public long SpecialTorpedoRange { get; set; }
    [JsonPropertyName("specialship_id")]
    public List<object>? SpecialshipId { get; set; }
    [JsonPropertyName("specialship_type")]
    public List<object>? SpecialshipType { get; set; }
    [JsonPropertyName("specialstrategy")]
    public List<object>? Specialstrategy { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("st_id")]
    public long StId { get; set; }
    [JsonPropertyName("to_air_attack")]
    public long ToAirAttack { get; set; }
    [JsonPropertyName("to_torpedo_attack")]
    public long ToTorpedoAttack { get; set; }
    [JsonPropertyName("torpedo")]
    public long Torpedo { get; set; }
    [JsonPropertyName("torpedo_available")]
    public long TorpedoAvailable { get; set; }
    [JsonPropertyName("torpedo_defense")]
    public long TorpedoDefense { get; set; }
    [JsonPropertyName("torpedo_num")]
    public long TorpedoNum { get; set; }
    [JsonPropertyName("torpedo_target_num")]
    public long TorpedoTargetNum { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("view_range")]
    public long ViewRange { get; set; }
    [JsonPropertyName("voyage")]
    public long Voyage { get; set; }
}
