// <auto-generated />
// Table: config_buildingtype (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildingtype
{
    [JsonPropertyName("buildnumber")]
    public long Buildnumber { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
