// <auto-generated />
// Table: config_pskill_sp_talent (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillSpTalent
{
    [JsonPropertyName("condition_type")]
    public long ConditionType { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("parameter")]
    public List<long>? Parameter { get; set; }
    [JsonPropertyName("talent_id")]
    public long TalentId { get; set; }
    [JsonPropertyName("val_add")]
    public long ValAdd { get; set; }
    [JsonPropertyName("val_init")]
    public long ValInit { get; set; }
}
