// <auto-generated />
// Table: config_ship_perform_limit (rows: 11)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipPerformLimit
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("ship_type")]
    public string? ShipType { get; set; }
    [JsonPropertyName("value1_max")]
    public long Value1Max { get; set; }
    [JsonPropertyName("value1_max_evaluation")]
    public long Value1MaxEvaluation { get; set; }
    [JsonPropertyName("value1_min_evaluation")]
    public long Value1MinEvaluation { get; set; }
    [JsonPropertyName("value2_max")]
    public long Value2Max { get; set; }
    [JsonPropertyName("value2_max_evaluation")]
    public long Value2MaxEvaluation { get; set; }
    [JsonPropertyName("value2_min_evaluation")]
    public long Value2MinEvaluation { get; set; }
    [JsonPropertyName("value3_max")]
    public long Value3Max { get; set; }
    [JsonPropertyName("value3_max_evaluation")]
    public long Value3MaxEvaluation { get; set; }
    [JsonPropertyName("value3_min_evaluation")]
    public long Value3MinEvaluation { get; set; }
    [JsonPropertyName("value4_max")]
    public long Value4Max { get; set; }
    [JsonPropertyName("value4_max_evaluation")]
    public long Value4MaxEvaluation { get; set; }
    [JsonPropertyName("value4_min_evaluation")]
    public long Value4MinEvaluation { get; set; }
    [JsonPropertyName("value5_max")]
    public long Value5Max { get; set; }
    [JsonPropertyName("value5_max_evaluation")]
    public long Value5MaxEvaluation { get; set; }
    [JsonPropertyName("value5_min_evaluation")]
    public long Value5MinEvaluation { get; set; }
    [JsonPropertyName("value6_max")]
    public long Value6Max { get; set; }
    [JsonPropertyName("value6_max_evaluation")]
    public long Value6MaxEvaluation { get; set; }
    [JsonPropertyName("value6_min_evaluation")]
    public long Value6MinEvaluation { get; set; }
}
