// <auto-generated />
// Table: config_battle_logic_trigger (rows: 63)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleLogicTrigger
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("trigger_condition")]
    public long TriggerCondition { get; set; }
    [JsonPropertyName("trigger_condition_param")]
    public string? TriggerConditionParam { get; set; }
    [JsonPropertyName("trigger_limit_num")]
    public long TriggerLimitNum { get; set; }
    [JsonPropertyName("trigger_result")]
    public List<long>? TriggerResult { get; set; }
    [JsonPropertyName("trigger_time")]
    public long TriggerTime { get; set; }
    [JsonPropertyName("trigger_tip")]
    public long TriggerTip { get; set; }
}
