// <auto-generated />
// Table: config_skill_trigger_range (rows: 0)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTriggerRange
{
}
