// <auto-generated />
// Table: config_pskill_dict_buff_trans (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictBuffTrans
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("last_time_mode")]
    public long LastTimeMode { get; set; }
    [JsonPropertyName("trans_count")]
    public long TransCount { get; set; }
    [JsonPropertyName("trans_target")]
    public long TransTarget { get; set; }
    [JsonPropertyName("trans_time")]
    public long TransTime { get; set; }
}
