// <auto-generated />
// Table: config_home_scene_envir (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigHomeSceneEnvir
{
    [JsonPropertyName("big_activity_envir_bgm")]
    public string? BigActivityEnvirBgm { get; set; }
    [JsonPropertyName("big_activity_envir_bgm_1101")]
    public string? BigActivityEnvirBgm1101 { get; set; }
    [JsonPropertyName("big_activity_envir_bgm_1512")]
    public string? BigActivityEnvirBgm1512 { get; set; }
    [JsonPropertyName("big_activity_envir_bgm_6")]
    public string? BigActivityEnvirBgm6 { get; set; }
    [JsonPropertyName("big_activity_envir_bgm_7")]
    public string? BigActivityEnvirBgm7 { get; set; }
    [JsonPropertyName("big_activity_envir_bgm_ryza")]
    public string? BigActivityEnvirBgmRyza { get; set; }
    [JsonPropertyName("envir_bgm")]
    public string? EnvirBgm { get; set; }
    [JsonPropertyName("envir_resource")]
    public string? EnvirResource { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("intaction_item_id")]
    public List<long>? IntactionItemId { get; set; }
    [JsonPropertyName("restrictive_condition_parameter")]
    public List<object>? RestrictiveConditionParameter { get; set; }
    [JsonPropertyName("restrictive_condition_type")]
    public List<object>? RestrictiveConditionType { get; set; }
    [JsonPropertyName("time_frame")]
    public List<long>? TimeFrame { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
