// <auto-generated />
// Table: config_battle_ai_fleet_escape (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiFleetEscape
{
    [JsonPropertyName("baf_id")]
    public long BafId { get; set; }
    [JsonPropertyName("bafe_id")]
    public long BafeId { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("escape_target")]
    public string? EscapeTarget { get; set; }
    [JsonPropertyName("escape_type")]
    public long EscapeType { get; set; }
    [JsonPropertyName("escape_weight")]
    public long EscapeWeight { get; set; }
}
