// <auto-generated />
// Table: config_copy_display (rows: 2032)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopyDisplay
{
    [JsonPropertyName("activity_item")]
    public List<long>? ActivityItem { get; set; }
    [JsonPropertyName("activity_period")]
    public long ActivityPeriod { get; set; }
    [JsonPropertyName("activity_period_area")]
    public List<long>? ActivityPeriodArea { get; set; }
    [JsonPropertyName("activity_plot_bg")]
    public string? ActivityPlotBg { get; set; }
    [JsonPropertyName("activity_point_get")]
    public long ActivityPointGet { get; set; }
    [JsonPropertyName("after_clear_supple_num")]
    public List<long>? AfterClearSuppleNum { get; set; }
    [JsonPropertyName("assist_fleet")]
    public List<long>? AssistFleet { get; set; }
    [JsonPropertyName("assist_fleet_lock")]
    public long AssistFleetLock { get; set; }
    [JsonPropertyName("assist_fleet_num")]
    public long AssistFleetNum { get; set; }
    [JsonPropertyName("attached_fleet")]
    public long AttachedFleet { get; set; }
    [JsonPropertyName("auto_continuation")]
    public long AutoContinuation { get; set; }
    [JsonPropertyName("autobattle_gamelimit")]
    public List<object>? AutobattleGamelimit { get; set; }
    [JsonPropertyName("autobattle_isshow")]
    public long AutobattleIsshow { get; set; }
    [JsonPropertyName("autobattle_open")]
    public long AutobattleOpen { get; set; }
    [JsonPropertyName("autobattle_opendesc")]
    public long AutobattleOpendesc { get; set; }
    [JsonPropertyName("autobattle_time")]
    public long AutobattleTime { get; set; }
    [JsonPropertyName("ban_autobattle")]
    public long BanAutobattle { get; set; }
    [JsonPropertyName("battle_boss_hp_uri")]
    public string? BattleBossHpUri { get; set; }
    [JsonPropertyName("battle_time")]
    public long BattleTime { get; set; }
    [JsonPropertyName("before_copy_id_list")]
    public List<long>? BeforeCopyIdList { get; set; }
    [JsonPropertyName("big_activity_copy_display_id")]
    public long BigActivityCopyDisplayId { get; set; }
    [JsonPropertyName("boss_net_image")]
    public string? BossNetImage { get; set; }
    [JsonPropertyName("branch_copy")]
    public List<long>? BranchCopy { get; set; }
    [JsonPropertyName("branch_id")]
    public List<long>? BranchId { get; set; }
    [JsonPropertyName("buff_max_times")]
    public long BuffMaxTimes { get; set; }
    [JsonPropertyName("checkpoint_instructions")]
    public long CheckpointInstructions { get; set; }
    [JsonPropertyName("choice_boss")]
    public string? ChoiceBoss { get; set; }
    [JsonPropertyName("clear_forbbiden_id")]
    public List<long>? ClearForbbidenId { get; set; }
    [JsonPropertyName("condition")]
    public List<object>? Condition { get; set; }
    [JsonPropertyName("coordinate")]
    public List<double>? Coordinate { get; set; }
    [JsonPropertyName("copy_activity_value")]
    public List<List<long>>? CopyActivityValue { get; set; }
    [JsonPropertyName("copy_demo_id")]
    public long CopyDemoId { get; set; }
    [JsonPropertyName("copy_display_type")]
    public long CopyDisplayType { get; set; }
    [JsonPropertyName("copy_guarantee")]
    public List<List<long>>? CopyGuarantee { get; set; }
    [JsonPropertyName("copy_index")]
    public string? CopyIndex { get; set; }
    [JsonPropertyName("copy_must_drop_num")]
    public long CopyMustDropNum { get; set; }
    [JsonPropertyName("copy_must_drop_reward")]
    public long CopyMustDropReward { get; set; }
    [JsonPropertyName("copy_progress")]
    public List<long>? CopyProgress { get; set; }
    [JsonPropertyName("copy_thumbnail_after")]
    public string? CopyThumbnailAfter { get; set; }
    [JsonPropertyName("copy_thumbnail_before")]
    public string? CopyThumbnailBefore { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("details_boss")]
    public string? DetailsBoss { get; set; }
    [JsonPropertyName("download_ids")]
    public List<object>? DownloadIds { get; set; }
    [JsonPropertyName("drop_info_id")]
    public List<long>? DropInfoId { get; set; }
    [JsonPropertyName("drop_period")]
    public long DropPeriod { get; set; }
    [JsonPropertyName("drop_sr_copydisplayid")]
    public long DropSrCopydisplayid { get; set; }
    [JsonPropertyName("drop_sr_shipid")]
    public long DropSrShipid { get; set; }
    [JsonPropertyName("drop_ssr_copydisplayid")]
    public long DropSsrCopydisplayid { get; set; }
    [JsonPropertyName("drop_ssr_shipid")]
    public long DropSsrShipid { get; set; }
    [JsonPropertyName("evaluation_instructions")]
    public string? EvaluationInstructions { get; set; }
    [JsonPropertyName("exercises_point")]
    public long ExercisesPoint { get; set; }
    [JsonPropertyName("fail_cost")]
    public long FailCost { get; set; }
    [JsonPropertyName("finishmission_reward")]
    public List<object>? FinishmissionReward { get; set; }
    [JsonPropertyName("first_reward")]
    public List<long>? FirstReward { get; set; }
    [JsonPropertyName("full_name")]
    public string? FullName { get; set; }
    [JsonPropertyName("gotowar_num_mub")]
    public long GotowarNumMub { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_boss_copy")]
    public long IsBossCopy { get; set; }
    [JsonPropertyName("is_influence_by_evaluate")]
    public long IsInfluenceByEvaluate { get; set; }
    [JsonPropertyName("is_match")]
    public long IsMatch { get; set; }
    [JsonPropertyName("is_open_modecheck")]
    public long IsOpenModecheck { get; set; }
    [JsonPropertyName("level_limit")]
    public long LevelLimit { get; set; }
    [JsonPropertyName("link_display")]
    public List<object>? LinkDisplay { get; set; }
    [JsonPropertyName("max_fleet")]
    public long MaxFleet { get; set; }
    [JsonPropertyName("minigame_id")]
    public long MinigameId { get; set; }
    [JsonPropertyName("mission_display")]
    public long MissionDisplay { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("next_copy_id_list")]
    public List<long>? NextCopyIdList { get; set; }
    [JsonPropertyName("norecord_power")]
    public long NorecordPower { get; set; }
    [JsonPropertyName("nvn_ship_exp_up")]
    public List<List<long>>? NvnShipExpUp { get; set; }
    [JsonPropertyName("once_seasafe")]
    public long OnceSeasafe { get; set; }
    [JsonPropertyName("period_drop")]
    public long PeriodDrop { get; set; }
    [JsonPropertyName("plot_bg_lock")]
    public string? PlotBgLock { get; set; }
    [JsonPropertyName("pskill_id")]
    public long PskillId { get; set; }
    [JsonPropertyName("pvept_cost")]
    public long PveptCost { get; set; }
    [JsonPropertyName("random_factor_sets")]
    public List<long>? RandomFactorSets { get; set; }
    [JsonPropertyName("rank_drop")]
    public long RankDrop { get; set; }
    [JsonPropertyName("recommend")]
    public List<long>? Recommend { get; set; }
    [JsonPropertyName("recommend_info")]
    public List<long>? RecommendInfo { get; set; }
    [JsonPropertyName("recommend_tactics")]
    public long RecommendTactics { get; set; }
    [JsonPropertyName("recommended_attack")]
    public long RecommendedAttack { get; set; }
    [JsonPropertyName("recommended_battle_power")]
    public long RecommendedBattlePower { get; set; }
    [JsonPropertyName("recommended_speed")]
    public long RecommendedSpeed { get; set; }
    [JsonPropertyName("revive_icon_after")]
    public string? ReviveIconAfter { get; set; }
    [JsonPropertyName("revive_icon_before")]
    public string? ReviveIconBefore { get; set; }
    [JsonPropertyName("safe_area_hidden")]
    public long SafeAreaHidden { get; set; }
    [JsonPropertyName("save_mode")]
    public long SaveMode { get; set; }
    [JsonPropertyName("script_function_name")]
    public string? ScriptFunctionName { get; set; }
    [JsonPropertyName("script_params")]
    public List<object>? ScriptParams { get; set; }
    [JsonPropertyName("sea_area_unlock")]
    public long SeaAreaUnlock { get; set; }
    [JsonPropertyName("search_3d")]
    public long Search3d { get; set; }
    [JsonPropertyName("search_boss_hp_uri")]
    public string? SearchBossHpUri { get; set; }
    [JsonPropertyName("ship_limit")]
    public List<long>? ShipLimit { get; set; }
    [JsonPropertyName("shiplimit_desc")]
    public object? ShiplimitDesc { get; set; }
    [JsonPropertyName("special_buff")]
    public List<long>? SpecialBuff { get; set; }
    [JsonPropertyName("special_type")]
    public long SpecialType { get; set; }
    [JsonPropertyName("split_team")]
    public List<List<long>>? SplitTeam { get; set; }
    [JsonPropertyName("sport_type")]
    public long SportType { get; set; }
    [JsonPropertyName("stageid")]
    public long Stageid { get; set; }
    [JsonPropertyName("star_require")]
    public List<long>? StarRequire { get; set; }
    [JsonPropertyName("star_require_unlock")]
    public long StarRequireUnlock { get; set; }
    [JsonPropertyName("str_index")]
    public string? StrIndex { get; set; }
    [JsonPropertyName("supple_cost_argu")]
    public long SuppleCostArgu { get; set; }
    [JsonPropertyName("supply_basic_cost")]
    public long SupplyBasicCost { get; set; }
    [JsonPropertyName("support_fleet_average_level_min")]
    public long SupportFleetAverageLevelMin { get; set; }
    [JsonPropertyName("support_fleet_battle_ratio")]
    public long SupportFleetBattleRatio { get; set; }
    [JsonPropertyName("support_fleet_count_max")]
    public long SupportFleetCountMax { get; set; }
    [JsonPropertyName("support_fleet_target_and_effect")]
    public List<List<long>>? SupportFleetTargetAndEffect { get; set; }
    [JsonPropertyName("support_fleet_unlock_id")]
    public long SupportFleetUnlockId { get; set; }
    [JsonPropertyName("three_star_reward")]
    public List<object>? ThreeStarReward { get; set; }
    [JsonPropertyName("thumbnail")]
    public string? Thumbnail { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("total_supple_num")]
    public List<long>? TotalSuppleNum { get; set; }
    [JsonPropertyName("tower_prop_id_num")]
    public List<List<double>>? TowerPropIdNum { get; set; }
    [JsonPropertyName("training_open_limit")]
    public long TrainingOpenLimit { get; set; }
    [JsonPropertyName("training_strategy")]
    public List<List<long>>? TrainingStrategy { get; set; }
    [JsonPropertyName("training_teacher_modle")]
    public long TrainingTeacherModle { get; set; }
    [JsonPropertyName("training_tips")]
    public string? TrainingTips { get; set; }
    [JsonPropertyName("true_assist_fleet")]
    public List<long>? TrueAssistFleet { get; set; }
    [JsonPropertyName("unlock_clear_request")]
    public List<long>? UnlockClearRequest { get; set; }
    [JsonPropertyName("unlock_next_chapter")]
    public long UnlockNextChapter { get; set; }
    [JsonPropertyName("upload_ids")]
    public List<object>? UploadIds { get; set; }
    [JsonPropertyName("use_assist_mode")]
    public long UseAssistMode { get; set; }
    [JsonPropertyName("warning_power")]
    public long WarningPower { get; set; }
}
