// <auto-generated />
// Table: config_task_magazine (rows: 343)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskMagazine
{
    [JsonPropertyName("accumulate")]
    public List<object>? Accumulate { get; set; }
    [JsonPropertyName("auto_send")]
    public long AutoSend { get; set; }
    [JsonPropertyName("count_type")]
    public long CountType { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("desc_language")]
    public long DescLanguage { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("go_up_to_parm")]
    public List<object>? GoUpToParm { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("last_task")]
    public long LastTask { get; set; }
    [JsonPropertyName("last_task_client")]
    public long LastTaskClient { get; set; }
    [JsonPropertyName("last_task_list")]
    public List<long>? LastTaskList { get; set; }
    [JsonPropertyName("magazine_id")]
    public long MagazineId { get; set; }
    [JsonPropertyName("magazine_page_id")]
    public long MagazinePageId { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("period_list")]
    public List<object>? PeriodList { get; set; }
    [JsonPropertyName("period_list_area")]
    public List<object>? PeriodListArea { get; set; }
    [JsonPropertyName("refresh_id")]
    public long RefreshId { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("show_reward_num")]
    public long ShowRewardNum { get; set; }
}
