// <auto-generated />
// Table: config_skill_be_hit (rows: 1728)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillBeHit
{
    [JsonPropertyName("bac_use_state")]
    public string? BacUseState { get; set; }
    [JsonPropertyName("bac_use_state_bk")]
    public string? BacUseStateBk { get; set; }
    [JsonPropertyName("behit_bind_type")]
    public List<long>? BehitBindType { get; set; }
    [JsonPropertyName("behit_duration")]
    public double BehitDuration { get; set; }
    [JsonPropertyName("behit_effect_bind_id")]
    public List<string>? BehitEffectBindId { get; set; }
    [JsonPropertyName("behit_effect_id")]
    public string? BehitEffectId { get; set; }
    [JsonPropertyName("behit_hp_state")]
    public long BehitHpState { get; set; }
    [JsonPropertyName("camera_info_group")]
    public string? CameraInfoGroup { get; set; }
    [JsonPropertyName("camera_info_group_bk")]
    public string? CameraInfoGroupBk { get; set; }
    [JsonPropertyName("cutin_right_camera_info_group")]
    public string? CutinRightCameraInfoGroup { get; set; }
    [JsonPropertyName("damage_type")]
    public long DamageType { get; set; }
    [JsonPropertyName("hdr_duration")]
    public double HdrDuration { get; set; }
    [JsonPropertyName("poke_duration")]
    public double PokeDuration { get; set; }
    [JsonPropertyName("poke_start_time")]
    public double PokeStartTime { get; set; }
    [JsonPropertyName("poyi_shake_duration")]
    public double PoyiShakeDuration { get; set; }
    [JsonPropertyName("poyi_shake_speed")]
    public double PoyiShakeSpeed { get; set; }
    [JsonPropertyName("poyi_shake_strenth")]
    public double PoyiShakeStrenth { get; set; }
    [JsonPropertyName("poyi_start_shake_time")]
    public double PoyiStartShakeTime { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("screen_fxpro_duration")]
    public double ScreenFxproDuration { get; set; }
    [JsonPropertyName("screen_fxpro_start_tiem")]
    public double ScreenFxproStartTiem { get; set; }
    [JsonPropertyName("ship_id")]
    public string? ShipId { get; set; }
    [JsonPropertyName("show_damage_switch")]
    public long ShowDamageSwitch { get; set; }
    [JsonPropertyName("show_damage_time")]
    public double ShowDamageTime { get; set; }
    [JsonPropertyName("ui_idle_show_camera_path")]
    public string? UiIdleShowCameraPath { get; set; }
    [JsonPropertyName("ui_show_camera_path")]
    public string? UiShowCameraPath { get; set; }
}
