// <auto-generated />
// Table: config_pet_main (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPetMain
{
    [JsonPropertyName("defult_prop")]
    public List<List<long>>? DefultProp { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("equip_id")]
    public long EquipId { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("nomarl_show_id")]
    public string? NomarlShowId { get; set; }
    [JsonPropertyName("position")]
    public List<long>? Position { get; set; }
    [JsonPropertyName("pskill_group_nomarl")]
    public List<long>? PskillGroupNomarl { get; set; }
    [JsonPropertyName("pskill_wakeup")]
    public List<long>? PskillWakeup { get; set; }
    [JsonPropertyName("scale")]
    public long Scale { get; set; }
    [JsonPropertyName("usestate_loop")]
    public string? UsestateLoop { get; set; }
    [JsonPropertyName("usestate_restore")]
    public string? UsestateRestore { get; set; }
    [JsonPropertyName("usestate_settlement")]
    public string? UsestateSettlement { get; set; }
    [JsonPropertyName("usestate_wakeup")]
    public string? UsestateWakeup { get; set; }
    [JsonPropertyName("wakeup_show_id")]
    public string? WakeupShowId { get; set; }
}
