// <auto-generated />
// Table: config_affection_favor (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAffectionFavor
{
    [JsonPropertyName("affection_adddescribe")]
    public string? AffectionAdddescribe { get; set; }
    [JsonPropertyName("affection_cost")]
    public long AffectionCost { get; set; }
    [JsonPropertyName("affection_describe")]
    public string? AffectionDescribe { get; set; }
    [JsonPropertyName("affection_icon")]
    public string? AffectionIcon { get; set; }
    [JsonPropertyName("affection_id")]
    public long AffectionId { get; set; }
    [JsonPropertyName("affection_marry")]
    public long AffectionMarry { get; set; }
    [JsonPropertyName("affection_max")]
    public long AffectionMax { get; set; }
    [JsonPropertyName("affection_min")]
    public long AffectionMin { get; set; }
    [JsonPropertyName("affection_value_effect")]
    public List<long>? AffectionValueEffect { get; set; }
    [JsonPropertyName("value_effect_power")]
    public List<long>? ValueEffectPower { get; set; }
}
