// <auto-generated />
// Table: config_shiptalenttype (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShiptalenttype
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("shiptypelist")]
    public List<long>? Shiptypelist { get; set; }
}
