// <auto-generated />
// Table: config_goods_battle (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGoodsBattle
{
    [JsonPropertyName("buff_id")]
    public List<long>? BuffId { get; set; }
    [JsonPropertyName("buff_name")]
    public string? BuffName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("type_icon")]
    public string? TypeIcon { get; set; }
}
