// <auto-generated />
// Table: config_pskill_dict_select_target (rows: 120)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictSelectTarget
{
    [JsonPropertyName("base_num")]
    public long BaseNum { get; set; }
    [JsonPropertyName("condition_items")]
    public List<long>? ConditionItems { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_fleet")]
    public long IsFleet { get; set; }
    [JsonPropertyName("prop_num")]
    public long PropNum { get; set; }
    [JsonPropertyName("random_num")]
    public long RandomNum { get; set; }
    [JsonPropertyName("select_need_valid")]
    public long SelectNeedValid { get; set; }
    [JsonPropertyName("select_only_one")]
    public long SelectOnlyOne { get; set; }
    [JsonPropertyName("select_type")]
    public long SelectType { get; set; }
    [JsonPropertyName("self_filter")]
    public long SelfFilter { get; set; }
}
