// <auto-generated />
// Table: config_copy_type_map (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopyTypeMap2
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("value")]
    public long Value { get; set; }
}
