// <auto-generated />
// Table: config_skill_release (rows: 1346)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillRelease
{
    [JsonPropertyName("release_group_id")]
    public string? ReleaseGroupId { get; set; }
    [JsonPropertyName("release_project")]
    public string? ReleaseProject { get; set; }
    [JsonPropertyName("release_time")]
    public double ReleaseTime { get; set; }
    [JsonPropertyName("release_type")]
    public long ReleaseType { get; set; }
    [JsonPropertyName("select_target_type")]
    public long SelectTargetType { get; set; }
    [JsonPropertyName("sr_id")]
    public string? SrId { get; set; }
}
