// <auto-generated />
// Table: config_skill_torpedo (rows: 19)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTorpedo
{
    [JsonPropertyName("angle")]
    public long Angle { get; set; }
    [JsonPropertyName("persuit_time")]
    public long PersuitTime { get; set; }
    [JsonPropertyName("radius")]
    public double Radius { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("stg_id")]
    public long StgId { get; set; }
    [JsonPropertyName("torpedo_range")]
    public long TorpedoRange { get; set; }
    [JsonPropertyName("trap_count")]
    public long TrapCount { get; set; }
}
