// <auto-generated />
// Table: config_air_spe_link_fleet (rows: 115)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAirSpeLinkFleet
{
    [JsonPropertyName("air_attack_spe_data")]
    public long AirAttackSpeData { get; set; }
    [JsonPropertyName("air_search_spe_array")]
    public List<long>? AirSearchSpeArray { get; set; }
    [JsonPropertyName("fleet_id")]
    public long FleetId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
