// <auto-generated />
// Table: config_interaction_item (rows: 129)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigInteractionItem
{
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("effect_item_name")]
    public string? EffectItemName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("interaction_event")]
    public long InteractionEvent { get; set; }
    [JsonPropertyName("interaction_item_attach")]
    public List<long>? InteractionItemAttach { get; set; }
    [JsonPropertyName("interaction_item_bag")]
    public long InteractionItemBag { get; set; }
    [JsonPropertyName("interaction_item_desc")]
    public string? InteractionItemDesc { get; set; }
    [JsonPropertyName("interaction_item_detail")]
    public string? InteractionItemDetail { get; set; }
    [JsonPropertyName("interaction_item_name")]
    public string? InteractionItemName { get; set; }
    [JsonPropertyName("interaction_item_pic")]
    public string? InteractionItemPic { get; set; }
    [JsonPropertyName("interaction_item_type")]
    public long InteractionItemType { get; set; }
    [JsonPropertyName("item_display_period")]
    public long ItemDisplayPeriod { get; set; }
    [JsonPropertyName("item_info_id")]
    public long ItemInfoId { get; set; }
    [JsonPropertyName("item_location_coordinate")]
    public List<List<double>>? ItemLocationCoordinate { get; set; }
    [JsonPropertyName("item_name")]
    public string? ItemName { get; set; }
    [JsonPropertyName("item_name_dawn")]
    public string? ItemNameDawn { get; set; }
    [JsonPropertyName("item_name_night")]
    public string? ItemNameNight { get; set; }
    [JsonPropertyName("item_show_next_item")]
    public long ItemShowNextItem { get; set; }
    [JsonPropertyName("item_show_next_item_type")]
    public long ItemShowNextItemType { get; set; }
    [JsonPropertyName("item_show_previous_item")]
    public long ItemShowPreviousItem { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
}
