// <auto-generated />
// Table: config_flagsystem (rows: 160)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFlagsystem
{
    [JsonPropertyName("function_open")]
    public List<long>? FunctionOpen { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("param")]
    public List<long>? Param { get; set; }
}
