// <auto-generated />
// Table: config_skill_common_condition (rows: 285)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillCommonCondition
{
    [JsonPropertyName("battle_weather")]
    public long BattleWeather { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("min_hp_state")]
    public long MinHpState { get; set; }
    [JsonPropertyName("player_type")]
    public long PlayerType { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("skill_type")]
    public long SkillType { get; set; }
}
