// <auto-generated />
// Table: config_sportsmeet_rank (rows: 33)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSportsmeetRank
{
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("range")]
    public List<long>? Range { get; set; }
    [JsonPropertyName("range_desc")]
    public string? RangeDesc { get; set; }
    [JsonPropertyName("rank_pic")]
    public List<string>? RankPic { get; set; }
    [JsonPropertyName("rank_reward")]
    public long RankReward { get; set; }
    [JsonPropertyName("rank_reward_curren")]
    public long RankRewardCurren { get; set; }
    [JsonPropertyName("sport_type")]
    public long SportType { get; set; }
}
