// <auto-generated />
// Table: config_askill_dict_projectile_ctrl (rows: 3458)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAskillDictProjectileCtrl
{
    [JsonPropertyName("create_dir_type")]
    public long CreateDirType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("independent")]
    public long Independent { get; set; }
    [JsonPropertyName("independent_duration")]
    public long IndependentDuration { get; set; }
    [JsonPropertyName("logic_array")]
    public List<long>? LogicArray { get; set; }
    [JsonPropertyName("logic_delay")]
    public long LogicDelay { get; set; }
    [JsonPropertyName("move_step")]
    public string? MoveStep { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("projectCtrlDelayOption")]
    public long ProjectCtrlDelayOption { get; set; }
    [JsonPropertyName("projectile_item")]
    public List<long>? ProjectileItem { get; set; }
    [JsonPropertyName("trigger_time_type")]
    public long TriggerTimeType { get; set; }
}
