// <auto-generated />
// Table: config_weather (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigWeather
{
    [JsonPropertyName("battle_tip")]
    public long BattleTip { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("random_count")]
    public long RandomCount { get; set; }
    [JsonPropertyName("random_event")]
    public List<long>? RandomEvent { get; set; }
    [JsonPropertyName("scene_param")]
    public List<List<double>>? SceneParam { get; set; }
    [JsonPropertyName("state_event")]
    public List<long>? StateEvent { get; set; }
    [JsonPropertyName("ui_battle_pic")]
    public string? UiBattlePic { get; set; }
    [JsonPropertyName("weight")]
    public List<long>? Weight { get; set; }
}
