// <auto-generated />
// Table: config_ship_talent_upgrade_item (rows: 0)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipTalentUpgradeItem
{
}
