// <auto-generated />
// Table: config_equip (rows: 989)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquip
{
    [JsonPropertyName("activity_equip")]
    public long ActivityEquip { get; set; }
    [JsonPropertyName("activity_id")]
    public List<long>? ActivityId { get; set; }
    [JsonPropertyName("copy_display_id")]
    public List<object>? CopyDisplayId { get; set; }
    [JsonPropertyName("dismantling_get")]
    public List<long>? DismantlingGet { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("e_id")]
    public long EId { get; set; }
    [JsonPropertyName("energy_name")]
    public string? EnergyName { get; set; }
    [JsonPropertyName("enhance_level_max")]
    public long EnhanceLevelMax { get; set; }
    [JsonPropertyName("enhance_prop")]
    public List<List<long>>? EnhanceProp { get; set; }
    [JsonPropertyName("equip_prop")]
    public List<List<long>>? EquipProp { get; set; }
    [JsonPropertyName("equip_ship")]
    public List<long>? EquipShip { get; set; }
    [JsonPropertyName("equip_skill_anim_eb_id")]
    public string? EquipSkillAnimEbId { get; set; }
    [JsonPropertyName("equip_srp_id")]
    public string? EquipSrpId { get; set; }
    [JsonPropertyName("equip_trap_ste_id")]
    public long EquipTrapSteId { get; set; }
    [JsonPropertyName("equip_type_id")]
    public long EquipTypeId { get; set; }
    [JsonPropertyName("equip_type_id2")]
    public long EquipTypeId2 { get; set; }
    [JsonPropertyName("ewt_id")]
    public List<long>? EwtId { get; set; }
    [JsonPropertyName("existence")]
    public long Existence { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_small")]
    public string? IconSmall { get; set; }
    [JsonPropertyName("max_energy")]
    public long MaxEnergy { get; set; }
    [JsonPropertyName("max_number")]
    public long MaxNumber { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("no_pack")]
    public long NoPack { get; set; }
    [JsonPropertyName("no_resolve")]
    public long NoResolve { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("picture_show")]
    public long PictureShow { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("renovate_skill")]
    public List<long>? RenovateSkill { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("rules")]
    public List<object>? Rules { get; set; }
    [JsonPropertyName("ryza_formula_id")]
    public long RyzaFormulaId { get; set; }
    [JsonPropertyName("ryza_type")]
    public List<long>? RyzaType { get; set; }
    [JsonPropertyName("ryza_type_num")]
    public long RyzaTypeNum { get; set; }
    [JsonPropertyName("skill_array")]
    public List<object>? SkillArray { get; set; }
    [JsonPropertyName("skill_fashion_id")]
    public List<object>? SkillFashionId { get; set; }
    [JsonPropertyName("star_max")]
    public long StarMax { get; set; }
}
