// <auto-generated />
// Table: config_copy_enemy (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCopyEnemy
{
    [JsonPropertyName("aircraft")]
    public long Aircraft { get; set; }
    [JsonPropertyName("angle_spped")]
    public long AngleSpped { get; set; }
    [JsonPropertyName("attack")]
    public long Attack { get; set; }
    [JsonPropertyName("battle_angle_speed")]
    public long BattleAngleSpeed { get; set; }
    [JsonPropertyName("defence")]
    public long Defence { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("enmey_type")]
    public string? EnmeyType { get; set; }
    [JsonPropertyName("hero_id")]
    public string? HeroId { get; set; }
    [JsonPropertyName("hp")]
    public long Hp { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("view_range")]
    public long ViewRange { get; set; }
}
