// <auto-generated />
// Table: config_task_treaty (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskTreaty
{
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
}
