// <auto-generated />
// Table: config_building_furniture_res (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildingFurnitureRes
{
    [JsonPropertyName("furniture_id")]
    public long FurnitureId { get; set; }
    [JsonPropertyName("furniture_long")]
    public long FurnitureLong { get; set; }
    [JsonPropertyName("furniture_res")]
    public string? FurnitureRes { get; set; }
    [JsonPropertyName("furniture_type")]
    public long FurnitureType { get; set; }
    [JsonPropertyName("furniture_wide")]
    public long FurnitureWide { get; set; }
    [JsonPropertyName("subsidiary_layer")]
    public long SubsidiaryLayer { get; set; }
    [JsonPropertyName("subsidiary_type")]
    public long SubsidiaryType { get; set; }
}
