// <auto-generated />
// Table: config_ship_combat_effectiveness (rows: 11)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipCombatEffectiveness
{
    [JsonPropertyName("attack")]
    public long Attack { get; set; }
    [JsonPropertyName("defense")]
    public long Defense { get; set; }
    [JsonPropertyName("hp")]
    public long Hp { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("plane_air_control")]
    public long PlaneAirControl { get; set; }
    [JsonPropertyName("plane_bomb_attack")]
    public long PlaneBombAttack { get; set; }
    [JsonPropertyName("ship_air_control")]
    public long ShipAirControl { get; set; }
    [JsonPropertyName("ship_bomb_attack")]
    public long ShipBombAttack { get; set; }
    [JsonPropertyName("ship_type2")]
    public long ShipType2 { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("survival_factor")]
    public long SurvivalFactor { get; set; }
    [JsonPropertyName("to_air_attack")]
    public long ToAirAttack { get; set; }
    [JsonPropertyName("torpedo_attack")]
    public long TorpedoAttack { get; set; }
    [JsonPropertyName("torpedo_defense")]
    public long TorpedoDefense { get; set; }
}
