// <auto-generated />
// Table: config_askill_dict_create_item (rows: 3094)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAskillDictCreateItem
{
    [JsonPropertyName("distance")]
    public double Distance { get; set; }
    [JsonPropertyName("euler")]
    public double Euler { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
