// <auto-generated />
// Table: config_left_camera_controller (rows: 29)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigLeftCameraController
{
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_preemptive")]
    public long IsPreemptive { get; set; }
    [JsonPropertyName("next_correct_weidth")]
    public long NextCorrectWeidth { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("trigger_condition")]
    public string? TriggerCondition { get; set; }
    [JsonPropertyName("trigger_search_mode")]
    public long TriggerSearchMode { get; set; }
    [JsonPropertyName("trigger_target")]
    public string? TriggerTarget { get; set; }
    [JsonPropertyName("trigger_type")]
    public long TriggerType { get; set; }
    [JsonPropertyName("trigger_weidth")]
    public long TriggerWeidth { get; set; }
    [JsonPropertyName("use_ship_behaviour_and_camera_states")]
    public List<string>? UseShipBehaviourAndCameraStates { get; set; }
}
