// <auto-generated />
// Table: config_plot_episode_trigger (rows: 2195)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlotEpisodeTrigger
{
    [JsonPropertyName("plot_copydisplay_id_end")]
    public long PlotCopydisplayIdEnd { get; set; }
    [JsonPropertyName("plot_copydisplay_id_end_branch")]
    public long PlotCopydisplayIdEndBranch { get; set; }
    [JsonPropertyName("plot_episode_id")]
    public long PlotEpisodeId { get; set; }
    [JsonPropertyName("plot_episode_reward")]
    public List<List<long>>? PlotEpisodeReward { get; set; }
    [JsonPropertyName("plot_steps")]
    public string? PlotSteps { get; set; }
    [JsonPropertyName("plot_tableName")]
    public string? PlotTableName { get; set; }
    [JsonPropertyName("plot_trigger_end")]
    public long PlotTriggerEnd { get; set; }
    [JsonPropertyName("plot_trigger_id")]
    public long PlotTriggerId { get; set; }
    [JsonPropertyName("plot_trigger_parameter")]
    public List<long>? PlotTriggerParameter { get; set; }
    [JsonPropertyName("plot_trigger_type")]
    public string? PlotTriggerType { get; set; }
    [JsonPropertyName("plot_trigger_type_id")]
    public long PlotTriggerTypeId { get; set; }
    [JsonPropertyName("repeat_trigger")]
    public long RepeatTrigger { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("trigger_switch")]
    public long TriggerSwitch { get; set; }
}
