// <auto-generated />
// Table: config_adventure_role (rows: 30)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAdventureRole
{
    [JsonPropertyName("attack_max")]
    public long AttackMax { get; set; }
    [JsonPropertyName("enemy_life")]
    public long EnemyLife { get; set; }
    [JsonPropertyName("hero_life")]
    public long HeroLife { get; set; }
    [JsonPropertyName("hero_name")]
    public string? HeroName { get; set; }
    [JsonPropertyName("hero_profession")]
    public string? HeroProfession { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("image_attack")]
    public string? ImageAttack { get; set; }
    [JsonPropertyName("image_death")]
    public string? ImageDeath { get; set; }
    [JsonPropertyName("level_max")]
    public long LevelMax { get; set; }
    [JsonPropertyName("levelup_item")]
    public List<long>? LevelupItem { get; set; }
    [JsonPropertyName("levelup_item_num")]
    public List<long>? LevelupItemNum { get; set; }
    [JsonPropertyName("levelup_life")]
    public List<long>? LevelupLife { get; set; }
    [JsonPropertyName("task_id")]
    public long TaskId { get; set; }
}
