// <auto-generated />
// Table: config_battle_ai_ship_skill_ratio (rows: 57)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiShipSkillRatio
{
    [JsonPropertyName("attack_range")]
    public long AttackRange { get; set; }
    [JsonPropertyName("basi_id")]
    public long BasiId { get; set; }
    [JsonPropertyName("bassr_id")]
    public long BassrId { get; set; }
    [JsonPropertyName("skill_base_ratio")]
    public double SkillBaseRatio { get; set; }
    [JsonPropertyName("skill_type")]
    public long SkillType { get; set; }
}
