// <auto-generated />
// Table: config_chat_emoji (rows: 17)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChatEmoji
{
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
