// <auto-generated />
// Table: config_system_info_text (rows: 14)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSystemInfoText
{
    [JsonPropertyName("beizhu")]
    public string? Beizhu { get; set; }
    [JsonPropertyName("btn_img1")]
    public string? BtnImg1 { get; set; }
    [JsonPropertyName("btn_img2")]
    public string? BtnImg2 { get; set; }
    [JsonPropertyName("btn_num")]
    public long BtnNum { get; set; }
    [JsonPropertyName("btn_txt1")]
    public string? BtnTxt1 { get; set; }
    [JsonPropertyName("btn_txt2")]
    public string? BtnTxt2 { get; set; }
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("infoId")]
    public long InfoId { get; set; }
    [JsonPropertyName("priority")]
    public long Priority { get; set; }
    [JsonPropertyName("style")]
    public long Style { get; set; }
    [JsonPropertyName("title_chi")]
    public string? TitleChi { get; set; }
    [JsonPropertyName("title_eng")]
    public string? TitleEng { get; set; }
}
