// <auto-generated />
// Table: config_cheat_app (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCheatApp
{
    [JsonPropertyName("cheat_id")]
    public long CheatId { get; set; }
    [JsonPropertyName("package")]
    public string? Package { get; set; }
}
