// <auto-generated />
// Table: config_daily_finish (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDailyFinish
{
    [JsonPropertyName("fetch_icon")]
    public string? FetchIcon { get; set; }
    [JsonPropertyName("fetched_icon")]
    public string? FetchedIcon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("login_achievements")]
    public long LoginAchievements { get; set; }
    [JsonPropertyName("login_type")]
    public List<long>? LoginType { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
