// <auto-generated />
// Table: config_fleet_patrol_route (rows: 3244)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFleetPatrolRoute
{
    [JsonPropertyName("f_id")]
    public string? FId { get; set; }
    [JsonPropertyName("fpr_id")]
    public string? FprId { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("sp_id")]
    public string? SpId { get; set; }
}
