// <auto-generated />
// Table: config_boss_life_control (rows: 240)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBossLifeControl
{
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("life")]
    public string? Life { get; set; }
    [JsonPropertyName("time")]
    public long Time { get; set; }
}
