// <auto-generated />
// Table: config_ship_talent_upgrade_exp (rows: 20)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipTalentUpgradeExp
{
    [JsonPropertyName("exp")]
    public long Exp { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
}
