// <auto-generated />
// Table: config_shop_goods (rows: 2136)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShopGoods
{
    [JsonPropertyName("activatetime")]
    public long Activatetime { get; set; }
    [JsonPropertyName("buy_limits")]
    public List<long>? BuyLimits { get; set; }
    [JsonPropertyName("buy_type")]
    public long BuyType { get; set; }
    [JsonPropertyName("count_refresh")]
    public List<long>? CountRefresh { get; set; }
    [JsonPropertyName("cur_relation")]
    public long CurRelation { get; set; }
    [JsonPropertyName("currency")]
    public List<List<long>>? Currency { get; set; }
    [JsonPropertyName("discount")]
    public List<long>? Discount { get; set; }
    [JsonPropertyName("goods")]
    public List<long>? Goods { get; set; }
    [JsonPropertyName("goods_visible")]
    public long GoodsVisible { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_buy_batch")]
    public long IsBuyBatch { get; set; }
    [JsonPropertyName("language_id")]
    public long LanguageId { get; set; }
    [JsonPropertyName("last_id")]
    public long LastId { get; set; }
    [JsonPropertyName("level_deblocking")]
    public long LevelDeblocking { get; set; }
    [JsonPropertyName("manual_refresh_stock")]
    public long ManualRefreshStock { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("new")]
    public long New { get; set; }
    [JsonPropertyName("open_limit")]
    public List<object>? OpenLimit { get; set; }
    [JsonPropertyName("period_buy")]
    public List<long>? PeriodBuy { get; set; }
    [JsonPropertyName("period_show")]
    public long PeriodShow { get; set; }
    [JsonPropertyName("price")]
    public List<List<long>>? Price { get; set; }
    [JsonPropertyName("price1")]
    public List<List<long>>? Price1 { get; set; }
    [JsonPropertyName("price2")]
    public List<List<long>>? Price2 { get; set; }
    [JsonPropertyName("random_limits")]
    public List<long>? RandomLimits { get; set; }
    [JsonPropertyName("recharge_id")]
    public long RechargeId { get; set; }
    [JsonPropertyName("recommend_weight")]
    public long RecommendWeight { get; set; }
    [JsonPropertyName("shelf_id")]
    public long ShelfId { get; set; }
    [JsonPropertyName("show_limit")]
    public long ShowLimit { get; set; }
    [JsonPropertyName("stock")]
    public long Stock { get; set; }
    [JsonPropertyName("stock_period_max_count")]
    public long StockPeriodMaxCount { get; set; }
    [JsonPropertyName("undercarriage")]
    public long Undercarriage { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
