// <auto-generated />
// Table: config_recharge (rows: 607)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRecharge
{
    [JsonPropertyName("activitydrop")]
    public long Activitydrop { get; set; }
    [JsonPropertyName("appeartype")]
    public long Appeartype { get; set; }
    [JsonPropertyName("boxexisttime")]
    public long Boxexisttime { get; set; }
    [JsonPropertyName("buy_limit")]
    public List<object>? BuyLimit { get; set; }
    [JsonPropertyName("buynum")]
    public long Buynum { get; set; }
    [JsonPropertyName("buynum_refreshtime")]
    public long BuynumRefreshtime { get; set; }
    [JsonPropertyName("channel")]
    public long Channel { get; set; }
    [JsonPropertyName("condition")]
    public long Condition { get; set; }
    [JsonPropertyName("cost")]
    public long Cost { get; set; }
    [JsonPropertyName("currency_type")]
    public long CurrencyType { get; set; }
    [JsonPropertyName("daily_reward")]
    public long DailyReward { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("double_period")]
    public List<long>? DoublePeriod { get; set; }
    [JsonPropertyName("drop")]
    public long Drop { get; set; }
    [JsonPropertyName("drop_reward")]
    public long DropReward { get; set; }
    [JsonPropertyName("duration")]
    public long Duration { get; set; }
    [JsonPropertyName("extra_reward")]
    public long ExtraReward { get; set; }
    [JsonPropertyName("flag_id")]
    public List<long>? FlagId { get; set; }
    [JsonPropertyName("free_duration")]
    public long FreeDuration { get; set; }
    [JsonPropertyName("free_reward")]
    public long FreeReward { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("isshow")]
    public long Isshow { get; set; }
    [JsonPropertyName("last_id")]
    public long LastId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("nodouble_desc")]
    public string? NodoubleDesc { get; set; }
    [JsonPropertyName("nodouble_extra_reward")]
    public long NodoubleExtraReward { get; set; }
    [JsonPropertyName("nodouble_extra_reward_desc")]
    public string? NodoubleExtraRewardDesc { get; set; }
    [JsonPropertyName("open_limit")]
    public List<object>? OpenLimit { get; set; }
    [JsonPropertyName("orderparam")]
    public List<long>? Orderparam { get; set; }
    [JsonPropertyName("orderscript")]
    public string? Orderscript { get; set; }
    [JsonPropertyName("originalcost")]
    public long Originalcost { get; set; }
    [JsonPropertyName("paytype")]
    public long Paytype { get; set; }
    [JsonPropertyName("privilege")]
    public long Privilege { get; set; }
    [JsonPropertyName("privilegedesc")]
    public List<long>? Privilegedesc { get; set; }
    [JsonPropertyName("productId")]
    public long ProductId { get; set; }
    [JsonPropertyName("pushnum")]
    public long Pushnum { get; set; }
    [JsonPropertyName("random_limit")]
    public List<object>? RandomLimit { get; set; }
    [JsonPropertyName("recharge_value")]
    public long RechargeValue { get; set; }
    [JsonPropertyName("recommend_bg1")]
    public string? RecommendBg1 { get; set; }
    [JsonPropertyName("recommend_bg2")]
    public string? RecommendBg2 { get; set; }
    [JsonPropertyName("refreshid")]
    public List<long>? Refreshid { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
    [JsonPropertyName("sdkdesc")]
    public string? Sdkdesc { get; set; }
    [JsonPropertyName("selltime")]
    public long Selltime { get; set; }
    [JsonPropertyName("shop_bg")]
    public string? ShopBg { get; set; }
    [JsonPropertyName("show_createdays")]
    public long ShowCreatedays { get; set; }
    [JsonPropertyName("show_name")]
    public string? ShowName { get; set; }
    [JsonPropertyName("show_reddot")]
    public long ShowReddot { get; set; }
    [JsonPropertyName("tagid")]
    public long Tagid { get; set; }
    [JsonPropertyName("true_cost")]
    public long TrueCost { get; set; }
    [JsonPropertyName("value")]
    public long Value { get; set; }
    [JsonPropertyName("weight")]
    public long Weight { get; set; }
}
