// <auto-generated />
// Table: config_magazine_info (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMagazineInfo
{
    [JsonPropertyName("buff_id")]
    public List<long>? BuffId { get; set; }
    [JsonPropertyName("condition")]
    public List<long>? Condition { get; set; }
    [JsonPropertyName("condition_max")]
    public object? ConditionMax { get; set; }
    [JsonPropertyName("content_ship")]
    public List<long>? ContentShip { get; set; }
    [JsonPropertyName("contents_left")]
    public List<long>? ContentsLeft { get; set; }
    [JsonPropertyName("contents_right")]
    public List<long>? ContentsRight { get; set; }
    [JsonPropertyName("cover_image")]
    public string? CoverImage { get; set; }
    [JsonPropertyName("cover_image_big")]
    public string? CoverImageBig { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_open")]
    public long IsOpen { get; set; }
    [JsonPropertyName("item")]
    public List<long>? Item { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("num")]
    public string? Num { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("page_id")]
    public List<long>? PageId { get; set; }
    [JsonPropertyName("pagedown_id")]
    public List<long>? PagedownId { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("period_area")]
    public List<object>? PeriodArea { get; set; }
    [JsonPropertyName("release_lock")]
    public List<long>? ReleaseLock { get; set; }
    [JsonPropertyName("rewards")]
    public List<long>? Rewards { get; set; }
    [JsonPropertyName("rewards_long")]
    public List<long>? RewardsLong { get; set; }
    [JsonPropertyName("show_tag_id")]
    public List<long>? ShowTagId { get; set; }
    [JsonPropertyName("special")]
    public long Special { get; set; }
    [JsonPropertyName("tag_num_image")]
    public List<string>? TagNumImage { get; set; }
    [JsonPropertyName("task_left_id")]
    public List<long>? TaskLeftId { get; set; }
    [JsonPropertyName("task_period_area")]
    public List<long>? TaskPeriodArea { get; set; }
    [JsonPropertyName("task_rewards")]
    public long TaskRewards { get; set; }
    [JsonPropertyName("task_right_id")]
    public List<long>? TaskRightId { get; set; }
    [JsonPropertyName("ticket_info")]
    public List<long>? TicketInfo { get; set; }
    [JsonPropertyName("ticket_period_area")]
    public List<long>? TicketPeriodArea { get; set; }
    [JsonPropertyName("ticket_ship_id")]
    public List<long>? TicketShipId { get; set; }
}
