// <auto-generated />
// Table: config_ship_model_look_camera (rows: 14)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipModelLookCamera
{
    [JsonPropertyName("camera_index")]
    public long CameraIndex { get; set; }
    [JsonPropertyName("camera_path")]
    public string? CameraPath { get; set; }
    [JsonPropertyName("camera_target")]
    public long CameraTarget { get; set; }
    [JsonPropertyName("model")]
    public string? Model { get; set; }
    [JsonPropertyName("offset_euler_x")]
    public double OffsetEulerX { get; set; }
    [JsonPropertyName("offset_euler_y")]
    public double OffsetEulerY { get; set; }
    [JsonPropertyName("offset_euler_z")]
    public long OffsetEulerZ { get; set; }
    [JsonPropertyName("offset_position_x")]
    public double OffsetPositionX { get; set; }
    [JsonPropertyName("offset_position_y")]
    public double OffsetPositionY { get; set; }
    [JsonPropertyName("offset_position_z")]
    public double OffsetPositionZ { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
}
