// <auto-generated />
// Table: config_skill_trap_item (rows: 239)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTrapItem
{
    [JsonPropertyName("delay_time")]
    public long DelayTime { get; set; }
    [JsonPropertyName("euler_delta")]
    public double EulerDelta { get; set; }
    [JsonPropertyName("pos_x")]
    public long PosX { get; set; }
    [JsonPropertyName("pos_y")]
    public long PosY { get; set; }
    [JsonPropertyName("scale_shift")]
    public long ScaleShift { get; set; }
    [JsonPropertyName("select_weight")]
    public long SelectWeight { get; set; }
    [JsonPropertyName("shape_param")]
    public string? ShapeParam { get; set; }
    [JsonPropertyName("shape_type")]
    public long ShapeType { get; set; }
    [JsonPropertyName("ste_id")]
    public long SteId { get; set; }
    [JsonPropertyName("sti_id")]
    public long StiId { get; set; }
    [JsonPropertyName("svte_id")]
    public long SvteId { get; set; }
}
