// <auto-generated />
// Table: config_boss_copy_main (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBossCopyMain
{
    [JsonPropertyName("boss_life")]
    public long BossLife { get; set; }
    [JsonPropertyName("copy_display_id")]
    public List<long>? CopyDisplayId { get; set; }
    [JsonPropertyName("eff_boss")]
    public string? EffBoss { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image_boss")]
    public string? ImageBoss { get; set; }
    [JsonPropertyName("image_boss_2")]
    public string? ImageBoss2 { get; set; }
    [JsonPropertyName("image_boss_clear")]
    public string? ImageBossClear { get; set; }
    [JsonPropertyName("image_position")]
    public List<long>? ImagePosition { get; set; }
    [JsonPropertyName("image_scale")]
    public List<double>? ImageScale { get; set; }
    [JsonPropertyName("mail_id")]
    public long MailId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
}
