// <auto-generated />
// Table: config_teaching_achievement (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTeachingAchievement
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("next_id")]
    public long NextId { get; set; }
    [JsonPropertyName("prestige")]
    public long Prestige { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
}
