// <auto-generated />
// Table: config_player_levelup (rows: 100)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPlayerLevelup
{
    [JsonPropertyName("exp")]
    public long Exp { get; set; }
    [JsonPropertyName("friends_count")]
    public long FriendsCount { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("levelup_rewards")]
    public long LevelupRewards { get; set; }
    [JsonPropertyName("month_supply_max_add")]
    public long MonthSupplyMaxAdd { get; set; }
    [JsonPropertyName("month_supply_speed_add")]
    public List<long>? MonthSupplySpeedAdd { get; set; }
    [JsonPropertyName("pvept_num")]
    public long PveptNum { get; set; }
    [JsonPropertyName("pvept_recovery")]
    public List<long>? PveptRecovery { get; set; }
    [JsonPropertyName("supply_increase_speed")]
    public List<long>? SupplyIncreaseSpeed { get; set; }
    [JsonPropertyName("supply_max_limit")]
    public long SupplyMaxLimit { get; set; }
    [JsonPropertyName("tactic_poin")]
    public long TacticPoin { get; set; }
    [JsonPropertyName("world_chat_count_limit")]
    public long WorldChatCountLimit { get; set; }
}
