// <auto-generated />
// Table: config_guildoffer_scorereward (rows: 25)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildofferScorereward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("personscore")]
    public long Personscore { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
}
