// <auto-generated />
// Table: config_battle_ai_support (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiSupport
{
    [JsonPropertyName("ba_id")]
    public string? BaId { get; set; }
    [JsonPropertyName("call_for_support_time")]
    public long CallForSupportTime { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("fleet_id")]
    public string? FleetId { get; set; }
    [JsonPropertyName("support_arg")]
    public string? SupportArg { get; set; }
    [JsonPropertyName("support_type")]
    public long SupportType { get; set; }
}
