// <auto-generated />
// Table: config_challenge (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChallenge
{
    [JsonPropertyName("function_id")]
    public long FunctionId { get; set; }
    [JsonPropertyName("function_param")]
    public List<long>? FunctionParam { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_open")]
    public long IsOpen { get; set; }
    [JsonPropertyName("message1")]
    public string? Message1 { get; set; }
    [JsonPropertyName("message2")]
    public string? Message2 { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("red_dot")]
    public List<long>? RedDot { get; set; }
    [JsonPropertyName("red_dot_param")]
    public List<List<long>>? RedDotParam { get; set; }
}
