// <auto-generated />
// Table: config_ship_show (rows: 1417)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipShow
{
    [JsonPropertyName("building_model")]
    public string? BuildingModel { get; set; }
    [JsonPropertyName("constellation")]
    public long Constellation { get; set; }
    [JsonPropertyName("cut_in_head")]
    public string? CutInHead { get; set; }
    [JsonPropertyName("cut_in_icon")]
    public string? CutInIcon { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("info")]
    public string? Info { get; set; }
    [JsonPropertyName("model_id")]
    public string? ModelId { get; set; }
    [JsonPropertyName("model_radius")]
    public long ModelRadius { get; set; }
    [JsonPropertyName("plane_air_equip_id")]
    public long PlaneAirEquipId { get; set; }
    [JsonPropertyName("plane_bomb_equip_id")]
    public long PlaneBombEquipId { get; set; }
    [JsonPropertyName("plane_torpedo_equip_id")]
    public long PlaneTorpedoEquipId { get; set; }
    [JsonPropertyName("profilelist")]
    public List<long>? Profilelist { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("sf_id")]
    public long SfId { get; set; }
    [JsonPropertyName("ship_battle_hp_state")]
    public List<string>? ShipBattleHpState { get; set; }
    [JsonPropertyName("ship_behaviour")]
    public List<long>? ShipBehaviour { get; set; }
    [JsonPropertyName("ship_character")]
    public List<long>? ShipCharacter { get; set; }
    [JsonPropertyName("ship_country")]
    public long ShipCountry { get; set; }
    [JsonPropertyName("ship_draw")]
    public string? ShipDraw { get; set; }
    [JsonPropertyName("ship_draw_black")]
    public string? ShipDrawBlack { get; set; }
    [JsonPropertyName("ship_draw_po")]
    public string? ShipDrawPo { get; set; }
    [JsonPropertyName("ship_icon1")]
    public string? ShipIcon1 { get; set; }
    [JsonPropertyName("ship_icon1_back")]
    public string? ShipIcon1Back { get; set; }
    [JsonPropertyName("ship_icon1_po")]
    public string? ShipIcon1Po { get; set; }
    [JsonPropertyName("ship_icon1_po_back")]
    public string? ShipIcon1PoBack { get; set; }
    [JsonPropertyName("ship_icon2")]
    public string? ShipIcon2 { get; set; }
    [JsonPropertyName("ship_icon2_black")]
    public string? ShipIcon2Black { get; set; }
    [JsonPropertyName("ship_icon2_po")]
    public string? ShipIcon2Po { get; set; }
    [JsonPropertyName("ship_icon3")]
    public string? ShipIcon3 { get; set; }
    [JsonPropertyName("ship_icon3_po")]
    public string? ShipIcon3Po { get; set; }
    [JsonPropertyName("ship_icon4")]
    public string? ShipIcon4 { get; set; }
    [JsonPropertyName("ship_icon4_po")]
    public string? ShipIcon4Po { get; set; }
    [JsonPropertyName("ship_icon5")]
    public string? ShipIcon5 { get; set; }
    [JsonPropertyName("ship_icon6")]
    public string? ShipIcon6 { get; set; }
    [JsonPropertyName("ship_icon6_po")]
    public string? ShipIcon6Po { get; set; }
    [JsonPropertyName("ship_icon7")]
    public string? ShipIcon7 { get; set; }
    [JsonPropertyName("ship_icon7_po")]
    public string? ShipIcon7Po { get; set; }
    [JsonPropertyName("ship_icon_animoji")]
    public string? ShipIconAnimoji { get; set; }
    [JsonPropertyName("ship_icon_bathroom")]
    public string? ShipIconBathroom { get; set; }
    [JsonPropertyName("ship_icon_search3d")]
    public string? ShipIconSearch3d { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("skill_airAttack_eb_id")]
    public List<string>? SkillAirAttackEbId { get; set; }
    [JsonPropertyName("skill_airBomb_eb_id")]
    public List<string>? SkillAirBombEbId { get; set; }
    [JsonPropertyName("skill_airSearch_eb_id")]
    public List<string>? SkillAirSearchEbId { get; set; }
    [JsonPropertyName("skill_airTorpedo_eb_id")]
    public List<string>? SkillAirTorpedoEbId { get; set; }
    [JsonPropertyName("skill_torpedo_eb_id")]
    public List<string>? SkillTorpedoEbId { get; set; }
    [JsonPropertyName("ss_id")]
    public long SsId { get; set; }
}
