// <auto-generated />
// Table: config_audio (rows: 145)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAudio
{
    [JsonPropertyName("a_id")]
    public string? AId { get; set; }
    [JsonPropertyName("can_repeat")]
    public long CanRepeat { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("repeat_time")]
    public long RepeatTime { get; set; }
    [JsonPropertyName("res_path")]
    public string? ResPath { get; set; }
}
