// <auto-generated />
// Table: config_ship_exp_item (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipExpItem
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("exp")]
    public long Exp { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level_limit")]
    public List<object>? LevelLimit { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("ship_country")]
    public List<long>? ShipCountry { get; set; }
    [JsonPropertyName("ship_type")]
    public List<object>? ShipType { get; set; }
}
