// <auto-generated />
// Table: config_guildoffer_perscorereward (rows: 35)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildofferPerscorereward
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("reward")]
    public long Reward { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
}
