// <auto-generated />
// Table: config_talentcondition (rows: 214)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTalentcondition
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("p1")]
    public long P1 { get; set; }
    [JsonPropertyName("p2")]
    public long P2 { get; set; }
    [JsonPropertyName("p3")]
    public long P3 { get; set; }
    [JsonPropertyName("p4")]
    public long P4 { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
