// <auto-generated />
// Table: config_language (rows: 5493)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigLanguage
{
    [JsonPropertyName("content")]
    public string? Content { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
