// <auto-generated />
// Table: config_drop_info (rows: 1948)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDropInfo
{
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("drop_rate")]
    public string? DropRate { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_info")]
    public List<List<long>>? ItemInfo { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("out_show_num")]
    public long OutShowNum { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("quality_bg")]
    public string? QualityBg { get; set; }
    [JsonPropertyName("show_counts")]
    public long ShowCounts { get; set; }
    [JsonPropertyName("show_num")]
    public long ShowNum { get; set; }
    [JsonPropertyName("treaty_item")]
    public List<long>? TreatyItem { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
