// <auto-generated />
// Table: config_skill_be_hit_order (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillBeHitOrder
{
    [JsonPropertyName("behit_bind_types")]
    public List<long>? BehitBindTypes { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("s_id")]
    public string? SId { get; set; }
    [JsonPropertyName("ship_id")]
    public string? ShipId { get; set; }
}
