// <auto-generated />
// Table: config_pskill_dict_c_param (rows: 66)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictCParam
{
    [JsonPropertyName("condition_func")]
    public string? ConditionFunc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("param_type")]
    public long ParamType { get; set; }
}
