// <auto-generated />
// Table: config_fragment (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFragment
{
    [JsonPropertyName("amount")]
    public long Amount { get; set; }
    [JsonPropertyName("coin")]
    public long Coin { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_small")]
    public string? IconSmall { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item_id")]
    public List<long>? ItemId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
}
