// <auto-generated />
// Table: config_equip_enhance_renovate (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipEnhanceRenovate
{
    [JsonPropertyName("equip_self_count")]
    public long EquipSelfCount { get; set; }
    [JsonPropertyName("item_array")]
    public List<List<long>>? ItemArray { get; set; }
    [JsonPropertyName("need_enhance_level")]
    public long NeedEnhanceLevel { get; set; }
    [JsonPropertyName("renovate_level")]
    public long RenovateLevel { get; set; }
}
