// <auto-generated />
// Table: config_battlefield_resource (rows: 2722)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattlefieldResource
{
    [JsonPropertyName("buffid")]
    public List<long>? Buffid { get; set; }
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("flag")]
    public long Flag { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("odds")]
    public long Odds { get; set; }
    [JsonPropertyName("pos_id")]
    public string? PosId { get; set; }
    [JsonPropertyName("res_collide_effect_id")]
    public string? ResCollideEffectId { get; set; }
    [JsonPropertyName("res_collide_msg_effect_id")]
    public string? ResCollideMsgEffectId { get; set; }
    [JsonPropertyName("res_find_effect_id")]
    public string? ResFindEffectId { get; set; }
    [JsonPropertyName("res_image_effect_id")]
    public string? ResImageEffectId { get; set; }
    [JsonPropertyName("resourc_num")]
    public long ResourcNum { get; set; }
    [JsonPropertyName("resource_items")]
    public long ResourceItems { get; set; }
    [JsonPropertyName("resource_type")]
    public long ResourceType { get; set; }
    [JsonPropertyName("search3d_item_id")]
    public long Search3dItemId { get; set; }
    [JsonPropertyName("server")]
    public long Server { get; set; }
    [JsonPropertyName("settlement_type")]
    public long SettlementType { get; set; }
    [JsonPropertyName("show_num")]
    public long ShowNum { get; set; }
    [JsonPropertyName("show_type")]
    public long ShowType { get; set; }
}
