// <auto-generated />
// Table: config_ship_max_power (rows: 5247)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipMaxPower
{
    [JsonPropertyName("level_value_effect")]
    public List<long>? LevelValueEffect { get; set; }
    [JsonPropertyName("max_power_prop")]
    public List<List<long>>? MaxPowerProp { get; set; }
    [JsonPropertyName("param_list")]
    public List<List<double>>? ParamList { get; set; }
    [JsonPropertyName("script_list")]
    public List<string>? ScriptList { get; set; }
    [JsonPropertyName("smp_id")]
    public long SmpId { get; set; }
}
