// <auto-generated />
// Table: config_navmesh (rows: 168)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigNavmesh
{
    [JsonPropertyName("data")]
    public string? Data { get; set; }
    [JsonPropertyName("sceneID")]
    public string? SceneID { get; set; }
}
