// <auto-generated />
// Table: config_expedition_set (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigExpeditionSet
{
    [JsonPropertyName("count")]
    public long Count { get; set; }
    [JsonPropertyName("front_id")]
    public long FrontId { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_number_sametime")]
    public long MaxNumberSametime { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("refresh_time")]
    public long RefreshTime { get; set; }
    [JsonPropertyName("tasks")]
    public List<long>? Tasks { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
