// <auto-generated />
// Table: config_big_activity_copy_display (rows: 55)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBigActivityCopyDisplay
{
    [JsonPropertyName("copy_button_deviation")]
    public long CopyButtonDeviation { get; set; }
    [JsonPropertyName("diff_choosing_bg")]
    public string? DiffChoosingBg { get; set; }
    [JsonPropertyName("extra_drop_info")]
    public List<long>? ExtraDropInfo { get; set; }
    [JsonPropertyName("extra_drop_item")]
    public List<long>? ExtraDropItem { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("params")]
    public List<long>? Params { get; set; }
    [JsonPropertyName("recommend_power")]
    public long RecommendPower { get; set; }
    [JsonPropertyName("reward_coin")]
    public List<long>? RewardCoin { get; set; }
    [JsonPropertyName("reward_gongxun")]
    public List<long>? RewardGongxun { get; set; }
    [JsonPropertyName("script_function_name")]
    public string? ScriptFunctionName { get; set; }
}
