// <auto-generated />
// Table: config_ship_perform_mark (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipPerformMark
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level")]
    public string? Level { get; set; }
    [JsonPropertyName("max_value")]
    public long MaxValue { get; set; }
    [JsonPropertyName("min_value")]
    public long MinValue { get; set; }
}
