// <auto-generated />
// Table: config_battle_threat (rows: 12)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleThreat
{
    [JsonPropertyName("event_param")]
    public string? EventParam { get; set; }
    [JsonPropertyName("event_type")]
    public long EventType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("threat_time")]
    public long ThreatTime { get; set; }
    [JsonPropertyName("threat_type")]
    public long ThreatType { get; set; }
    [JsonPropertyName("threat_value")]
    public long ThreatValue { get; set; }
}
