// <auto-generated />
// Table: config_weather_exchange_light (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigWeatherExchangeLight
{
    [JsonPropertyName("light_args_duration_s")]
    public List<object>? LightArgsDurationS { get; set; }
    [JsonPropertyName("light_args_name_s")]
    public List<object>? LightArgsNameS { get; set; }
    [JsonPropertyName("light_args_start_time_s")]
    public List<object>? LightArgsStartTimeS { get; set; }
    [JsonPropertyName("light_args_target_value_s")]
    public List<object>? LightArgsTargetValueS { get; set; }
    [JsonPropertyName("light_type")]
    public string? LightType { get; set; }
    [JsonPropertyName("wel_id")]
    public long WelId { get; set; }
}
