// <auto-generated />
// Table: config_novice_ship_info (rows: 7)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigNoviceShipInfo
{
    [JsonPropertyName("equip1")]
    public long Equip1 { get; set; }
    [JsonPropertyName("equip2")]
    public long Equip2 { get; set; }
    [JsonPropertyName("equip3")]
    public long Equip3 { get; set; }
    [JsonPropertyName("equip4")]
    public long Equip4 { get; set; }
    [JsonPropertyName("equip5")]
    public long Equip5 { get; set; }
    [JsonPropertyName("equip6")]
    public long Equip6 { get; set; }
    [JsonPropertyName("novice_id")]
    public long NoviceId { get; set; }
    [JsonPropertyName("ship_enemy_id")]
    public long ShipEnemyId { get; set; }
}
