// <auto-generated />
// Table: config_battle_ai_fleet (rows: 855)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAiFleet
{
    [JsonPropertyName("aerial_search_duration")]
    public long AerialSearchDuration { get; set; }
    [JsonPropertyName("airattack_call")]
    public long AirattackCall { get; set; }
    [JsonPropertyName("baf_id")]
    public long BafId { get; set; }
    [JsonPropertyName("best_dis_odds")]
    public long BestDisOdds { get; set; }
    [JsonPropertyName("call_view_circle_range")]
    public double CallViewCircleRange { get; set; }
    [JsonPropertyName("call_view_euler")]
    public long CallViewEuler { get; set; }
    [JsonPropertyName("call_view_range")]
    public double CallViewRange { get; set; }
    [JsonPropertyName("escape_odds")]
    public double EscapeOdds { get; set; }
    [JsonPropertyName("skill_cd")]
    public long SkillCd { get; set; }
    [JsonPropertyName("speed_ratio")]
    public double SpeedRatio { get; set; }
    [JsonPropertyName("t_odds")]
    public double TOdds { get; set; }
    [JsonPropertyName("track_dis")]
    public long TrackDis { get; set; }
    [JsonPropertyName("track_range")]
    public long TrackRange { get; set; }
    [JsonPropertyName("view_circle_range")]
    public double ViewCircleRange { get; set; }
    [JsonPropertyName("view_euler")]
    public long ViewEuler { get; set; }
    [JsonPropertyName("view_range")]
    public double ViewRange { get; set; }
}
