// <auto-generated />
// Table: config_chapter_plot_type (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChapterPlotType
{
    [JsonPropertyName("chapter_list")]
    public List<long>? ChapterList { get; set; }
    [JsonPropertyName("chapter_list2")]
    public List<List<long>>? ChapterList2 { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("image")]
    public string? Image { get; set; }
    [JsonPropertyName("image_bg")]
    public List<string>? ImageBg { get; set; }
    [JsonPropertyName("image_btn")]
    public string? ImageBtn { get; set; }
    [JsonPropertyName("image_btn_push")]
    public string? ImageBtnPush { get; set; }
    [JsonPropertyName("image_mask")]
    public string? ImageMask { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("p1")]
    public long P1 { get; set; }
    [JsonPropertyName("p2")]
    public long P2 { get; set; }
    [JsonPropertyName("p3")]
    public long P3 { get; set; }
    [JsonPropertyName("p4")]
    public long P4 { get; set; }
    [JsonPropertyName("p5")]
    public long P5 { get; set; }
    [JsonPropertyName("p6")]
    public long P6 { get; set; }
    [JsonPropertyName("plot_enter_name")]
    public List<string>? PlotEnterName { get; set; }
    [JsonPropertyName("show_id")]
    public long ShowId { get; set; }
}
