// <auto-generated />
// Table: config_skill_be_hit_boss_sink (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillBeHitBossSink
{
    [JsonPropertyName("detail_anim_group_id")]
    public long DetailAnimGroupId { get; set; }
    [JsonPropertyName("s_id")]
    public long SId { get; set; }
    [JsonPropertyName("ship_info_id")]
    public string? ShipInfoId { get; set; }
    [JsonPropertyName("sink_state")]
    public long SinkState { get; set; }
}
