// <auto-generated />
// Table: config_random_factor (rows: 394)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRandomFactor
{
    [JsonPropertyName("effect_target")]
    public List<double>? EffectTarget { get; set; }
    [JsonPropertyName("effect_target_player_fleet")]
    public List<long>? EffectTargetPlayerFleet { get; set; }
    [JsonPropertyName("effect_target_type")]
    public long EffectTargetType { get; set; }
    [JsonPropertyName("factor_description")]
    public string? FactorDescription { get; set; }
    [JsonPropertyName("factor_id")]
    public long FactorId { get; set; }
    [JsonPropertyName("factor_image")]
    public List<string>? FactorImage { get; set; }
    [JsonPropertyName("factor_target")]
    public List<long>? FactorTarget { get; set; }
    [JsonPropertyName("factor_target_type")]
    public long FactorTargetType { get; set; }
    [JsonPropertyName("factor_type")]
    public long FactorType { get; set; }
    [JsonPropertyName("game_limits_id")]
    public long GameLimitsId { get; set; }
    [JsonPropertyName("is_enemy")]
    public long IsEnemy { get; set; }
}
