// <auto-generated />
// Table: config_emoji_pack (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEmojiPack
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("picture")]
    public List<long>? Picture { get; set; }
    [JsonPropertyName("type_name")]
    public string? TypeName { get; set; }
}
