// <auto-generated />
// Table: config_askill_dict_projectile_item (rows: 2924)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAskillDictProjectileItem
{
    [JsonPropertyName("delay_time")]
    public long DelayTime { get; set; }
    [JsonPropertyName("delta_euler")]
    public double DeltaEuler { get; set; }
    [JsonPropertyName("delta_pos_x")]
    public double DeltaPosX { get; set; }
    [JsonPropertyName("delta_pos_y")]
    public double DeltaPosY { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("shape_param")]
    public string? ShapeParam { get; set; }
    [JsonPropertyName("shape_type")]
    public long ShapeType { get; set; }
    [JsonPropertyName("ship_trigger_ebid")]
    public string? ShipTriggerEbid { get; set; }
    [JsonPropertyName("ship_trigger_order")]
    public long ShipTriggerOrder { get; set; }
    [JsonPropertyName("size_begin")]
    public double SizeBegin { get; set; }
    [JsonPropertyName("size_change_duration")]
    public long SizeChangeDuration { get; set; }
    [JsonPropertyName("ste_id")]
    public long SteId { get; set; }
    [JsonPropertyName("svte_id")]
    public long SvteId { get; set; }
    [JsonPropertyName("vice_gun_scale_shift")]
    public double ViceGunScaleShift { get; set; }
}
