// <auto-generated />
// Table: config_guildwar_base_info (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildwarBaseInfo
{
    [JsonPropertyName("camera_position")]
    public List<double>? CameraPosition { get; set; }
    [JsonPropertyName("camera_rotate_position")]
    public List<double>? CameraRotatePosition { get; set; }
    [JsonPropertyName("copydisplay_id")]
    public List<long>? CopydisplayId { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("lap")]
    public List<List<long>>? Lap { get; set; }
    [JsonPropertyName("lap_name")]
    public List<string>? LapName { get; set; }
    [JsonPropertyName("pic")]
    public string? Pic { get; set; }
    [JsonPropertyName("stage")]
    public List<long>? Stage { get; set; }
    [JsonPropertyName("stage_level")]
    public List<string>? StageLevel { get; set; }
    [JsonPropertyName("stage_reward")]
    public List<long>? StageReward { get; set; }
}
