// <auto-generated />
// Table: config_big_activity_chapter (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBigActivityChapter
{
    [JsonPropertyName("copy_thumbnail_list")]
    public List<string>? CopyThumbnailList { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("level_list")]
    public List<List<long>>? LevelList { get; set; }
    [JsonPropertyName("name_list")]
    public List<string>? NameList { get; set; }
}
