// <auto-generated />
// Table: config_ship_remould_template (rows: 63)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipRemouldTemplate
{
    [JsonPropertyName("complete_icon")]
    public string? CompleteIcon { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("lock_icon")]
    public string? LockIcon { get; set; }
    [JsonPropertyName("remould_item_group")]
    public List<long>? RemouldItemGroup { get; set; }
    [JsonPropertyName("res")]
    public string? Res { get; set; }
    [JsonPropertyName("select_icon")]
    public string? SelectIcon { get; set; }
    [JsonPropertyName("uncomplete_icon")]
    public string? UncompleteIcon { get; set; }
}
