// <auto-generated />
// Table: config_vow (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigVow
{
    [JsonPropertyName("ban_full_break_add_time")]
    public long BanFullBreakAddTime { get; set; }
    [JsonPropertyName("ban_not_full_break_add_time")]
    public long BanNotFullBreakAddTime { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("quality")]
    public long Quality { get; set; }
    [JsonPropertyName("result_that_quality_add_time")]
    public long ResultThatQualityAddTime { get; set; }
    [JsonPropertyName("result_that_quality_limit_time")]
    public long ResultThatQualityLimitTime { get; set; }
}
