// <auto-generated />
// Table: config_guildactivityrate (rows: 15)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildactivityrate
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rate")]
    public long Rate { get; set; }
    [JsonPropertyName("requireitemnum")]
    public long Requireitemnum { get; set; }
}
