// <auto-generated />
// Table: config_guildparam (rows: 1)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigGuildparam
{
    [JsonPropertyName("acqnote")]
    public long Acqnote { get; set; }
    [JsonPropertyName("announcencdtime")]
    public long Announcencdtime { get; set; }
    [JsonPropertyName("applymax")]
    public long Applymax { get; set; }
    [JsonPropertyName("applytime")]
    public long Applytime { get; set; }
    [JsonPropertyName("campaigntime")]
    public long Campaigntime { get; set; }
    [JsonPropertyName("changenamecost")]
    public List<object>? Changenamecost { get; set; }
    [JsonPropertyName("dismisslimit")]
    public long Dismisslimit { get; set; }
    [JsonPropertyName("dissolvedtime")]
    public long Dissolvedtime { get; set; }
    [JsonPropertyName("drawcost")]
    public long Drawcost { get; set; }
    [JsonPropertyName("guildbuild")]
    public List<long>? Guildbuild { get; set; }
    [JsonPropertyName("guildlv")]
    public long Guildlv { get; set; }
    [JsonPropertyName("guildnamenum")]
    public long Guildnamenum { get; set; }
    [JsonPropertyName("headoutlinetime")]
    public long Headoutlinetime { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("infonum")]
    public long Infonum { get; set; }
    [JsonPropertyName("leastnum")]
    public long Leastnum { get; set; }
    [JsonPropertyName("limitcontribution")]
    public long Limitcontribution { get; set; }
    [JsonPropertyName("mailapplyfail")]
    public long Mailapplyfail { get; set; }
    [JsonPropertyName("mailapplyouttime")]
    public long Mailapplyouttime { get; set; }
    [JsonPropertyName("mailapplysuc")]
    public long Mailapplysuc { get; set; }
    [JsonPropertyName("mailbasicreward")]
    public long Mailbasicreward { get; set; }
    [JsonPropertyName("mailguildbreak")]
    public long Mailguildbreak { get; set; }
    [JsonPropertyName("mailguildcreate")]
    public long Mailguildcreate { get; set; }
    [JsonPropertyName("mailguilddismiss")]
    public long Mailguilddismiss { get; set; }
    [JsonPropertyName("mailquitbyboss")]
    public long Mailquitbyboss { get; set; }
    [JsonPropertyName("mailquitbyself")]
    public long Mailquitbyself { get; set; }
    [JsonPropertyName("mailtaskreward")]
    public long Mailtaskreward { get; set; }
    [JsonPropertyName("notewordnum")]
    public long Notewordnum { get; set; }
    [JsonPropertyName("publicitycost")]
    public List<object>? Publicitycost { get; set; }
    [JsonPropertyName("quittime")]
    public long Quittime { get; set; }
    [JsonPropertyName("rewardcutofftime")]
    public long Rewardcutofftime { get; set; }
    [JsonPropertyName("rewardduration")]
    public long Rewardduration { get; set; }
    [JsonPropertyName("show_task_num")]
    public long ShowTaskNum { get; set; }
    [JsonPropertyName("tasduration")]
    public long Tasduration { get; set; }
    [JsonPropertyName("task_refresh")]
    public long TaskRefresh { get; set; }
    [JsonPropertyName("taskcurrency")]
    public long Taskcurrency { get; set; }
}
