// <auto-generated />
// Table: config_achievement_type_id (rows: 49)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAchievementTypeId
{
    [JsonPropertyName("id")]
    public List<long>? Id { get; set; }
    [JsonPropertyName("type_id")]
    public long TypeId { get; set; }
}
