// <auto-generated />
// Table: config_battle_torpedogun_combo (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleTorpedogunCombo
{
    [JsonPropertyName("damage_factors")]
    public double DamageFactors { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_times")]
    public long MaxTimes { get; set; }
}
