// <auto-generated />
// Table: config_assess (rows: 16)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAssess
{
    [JsonPropertyName("A_para")]
    public string? APara { get; set; }
    [JsonPropertyName("A_tips")]
    public string? ATips { get; set; }
    [JsonPropertyName("B_para")]
    public string? BPara { get; set; }
    [JsonPropertyName("B_tips")]
    public string? BTips { get; set; }
    [JsonPropertyName("C_para")]
    public string? CPara { get; set; }
    [JsonPropertyName("C_tips")]
    public string? CTips { get; set; }
    [JsonPropertyName("D_para")]
    public string? DPara { get; set; }
    [JsonPropertyName("D_tips")]
    public string? DTips { get; set; }
    [JsonPropertyName("E_para")]
    public string? EPara { get; set; }
    [JsonPropertyName("E_tips")]
    public string? ETips { get; set; }
    [JsonPropertyName("F_para")]
    public string? FPara { get; set; }
    [JsonPropertyName("F_tips")]
    public string? FTips { get; set; }
    [JsonPropertyName("SSS_para")]
    public string? SSSPara { get; set; }
    [JsonPropertyName("SSS_tips")]
    public string? SSSTips { get; set; }
    [JsonPropertyName("SS_para")]
    public string? SSPara { get; set; }
    [JsonPropertyName("SS_tips")]
    public string? SSTips { get; set; }
    [JsonPropertyName("S_para")]
    public string? SPara { get; set; }
    [JsonPropertyName("S_tips")]
    public string? STips { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
}
