// <auto-generated />
// Table: config_sportsmeet_award (rows: 22)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSportsmeetAward
{
    [JsonPropertyName("hot_point")]
    public long HotPoint { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("score")]
    public long Score { get; set; }
}
