// <auto-generated />
// Table: config_battlepass_task (rows: 17)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattlepassTask
{
    [JsonPropertyName("battlepass_exp")]
    public long BattlepassExp { get; set; }
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("go_up_to_parm")]
    public List<object>? GoUpToParm { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("task_goal")]
    public List<long>? TaskGoal { get; set; }
    [JsonPropertyName("task_name")]
    public string? TaskName { get; set; }
    [JsonPropertyName("task_type")]
    public long TaskType { get; set; }
    [JsonPropertyName("task_type_name")]
    public string? TaskTypeName { get; set; }
}
