// <auto-generated />
// Table: config_random_factor_target_type (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRandomFactorTargetType
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("table_index")]
    public string? TableIndex { get; set; }
}
