// <auto-generated />
// Table: config_minigame_item (rows: 14)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMinigameItem
{
    [JsonPropertyName("buff_id")]
    public List<long>? BuffId { get; set; }
    [JsonPropertyName("effect_desc")]
    public string? EffectDesc { get; set; }
    [JsonPropertyName("effect_path")]
    public string? EffectPath { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("p1")]
    public List<object>? P1 { get; set; }
    [JsonPropertyName("p2")]
    public List<long>? P2 { get; set; }
    [JsonPropertyName("position")]
    public List<double>? Position { get; set; }
    [JsonPropertyName("respath")]
    public string? Respath { get; set; }
    [JsonPropertyName("size")]
    public List<double>? Size { get; set; }
    [JsonPropertyName("template")]
    public long Template { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
    [JsonPropertyName("ui_resource")]
    public string? UiResource { get; set; }
}
