// <auto-generated />
// Table: config_ship_dressup (rows: 749)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipDressup
{
    [JsonPropertyName("battle_effects")]
    public List<string>? BattleEffects { get; set; }
    [JsonPropertyName("battle_hide")]
    public List<object>? BattleHide { get; set; }
    [JsonPropertyName("home_hide")]
    public List<string>? HomeHide { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("marry_hide")]
    public List<string>? MarryHide { get; set; }
    [JsonPropertyName("normal_effects")]
    public List<string>? NormalEffects { get; set; }
    [JsonPropertyName("settlement_hide")]
    public List<object>? SettlementHide { get; set; }
    [JsonPropertyName("ship_change_parts")]
    public List<string>? ShipChangeParts { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_parts_adress")]
    public List<string>? ShipPartsAdress { get; set; }
    [JsonPropertyName("ship_parts_adress_home")]
    public List<string>? ShipPartsAdressHome { get; set; }
}
