// <auto-generated />
// Table: config_ship_main (rows: 4809)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipMain
{
    [JsonPropertyName("airAttack_stg_id")]
    public long AirAttackStgId { get; set; }
    [JsonPropertyName("air_combat_coefficient")]
    public long AirCombatCoefficient { get; set; }
    [JsonPropertyName("angle_speed")]
    public long AngleSpeed { get; set; }
    [JsonPropertyName("anti_crit")]
    public long AntiCrit { get; set; }
    [JsonPropertyName("antisubmarine")]
    public long Antisubmarine { get; set; }
    [JsonPropertyName("antisubmarine_levelup")]
    public long AntisubmarineLevelup { get; set; }
    [JsonPropertyName("attack")]
    public long Attack { get; set; }
    [JsonPropertyName("attack_levelup")]
    public long AttackLevelup { get; set; }
    [JsonPropertyName("attack_ship_coefficient")]
    public long AttackShipCoefficient { get; set; }
    [JsonPropertyName("backup_plane_count")]
    public long BackupPlaneCount { get; set; }
    [JsonPropertyName("battle_angle_speed")]
    public long BattleAngleSpeed { get; set; }
    [JsonPropertyName("break_down_get")]
    public List<List<long>>? BreakDownGet { get; set; }
    [JsonPropertyName("break_level")]
    public long BreakLevel { get; set; }
    [JsonPropertyName("carry_plane_count")]
    public long CarryPlaneCount { get; set; }
    [JsonPropertyName("character")]
    public List<long>? Character { get; set; }
    [JsonPropertyName("characterlevel")]
    public List<long>? Characterlevel { get; set; }
    [JsonPropertyName("charactermaxlevel")]
    public List<List<long>>? Charactermaxlevel { get; set; }
    [JsonPropertyName("condition_activate_talent_id")]
    public List<object>? ConditionActivateTalentId { get; set; }
    [JsonPropertyName("crit")]
    public long Crit { get; set; }
    [JsonPropertyName("defense")]
    public long Defense { get; set; }
    [JsonPropertyName("defense_levelup")]
    public long DefenseLevelup { get; set; }
    [JsonPropertyName("direct_activate_talent_id")]
    public List<long>? DirectActivateTalentId { get; set; }
    [JsonPropertyName("dodge")]
    public long Dodge { get; set; }
    [JsonPropertyName("drop_path")]
    public List<long>? DropPath { get; set; }
    [JsonPropertyName("extract_get_exceed_count")]
    public long ExtractGetExceedCount { get; set; }
    [JsonPropertyName("extract_get_exceed_reward")]
    public long ExtractGetExceedReward { get; set; }
    [JsonPropertyName("extract_reward")]
    public long ExtractReward { get; set; }
    [JsonPropertyName("fate")]
    public long Fate { get; set; }
    [JsonPropertyName("favorite_gift")]
    public List<long>? FavoriteGift { get; set; }
    [JsonPropertyName("fire_coefficient")]
    public long FireCoefficient { get; set; }
    [JsonPropertyName("fixed_money")]
    public long FixedMoney { get; set; }
    [JsonPropertyName("hit")]
    public long Hit { get; set; }
    [JsonPropertyName("hp")]
    public long Hp { get; set; }
    [JsonPropertyName("hp_levelup")]
    public long HpLevelup { get; set; }
    [JsonPropertyName("level_value_effect")]
    public List<long>? LevelValueEffect { get; set; }
    [JsonPropertyName("main_gun_available")]
    public long MainGunAvailable { get; set; }
    [JsonPropertyName("main_gun_cd")]
    public long MainGunCd { get; set; }
    [JsonPropertyName("main_gun_range")]
    public long MainGunRange { get; set; }
    [JsonPropertyName("main_gun_stg_id")]
    public long MainGunStgId { get; set; }
    [JsonPropertyName("match_value_group")]
    public List<long>? MatchValueGroup { get; set; }
    [JsonPropertyName("not_match_value_group")]
    public List<long>? NotMatchValueGroup { get; set; }
    [JsonPropertyName("opentorpedo_projectiles")]
    public long OpentorpedoProjectiles { get; set; }
    [JsonPropertyName("param_list")]
    public List<List<double>>? ParamList { get; set; }
    [JsonPropertyName("plane_bomb")]
    public long PlaneBomb { get; set; }
    [JsonPropertyName("plane_health")]
    public long PlaneHealth { get; set; }
    [JsonPropertyName("plane_to_air")]
    public long PlaneToAir { get; set; }
    [JsonPropertyName("plane_torpedo")]
    public long PlaneTorpedo { get; set; }
    [JsonPropertyName("projectiles")]
    public List<long>? Projectiles { get; set; }
    [JsonPropertyName("pskill_show_id")]
    public List<long>? PskillShowId { get; set; }
    [JsonPropertyName("pskill_sp_talent_id")]
    public List<object>? PskillSpTalentId { get; set; }
    [JsonPropertyName("script_list")]
    public List<string>? ScriptList { get; set; }
    [JsonPropertyName("second_gun_available")]
    public long SecondGunAvailable { get; set; }
    [JsonPropertyName("ship_air_control")]
    public long ShipAirControl { get; set; }
    [JsonPropertyName("ship_air_control_levelup")]
    public long ShipAirControlLevelup { get; set; }
    [JsonPropertyName("ship_bomb_attack")]
    public long ShipBombAttack { get; set; }
    [JsonPropertyName("ship_bomb_attack_levelup")]
    public long ShipBombAttackLevelup { get; set; }
    [JsonPropertyName("ship_class")]
    public long ShipClass { get; set; }
    [JsonPropertyName("ship_info_id")]
    public long ShipInfoId { get; set; }
    [JsonPropertyName("ship_levelup_max")]
    public long ShipLevelupMax { get; set; }
    [JsonPropertyName("ship_tag_array")]
    public List<long>? ShipTagArray { get; set; }
    [JsonPropertyName("ship_torpedo_attack")]
    public long ShipTorpedoAttack { get; set; }
    [JsonPropertyName("ship_torpedo_attack_levelup")]
    public long ShipTorpedoAttackLevelup { get; set; }
    [JsonPropertyName("ship_type2")]
    public long ShipType2 { get; set; }
    [JsonPropertyName("ship_weapon")]
    public string? ShipWeapon { get; set; }
    [JsonPropertyName("sm_id")]
    public long SmId { get; set; }
    [JsonPropertyName("speed")]
    public long Speed { get; set; }
    [JsonPropertyName("speed_show")]
    public long SpeedShow { get; set; }
    [JsonPropertyName("st_id")]
    public long StId { get; set; }
    [JsonPropertyName("submarine")]
    public long Submarine { get; set; }
    [JsonPropertyName("submarine_levelup")]
    public long SubmarineLevelup { get; set; }
    [JsonPropertyName("supple_cost")]
    public long SuppleCost { get; set; }
    [JsonPropertyName("to_air_attack")]
    public long ToAirAttack { get; set; }
    [JsonPropertyName("to_air_attack_levelup")]
    public long ToAirAttackLevelup { get; set; }
    [JsonPropertyName("to_torpedo_attack")]
    public long ToTorpedoAttack { get; set; }
    [JsonPropertyName("to_torpedo_attack_levelup")]
    public long ToTorpedoAttackLevelup { get; set; }
    [JsonPropertyName("torpedo_attack")]
    public long TorpedoAttack { get; set; }
    [JsonPropertyName("torpedo_attack_levelup")]
    public long TorpedoAttackLevelup { get; set; }
    [JsonPropertyName("torpedo_available")]
    public long TorpedoAvailable { get; set; }
    [JsonPropertyName("torpedo_coefficient")]
    public long TorpedoCoefficient { get; set; }
    [JsonPropertyName("torpedo_defense")]
    public long TorpedoDefense { get; set; }
    [JsonPropertyName("torpedo_defense_levelup")]
    public long TorpedoDefenseLevelup { get; set; }
    [JsonPropertyName("torpedo_num")]
    public long TorpedoNum { get; set; }
    [JsonPropertyName("torpedo_range")]
    public long TorpedoRange { get; set; }
    [JsonPropertyName("transform_id")]
    public long TransformId { get; set; }
    [JsonPropertyName("transform_list")]
    public List<long>? TransformList { get; set; }
    [JsonPropertyName("unlock_item")]
    public List<List<List<long>>>? UnlockItem { get; set; }
    [JsonPropertyName("view_range")]
    public long ViewRange { get; set; }
}
