// <auto-generated />
// Table: config_effect_bind (rows: 1187)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEffectBind
{
    [JsonPropertyName("audio_id")]
    public string? AudioId { get; set; }
    [JsonPropertyName("bind_type")]
    public long BindType { get; set; }
    [JsonPropertyName("delay_show_time")]
    public double DelayShowTime { get; set; }
    [JsonPropertyName("delay_time")]
    public double DelayTime { get; set; }
    [JsonPropertyName("eb_id")]
    public string? EbId { get; set; }
    [JsonPropertyName("ebp_id")]
    public string? EbpId { get; set; }
    [JsonPropertyName("effect_id")]
    public string? EffectId { get; set; }
    [JsonPropertyName("euler_delta_x")]
    public double EulerDeltaX { get; set; }
    [JsonPropertyName("euler_delta_y")]
    public double EulerDeltaY { get; set; }
    [JsonPropertyName("euler_delta_z")]
    public double EulerDeltaZ { get; set; }
    [JsonPropertyName("move_ebp_id")]
    public string? MoveEbpId { get; set; }
    [JsonPropertyName("pos_delta_x")]
    public double PosDeltaX { get; set; }
    [JsonPropertyName("pos_delta_y")]
    public double PosDeltaY { get; set; }
    [JsonPropertyName("pos_delta_z")]
    public double PosDeltaZ { get; set; }
    [JsonPropertyName("shield_axis")]
    public long ShieldAxis { get; set; }
}
