// <auto-generated />
// Table: config_equip_enhance_level_ur (rows: 35)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipEnhanceLevelUr
{
    [JsonPropertyName("enchance_level")]
    public long EnchanceLevel { get; set; }
    [JsonPropertyName("item_cost")]
    public List<List<long>>? ItemCost { get; set; }
}
