// <auto-generated />
// Table: config_ship_forbidden (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipForbidden
{
    [JsonPropertyName("forbidden_condition")]
    public List<long>? ForbiddenCondition { get; set; }
    [JsonPropertyName("forbidden_tips")]
    public List<long>? ForbiddenTips { get; set; }
    [JsonPropertyName("forbidden_type")]
    public List<long>? ForbiddenType { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
