// <auto-generated />
// Table: config_data_version (rows: 28)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDataVersion
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
