// <auto-generated />
// Table: config_random_first_name_ja (rows: 97)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigRandomFirstNameJa
{
    [JsonPropertyName("firstName")]
    public string? FirstName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
