// <auto-generated />
// Table: config_main_line_reward_arg (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigMainLineRewardArg
{
    [JsonPropertyName("character")]
    public string? Character { get; set; }
    [JsonPropertyName("enemy_hp_surplus_ratio_max")]
    public long EnemyHpSurplusRatioMax { get; set; }
    [JsonPropertyName("enemy_hp_surplus_ratio_min")]
    public long EnemyHpSurplusRatioMin { get; set; }
    [JsonPropertyName("enemy_survival_count_ratio_max")]
    public long EnemySurvivalCountRatioMax { get; set; }
    [JsonPropertyName("enemy_survival_count_ratio_min")]
    public long EnemySurvivalCountRatioMin { get; set; }
    [JsonPropertyName("exp_ratio")]
    public long ExpRatio { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_enemy_all_dead")]
    public long IsEnemyAllDead { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("other_drop_ratio")]
    public long OtherDropRatio { get; set; }
    [JsonPropertyName("self_has_any_sink")]
    public long SelfHasAnySink { get; set; }
    [JsonPropertyName("self_hp_reduce_ratio_max")]
    public long SelfHpReduceRatioMax { get; set; }
    [JsonPropertyName("self_hp_reduce_ratio_min")]
    public long SelfHpReduceRatioMin { get; set; }
    [JsonPropertyName("settle_drop_ratio")]
    public long SettleDropRatio { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
