// <auto-generated />
// Table: config_battle_logic_trigger_result (rows: 142)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleLogicTriggerResult
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("result_type")]
    public long ResultType { get; set; }
    [JsonPropertyName("target_dictid")]
    public string? TargetDictid { get; set; }
    [JsonPropertyName("target_type")]
    public long TargetType { get; set; }
}
