// <auto-generated />
// Table: config_supply_get (rows: 2)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSupplyGet
{
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("reward")]
    public List<long>? Reward { get; set; }
    [JsonPropertyName("time")]
    public List<long>? Time { get; set; }
}
