// <auto-generated />
// Table: config_battlefield_info (rows: 214)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattlefieldInfo
{
    [JsonPropertyName("assist_fleet_position")]
    public List<string>? AssistFleetPosition { get; set; }
    [JsonPropertyName("battlefield_shape")]
    public long BattlefieldShape { get; set; }
    [JsonPropertyName("enemy_position")]
    public List<string>? EnemyPosition { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("player_fleet_position")]
    public List<object>? PlayerFleetPosition { get; set; }
    [JsonPropertyName("player_position")]
    public string? PlayerPosition { get; set; }
    [JsonPropertyName("shape_param")]
    public string? ShapeParam { get; set; }
}
