// <auto-generated />
// Table: config_build_ship (rows: 30)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuildShip
{
    [JsonPropertyName("build_quality_id")]
    public long BuildQualityId { get; set; }
    [JsonPropertyName("custom_tag")]
    public List<long>? CustomTag { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("package_weight")]
    public long PackageWeight { get; set; }
    [JsonPropertyName("res1")]
    public List<long>? Res1 { get; set; }
    [JsonPropertyName("res2")]
    public List<long>? Res2 { get; set; }
    [JsonPropertyName("res2_package_weight_arg")]
    public long Res2PackageWeightArg { get; set; }
    [JsonPropertyName("res3")]
    public List<long>? Res3 { get; set; }
    [JsonPropertyName("res3_package_weight_arg")]
    public long Res3PackageWeightArg { get; set; }
    [JsonPropertyName("ship_list")]
    public List<long>? ShipList { get; set; }
    [JsonPropertyName("ship_ratio")]
    public List<long>? ShipRatio { get; set; }
}
