// <auto-generated />
// Table: config_skill_trigger_group (rows: 32)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillTriggerGroup
{
    [JsonPropertyName("create_pos_type")]
    public long CreatePosType { get; set; }
    [JsonPropertyName("fill_prefab_path")]
    public string? FillPrefabPath { get; set; }
    [JsonPropertyName("follow_target")]
    public long FollowTarget { get; set; }
    [JsonPropertyName("hit_prefab_path")]
    public string? HitPrefabPath { get; set; }
    [JsonPropertyName("move_euler_speed")]
    public long MoveEulerSpeed { get; set; }
    [JsonPropertyName("move_speed")]
    public double MoveSpeed { get; set; }
    [JsonPropertyName("range")]
    public long Range { get; set; }
    [JsonPropertyName("shape")]
    public long Shape { get; set; }
    [JsonPropertyName("shape_num")]
    public long ShapeNum { get; set; }
    [JsonPropertyName("shape_scale_min")]
    public long ShapeScaleMin { get; set; }
    [JsonPropertyName("shape_scale_time")]
    public long ShapeScaleTime { get; set; }
    [JsonPropertyName("shape_size")]
    public long ShapeSize { get; set; }
    [JsonPropertyName("stg_id")]
    public long StgId { get; set; }
    [JsonPropertyName("trigger_prefab_path")]
    public string? TriggerPrefabPath { get; set; }
    [JsonPropertyName("trigger_time")]
    public long TriggerTime { get; set; }
    [JsonPropertyName("wait_time")]
    public long WaitTime { get; set; }
}
