// <auto-generated />
// Table: config_battle_maingun_clip (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleMaingunClip
{
    [JsonPropertyName("damage_factors")]
    public List<long>? DamageFactors { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_num")]
    public long MaxNum { get; set; }
    [JsonPropertyName("select_mode")]
    public long SelectMode { get; set; }
}
