// <auto-generated />
// Table: config_activity_type (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigActivityType
{
    [JsonPropertyName("banner_goto")]
    public string? BannerGoto { get; set; }
    [JsonPropertyName("banner_order")]
    public long BannerOrder { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_open")]
    public long IsOpen { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("red_dot")]
    public List<long>? RedDot { get; set; }
}
