// <auto-generated />
// Table: config_ship_position (rows: 782)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipPosition
{
    [JsonPropertyName("affection_inversion")]
    public long AffectionInversion { get; set; }
    [JsonPropertyName("affection_position")]
    public List<double>? AffectionPosition { get; set; }
    [JsonPropertyName("affection_scale")]
    public long AffectionScale { get; set; }
    [JsonPropertyName("character_story_inversion")]
    public long CharacterStoryInversion { get; set; }
    [JsonPropertyName("character_story_position")]
    public List<double>? CharacterStoryPosition { get; set; }
    [JsonPropertyName("character_story_scale")]
    public long CharacterStoryScale { get; set; }
    [JsonPropertyName("cutin_inversion")]
    public long CutinInversion { get; set; }
    [JsonPropertyName("cutin_position")]
    public List<long>? CutinPosition { get; set; }
    [JsonPropertyName("cutin_scale")]
    public long CutinScale { get; set; }
    [JsonPropertyName("draw_inversion")]
    public long DrawInversion { get; set; }
    [JsonPropertyName("draw_position")]
    public List<double>? DrawPosition { get; set; }
    [JsonPropertyName("draw_scale")]
    public long DrawScale { get; set; }
    [JsonPropertyName("fashion_inversion1")]
    public long FashionInversion1 { get; set; }
    [JsonPropertyName("fashion_position1")]
    public List<double>? FashionPosition1 { get; set; }
    [JsonPropertyName("fashion_scale1")]
    public long FashionScale1 { get; set; }
    [JsonPropertyName("fashion_shop_inversion")]
    public long FashionShopInversion { get; set; }
    [JsonPropertyName("fashion_shop_position")]
    public List<double>? FashionShopPosition { get; set; }
    [JsonPropertyName("fashion_shop_scale")]
    public long FashionShopScale { get; set; }
    [JsonPropertyName("item_selected_inversion")]
    public long ItemSelectedInversion { get; set; }
    [JsonPropertyName("item_selected_position")]
    public List<long>? ItemSelectedPosition { get; set; }
    [JsonPropertyName("item_selected_scale")]
    public long ItemSelectedScale { get; set; }
    [JsonPropertyName("model_position")]
    public List<double>? ModelPosition { get; set; }
    [JsonPropertyName("recommend_inversion")]
    public long RecommendInversion { get; set; }
    [JsonPropertyName("recommend_position")]
    public List<long>? RecommendPosition { get; set; }
    [JsonPropertyName("recommend_scale")]
    public long RecommendScale { get; set; }
    [JsonPropertyName("resume_inversion")]
    public long ResumeInversion { get; set; }
    [JsonPropertyName("resume_position")]
    public List<double>? ResumePosition { get; set; }
    [JsonPropertyName("resume_scale")]
    public long ResumeScale { get; set; }
    [JsonPropertyName("sf_id")]
    public long SfId { get; set; }
    [JsonPropertyName("ship_inversion1")]
    public long ShipInversion1 { get; set; }
    [JsonPropertyName("ship_inversion2")]
    public long ShipInversion2 { get; set; }
    [JsonPropertyName("ship_inversion3")]
    public long ShipInversion3 { get; set; }
    [JsonPropertyName("ship_name")]
    public string? ShipName { get; set; }
    [JsonPropertyName("ship_position1")]
    public List<double>? ShipPosition1 { get; set; }
    [JsonPropertyName("ship_position2")]
    public List<double>? ShipPosition2 { get; set; }
    [JsonPropertyName("ship_position3")]
    public List<double>? ShipPosition3 { get; set; }
    [JsonPropertyName("ship_scale1")]
    public long ShipScale1 { get; set; }
    [JsonPropertyName("ship_scale2")]
    public long ShipScale2 { get; set; }
    [JsonPropertyName("ship_scale3")]
    public long ShipScale3 { get; set; }
    [JsonPropertyName("ship_type")]
    public long ShipType { get; set; }
    [JsonPropertyName("si_id")]
    public long SiId { get; set; }
    [JsonPropertyName("support_fleet_inversion4")]
    public long SupportFleetInversion4 { get; set; }
    [JsonPropertyName("support_fleet_position4")]
    public List<double>? SupportFleetPosition4 { get; set; }
    [JsonPropertyName("support_fleet_scale4")]
    public long SupportFleetScale4 { get; set; }
    [JsonPropertyName("wish_advance_inversion")]
    public long WishAdvanceInversion { get; set; }
    [JsonPropertyName("wish_advance_position")]
    public List<long>? WishAdvancePosition { get; set; }
    [JsonPropertyName("wish_advance_scale")]
    public long WishAdvanceScale { get; set; }
}
