// <auto-generated />
// Table: config_battle_config (rows: 326)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleConfig
{
    [JsonPropertyName("data")]
    public string? Data { get; set; }
    [JsonPropertyName("data_double")]
    public double DataDouble { get; set; }
    [JsonPropertyName("data_int")]
    public long DataInt { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("enum_name")]
    public string? EnumName { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
}
