// <auto-generated />
// Table: config_pskill_dict_factor (rows: 1256)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPskillDictFactor
{
    [JsonPropertyName("export_func")]
    public string? ExportFunc { get; set; }
    [JsonPropertyName("export_odds_add")]
    public double ExportOddsAdd { get; set; }
    [JsonPropertyName("export_odds_base")]
    public long ExportOddsBase { get; set; }
    [JsonPropertyName("export_target_prop_id")]
    public long ExportTargetPropId { get; set; }
    [JsonPropertyName("export_type")]
    public long ExportType { get; set; }
    [JsonPropertyName("general_formula")]
    public long GeneralFormula { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("operation_buff_dict_id")]
    public List<long>? OperationBuffDictId { get; set; }
    [JsonPropertyName("operation_flag_dict_id")]
    public List<long>? OperationFlagDictId { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("select_mode")]
    public long SelectMode { get; set; }
    [JsonPropertyName("select_target_array")]
    public List<long>? SelectTargetArray { get; set; }
}
