// <auto-generated />
// Table: config_task_activity (rows: 1692)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigTaskActivity
{
    [JsonPropertyName("accumulate")]
    public List<long>? Accumulate { get; set; }
    [JsonPropertyName("activity_id")]
    public long ActivityId { get; set; }
    [JsonPropertyName("auto_send")]
    public long AutoSend { get; set; }
    [JsonPropertyName("count_type")]
    public long CountType { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("desc_language")]
    public long DescLanguage { get; set; }
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("go_up_to")]
    public long GoUpTo { get; set; }
    [JsonPropertyName("go_up_to_parm")]
    public List<long>? GoUpToParm { get; set; }
    [JsonPropertyName("goal")]
    public List<long>? Goal { get; set; }
    [JsonPropertyName("hide")]
    public long Hide { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("label")]
    public long Label { get; set; }
    [JsonPropertyName("last_task")]
    public long LastTask { get; set; }
    [JsonPropertyName("last_task_client")]
    public long LastTaskClient { get; set; }
    [JsonPropertyName("last_task_receive")]
    public long LastTaskReceive { get; set; }
    [JsonPropertyName("order")]
    public long Order { get; set; }
    [JsonPropertyName("period")]
    public long Period { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("period_list")]
    public List<object>? PeriodList { get; set; }
    [JsonPropertyName("period_list_area")]
    public List<object>? PeriodListArea { get; set; }
    [JsonPropertyName("refresh_id")]
    public long RefreshId { get; set; }
    [JsonPropertyName("rewards")]
    public long Rewards { get; set; }
    [JsonPropertyName("show_reward_num")]
    public long ShowRewardNum { get; set; }
    [JsonPropertyName("show_rewards")]
    public long ShowRewards { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
}
