// <auto-generated />
// Table: config_effect_bind_path (rows: 396)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEffectBindPath
{
    [JsonPropertyName("ebp_id")]
    public long EbpId { get; set; }
    [JsonPropertyName("model_path")]
    public string? ModelPath { get; set; }
}
