// <auto-generated />
// Table: config_chapter_type_info (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChapterTypeInfo
{
    [JsonPropertyName("check_image")]
    public string? CheckImage { get; set; }
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("locked_image")]
    public string? LockedImage { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("unchecked_image")]
    public string? UncheckedImage { get; set; }
}
