// <auto-generated />
// Table: config_battle_ai (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAi
{
    [JsonPropertyName("aerial_search_duration")]
    public long AerialSearchDuration { get; set; }
    [JsonPropertyName("ba_id")]
    public string? BaId { get; set; }
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("escape_odds")]
    public double EscapeOdds { get; set; }
    [JsonPropertyName("f_id")]
    public string? FId { get; set; }
    [JsonPropertyName("skill_cd")]
    public long SkillCd { get; set; }
    [JsonPropertyName("speed_ratio")]
    public double SpeedRatio { get; set; }
    [JsonPropertyName("t_odds")]
    public double TOdds { get; set; }
    [JsonPropertyName("track_dis")]
    public long TrackDis { get; set; }
    [JsonPropertyName("track_range")]
    public long TrackRange { get; set; }
    [JsonPropertyName("view_euler")]
    public long ViewEuler { get; set; }
    [JsonPropertyName("view_range")]
    public long ViewRange { get; set; }
}
