// <auto-generated />
// Table: config_vow_wall_ship (rows: 8)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigVowWallShip
{
    [JsonPropertyName("vow_pos_id")]
    public long VowPosId { get; set; }
    [JsonPropertyName("vow_pos_x")]
    public long VowPosX { get; set; }
    [JsonPropertyName("vow_pos_y")]
    public long VowPosY { get; set; }
    [JsonPropertyName("vow_shi_pin")]
    public string? VowShiPin { get; set; }
    [JsonPropertyName("vow_ship_kuang")]
    public string? VowShipKuang { get; set; }
    [JsonPropertyName("vow_wall")]
    public long VowWall { get; set; }
}
