// <auto-generated />
// Table: config_assess_condition (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigAssessCondition
{
    [JsonPropertyName("condition_func")]
    public string? ConditionFunc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("param_type")]
    public long ParamType { get; set; }
}
