// <auto-generated />
// Table: config_chapter (rows: 201)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChapter
{
    [JsonPropertyName("activate_by_default")]
    public long ActivateByDefault { get; set; }
    [JsonPropertyName("belong_chapter_list")]
    public List<long>? BelongChapterList { get; set; }
    [JsonPropertyName("big_activity_chapter_id")]
    public long BigActivityChapterId { get; set; }
    [JsonPropertyName("changechapterbtnhide")]
    public long Changechapterbtnhide { get; set; }
    [JsonPropertyName("chapter_details")]
    public string? ChapterDetails { get; set; }
    [JsonPropertyName("chapter_open")]
    public long ChapterOpen { get; set; }
    [JsonPropertyName("chapter_openname")]
    public string? ChapterOpenname { get; set; }
    [JsonPropertyName("chapter_period")]
    public long ChapterPeriod { get; set; }
    [JsonPropertyName("chapter_periodarea")]
    public List<long>? ChapterPeriodarea { get; set; }
    [JsonPropertyName("chapter_plot_type")]
    public long ChapterPlotType { get; set; }
    [JsonPropertyName("chapter_type")]
    public long ChapterType { get; set; }
    [JsonPropertyName("class_name")]
    public string? ClassName { get; set; }
    [JsonPropertyName("class_type")]
    public long ClassType { get; set; }
    [JsonPropertyName("coordinate")]
    public List<double>? Coordinate { get; set; }
    [JsonPropertyName("copy_background")]
    public string? CopyBackground { get; set; }
    [JsonPropertyName("copy_background_2")]
    public string? CopyBackground2 { get; set; }
    [JsonPropertyName("copy_pos_x")]
    public List<double>? CopyPosX { get; set; }
    [JsonPropertyName("copy_pos_y")]
    public List<double>? CopyPosY { get; set; }
    [JsonPropertyName("dailygroup_id")]
    public long DailygroupId { get; set; }
    [JsonPropertyName("day_chapter")]
    public long DayChapter { get; set; }
    [JsonPropertyName("ex_id")]
    public long ExId { get; set; }
    [JsonPropertyName("help_info")]
    public long HelpInfo { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_available")]
    public long IsAvailable { get; set; }
    [JsonPropertyName("is_show")]
    public long IsShow { get; set; }
    [JsonPropertyName("level_list")]
    public List<long>? LevelList { get; set; }
    [JsonPropertyName("leveldetailsbgm")]
    public string? Leveldetailsbgm { get; set; }
    [JsonPropertyName("memory_id")]
    public long MemoryId { get; set; }
    [JsonPropertyName("memory_start")]
    public long MemoryStart { get; set; }
    [JsonPropertyName("mubarcopy_chapter_image01")]
    public string? MubarcopyChapterImage01 { get; set; }
    [JsonPropertyName("mubarcopy_chapter_image02")]
    public string? MubarcopyChapterImage02 { get; set; }
    [JsonPropertyName("mubarcopy_data")]
    public List<List<string>>? MubarcopyData { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("name2")]
    public string? Name2 { get; set; }
    [JsonPropertyName("new_ocean_tag")]
    public long NewOceanTag { get; set; }
    [JsonPropertyName("next_chapter")]
    public long NextChapter { get; set; }
    [JsonPropertyName("night_chapter")]
    public long NightChapter { get; set; }
    [JsonPropertyName("open_chapter")]
    public List<long>? OpenChapter { get; set; }
    [JsonPropertyName("outpost_id")]
    public long OutpostId { get; set; }
    [JsonPropertyName("plot_copy_cover")]
    public string? PlotCopyCover { get; set; }
    [JsonPropertyName("plot_locked")]
    public string? PlotLocked { get; set; }
    [JsonPropertyName("prev_chapter")]
    public long PrevChapter { get; set; }
    [JsonPropertyName("pve_copy")]
    public List<long>? PveCopy { get; set; }
    [JsonPropertyName("relation_chapter_id")]
    public long RelationChapterId { get; set; }
    [JsonPropertyName("reward_times")]
    public long RewardTimes { get; set; }
    [JsonPropertyName("running_level_list")]
    public List<long>? RunningLevelList { get; set; }
    [JsonPropertyName("show_name")]
    public string? ShowName { get; set; }
    [JsonPropertyName("star_box")]
    public List<long>? StarBox { get; set; }
    [JsonPropertyName("star_cond")]
    public List<long>? StarCond { get; set; }
    [JsonPropertyName("star_reward")]
    public List<long>? StarReward { get; set; }
    [JsonPropertyName("starbox_cosy")]
    public double StarboxCosy { get; set; }
    [JsonPropertyName("starimage")]
    public List<string>? Starimage { get; set; }
    [JsonPropertyName("starpositionx")]
    public List<long>? Starpositionx { get; set; }
    [JsonPropertyName("tactic_type")]
    public long TacticType { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("training_chapter_id")]
    public long TrainingChapterId { get; set; }
    [JsonPropertyName("treaty_copy")]
    public List<long>? TreatyCopy { get; set; }
    [JsonPropertyName("treaty_open_copy")]
    public List<long>? TreatyOpenCopy { get; set; }
}
