// <auto-generated />
// Table: config_equip_fashion_showtype (rows: 5)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipFashionShowtype
{
    [JsonPropertyName("fashion_id")]
    public long FashionId { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("type_id")]
    public long TypeId { get; set; }
}
