// <auto-generated />
// Table: config_daily_group (rows: 4)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigDailyGroup
{
    [JsonPropertyName("basic_drop")]
    public List<List<long>>? BasicDrop { get; set; }
    [JsonPropertyName("chapterid")]
    public List<long>? Chapterid { get; set; }
    [JsonPropertyName("copy_background")]
    public List<string>? CopyBackground { get; set; }
    [JsonPropertyName("copy_button_deviation")]
    public List<long>? CopyButtonDeviation { get; set; }
    [JsonPropertyName("copy_dropinfo")]
    public string? CopyDropinfo { get; set; }
    [JsonPropertyName("drop_icon")]
    public string? DropIcon { get; set; }
    [JsonPropertyName("drop_info_id")]
    public List<List<long>>? DropInfoId { get; set; }
    [JsonPropertyName("extra_drop")]
    public List<List<long>>? ExtraDrop { get; set; }
    [JsonPropertyName("extra_drop_info_id")]
    public List<List<long>>? ExtraDropInfoId { get; set; }
    [JsonPropertyName("first_drop")]
    public List<long>? FirstDrop { get; set; }
    [JsonPropertyName("go_shopid")]
    public List<List<long>>? GoShopid { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("is_available")]
    public List<List<long>>? IsAvailable { get; set; }
    [JsonPropertyName("is_available_show")]
    public List<string>? IsAvailableShow { get; set; }
    [JsonPropertyName("lock_bg")]
    public string? LockBg { get; set; }
    [JsonPropertyName("period")]
    public List<long>? Period { get; set; }
    [JsonPropertyName("shop_id")]
    public List<long>? ShopId { get; set; }
    [JsonPropertyName("shop_name")]
    public List<string>? ShopName { get; set; }
    [JsonPropertyName("shopgoods_list")]
    public List<long>? ShopgoodsList { get; set; }
    [JsonPropertyName("show_draw_button")]
    public List<long>? ShowDrawButton { get; set; }
    [JsonPropertyName("title_icon")]
    public string? TitleIcon { get; set; }
    [JsonPropertyName("treaty_basic_drop_base")]
    public long TreatyBasicDropBase { get; set; }
    [JsonPropertyName("treaty_basic_drop_star")]
    public List<long>? TreatyBasicDropStar { get; set; }
    [JsonPropertyName("treaty_dropinfo_basic")]
    public List<List<long>>? TreatyDropinfoBasic { get; set; }
    [JsonPropertyName("treaty_dropinfo_extra")]
    public List<List<long>>? TreatyDropinfoExtra { get; set; }
    [JsonPropertyName("treaty_dropinfo_pass")]
    public List<long>? TreatyDropinfoPass { get; set; }
    [JsonPropertyName("treaty_extra_drop")]
    public List<long>? TreatyExtraDrop { get; set; }
    [JsonPropertyName("treaty_extra_drop_base")]
    public long TreatyExtraDropBase { get; set; }
    [JsonPropertyName("treaty_icon")]
    public string? TreatyIcon { get; set; }
    [JsonPropertyName("treaty_id")]
    public List<long>? TreatyId { get; set; }
    [JsonPropertyName("treaty_item")]
    public List<long>? TreatyItem { get; set; }
    [JsonPropertyName("treaty_pass_drop")]
    public long TreatyPassDrop { get; set; }
    [JsonPropertyName("treaty_show_buff")]
    public List<long>? TreatyShowBuff { get; set; }
    [JsonPropertyName("unlock_extract_ship_id")]
    public List<long>? UnlockExtractShipId { get; set; }
    [JsonPropertyName("unlock_ship_reward")]
    public List<long>? UnlockShipReward { get; set; }
}
