// <auto-generated />
// Table: config_skill_anim_project (rows: 673)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimProject
{
    [JsonPropertyName("diff_name")]
    public string? DiffName { get; set; }
    [JsonPropertyName("enter_water_effects")]
    public List<string>? EnterWaterEffects { get; set; }
    [JsonPropertyName("group")]
    public string? Group { get; set; }
    [JsonPropertyName("path")]
    public string? Path { get; set; }
    [JsonPropertyName("sap_id")]
    public string? SapId { get; set; }
    [JsonPropertyName("skill_project_duration")]
    public double SkillProjectDuration { get; set; }
    [JsonPropertyName("skill_project_fly_time")]
    public double SkillProjectFlyTime { get; set; }
    [JsonPropertyName("skill_project_ids")]
    public List<string>? SkillProjectIds { get; set; }
    [JsonPropertyName("skill_project_start_time")]
    public double SkillProjectStartTime { get; set; }
    [JsonPropertyName("skill_project_type")]
    public string? SkillProjectType { get; set; }
    [JsonPropertyName("skill_project_type2")]
    public string? SkillProjectType2 { get; set; }
}
