// <auto-generated />
// Table: config_interaction_paper_cut_fomula (rows: 126)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigInteractionPaperCutFomula
{
    [JsonPropertyName("drop_id")]
    public long DropId { get; set; }
    [JsonPropertyName("formula")]
    public List<long>? Formula { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("paper_cut")]
    public long PaperCut { get; set; }
    [JsonPropertyName("paper_cut_light_image")]
    public string? PaperCutLightImage { get; set; }
    [JsonPropertyName("paper_cut_main_image")]
    public string? PaperCutMainImage { get; set; }
    [JsonPropertyName("paper_cut_word_image")]
    public string? PaperCutWordImage { get; set; }
}
