// <auto-generated />
// Table: config_privilegedesc (rows: 18)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigPrivilegedesc
{
    [JsonPropertyName("desc")]
    public string? Desc { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("texttitle")]
    public string? Texttitle { get; set; }
}
