// <auto-generated />
// Table: config_cutin_ship_type_factor (rows: 22)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigCutinShipTypeFactor
{
    [JsonPropertyName("damage_factor")]
    public long DamageFactor { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("ship_type_id")]
    public long ShipTypeId { get; set; }
}
