// <auto-generated />
// Table: config_chapter_type (rows: 61)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigChapterType
{
    [JsonPropertyName("affection_add")]
    public long AffectionAdd { get; set; }
    [JsonPropertyName("affection_change_sort")]
    public long AffectionChangeSort { get; set; }
    [JsonPropertyName("affection_flagship_add")]
    public long AffectionFlagshipAdd { get; set; }
    [JsonPropertyName("affection_mvp_add")]
    public long AffectionMvpAdd { get; set; }
    [JsonPropertyName("affection_reduce")]
    public long AffectionReduce { get; set; }
    [JsonPropertyName("check_strategy")]
    public long CheckStrategy { get; set; }
    [JsonPropertyName("dot_key")]
    public string? DotKey { get; set; }
    [JsonPropertyName("ex_ids")]
    public List<long>? ExIds { get; set; }
    [JsonPropertyName("function_id")]
    public long FunctionId { get; set; }
    [JsonPropertyName("mood_reduce")]
    public long MoodReduce { get; set; }
    [JsonPropertyName("mood_shipwrecks_reduce")]
    public long MoodShipwrecksReduce { get; set; }
    [JsonPropertyName("not_effect_curriculum_vitae")]
    public long NotEffectCurriculumVitae { get; set; }
    [JsonPropertyName("not_effect_task")]
    public long NotEffectTask { get; set; }
    [JsonPropertyName("open_copydisplay")]
    public long OpenCopydisplay { get; set; }
    [JsonPropertyName("period_area")]
    public List<long>? PeriodArea { get; set; }
    [JsonPropertyName("period_id")]
    public long PeriodId { get; set; }
    [JsonPropertyName("start_chapter")]
    public long StartChapter { get; set; }
    [JsonPropertyName("top_text")]
    public string? TopText { get; set; }
}
