// <auto-generated />
// Table: config_equip_enhance_level (rows: 30)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigEquipEnhanceLevel
{
    [JsonPropertyName("enchance_level")]
    public long EnchanceLevel { get; set; }
    [JsonPropertyName("exp")]
    public long Exp { get; set; }
}
