// <auto-generated />
// Table: config_weather_group (rows: 6)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigWeatherGroup
{
    [JsonPropertyName("copy_tip")]
    public long CopyTip { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("scene_res_name")]
    public string? SceneResName { get; set; }
    [JsonPropertyName("trigger")]
    public long Trigger { get; set; }
    [JsonPropertyName("ui_copy_pic")]
    public string? UiCopyPic { get; set; }
    [JsonPropertyName("weather")]
    public List<long>? Weather { get; set; }
    [JsonPropertyName("weather_default")]
    public long WeatherDefault { get; set; }
    [JsonPropertyName("weather_weight")]
    public List<long>? WeatherWeight { get; set; }
}
