// <auto-generated />
// Table: config_battle_auto_chat (rows: 9)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBattleAutoChat
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("text")]
    public string? Text { get; set; }
}
