// <auto-generated />
// Table: config_skill_anim_detail_base_group (rows: 88)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSkillAnimDetailBaseGroup
{
    [JsonPropertyName("base_group_id")]
    public long BaseGroupId { get; set; }
    [JsonPropertyName("has_simple_behit")]
    public long HasSimpleBehit { get; set; }
    [JsonPropertyName("normal_group_id")]
    public long NormalGroupId { get; set; }
    [JsonPropertyName("normal_group_limit_id")]
    public List<long>? NormalGroupLimitId { get; set; }
    [JsonPropertyName("normal_hit_limit_id")]
    public List<long>? NormalHitLimitId { get; set; }
    [JsonPropertyName("pip_group_id")]
    public long PipGroupId { get; set; }
    [JsonPropertyName("pip_has_hit")]
    public long PipHasHit { get; set; }
    [JsonPropertyName("simple_group_id")]
    public long SimpleGroupId { get; set; }
}
