// <auto-generated />
// Table: config_food_compose (rows: 40)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFoodCompose
{
    [JsonPropertyName("hide")]
    public long Hide { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("item")]
    public List<long>? Item { get; set; }
    [JsonPropertyName("material")]
    public List<List<long>>? Material { get; set; }
    [JsonPropertyName("reward")]
    public List<long>? Reward { get; set; }
    [JsonPropertyName("type")]
    public long Type { get; set; }
}
