// <auto-generated />
// Table: config_stage (rows: 302)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigStage
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("max_safe")]
    public long MaxSafe { get; set; }
    [JsonPropertyName("safe_area")]
    public List<long>? SafeArea { get; set; }
    [JsonPropertyName("safe_area_score")]
    public List<long>? SafeAreaScore { get; set; }
    [JsonPropertyName("safe_condition")]
    public List<List<long>>? SafeCondition { get; set; }
    [JsonPropertyName("safe_effect")]
    public List<List<long>>? SafeEffect { get; set; }
    [JsonPropertyName("safe_effect_desc")]
    public List<long>? SafeEffectDesc { get; set; }
}
