// <auto-generated />
// Table: config_sp_settings_fleet_dict (rows: 3)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigSpSettingsFleetDict
{
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("sp_setting")]
    public List<List<long>>? SpSetting { get; set; }
    [JsonPropertyName("sp_setting_copy_id")]
    public long SpSettingCopyId { get; set; }
    [JsonPropertyName("sp_setting_fleet_id")]
    public long SpSettingFleetId { get; set; }
}
