// <auto-generated />
// Table: config_ship_provide_power_exp (rows: 5277)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigShipProvidePowerExp
{
    [JsonPropertyName("provide_power_exp")]
    public List<List<long>>? ProvidePowerExp { get; set; }
    [JsonPropertyName("sppe_id")]
    public long SppeId { get; set; }
}
