// <auto-generated />
// Table: config_building (rows: 10)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigBuilding
{
    [JsonPropertyName("buildinggroup_id")]
    public List<long>? BuildinggroupId { get; set; }
    [JsonPropertyName("defaultopening")]
    public long Defaultopening { get; set; }
    [JsonPropertyName("id")]
    public long Id { get; set; }
    [JsonPropertyName("officelevel")]
    public long Officelevel { get; set; }
}
