// <auto-generated />
// Table: config_function_info (rows: 104)
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BlueOath.Server.Configs;

public class ConfigFunctionInfo
{
    [JsonPropertyName("comment")]
    public string? Comment { get; set; }
    [JsonPropertyName("copy_id")]
    public long CopyId { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("fi_id")]
    public string? FiId { get; set; }
    [JsonPropertyName("focus")]
    public List<long>? Focus { get; set; }
    [JsonPropertyName("goto_parm")]
    public List<long>? GotoParm { get; set; }
    [JsonPropertyName("guideId")]
    public long GuideId { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("icon_Lock")]
    public long IconLock { get; set; }
    [JsonPropertyName("icon_effect")]
    public string? IconEffect { get; set; }
    [JsonPropertyName("icon_push")]
    public string? IconPush { get; set; }
    [JsonPropertyName("is_open")]
    public long IsOpen { get; set; }
    [JsonPropertyName("is_open_page")]
    public string? IsOpenPage { get; set; }
    [JsonPropertyName("is_tanchuang")]
    public long IsTanchuang { get; set; }
    [JsonPropertyName("level")]
    public long Level { get; set; }
    [JsonPropertyName("lookLevel")]
    public long LookLevel { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("open_show_name")]
    public string? OpenShowName { get; set; }
    [JsonPropertyName("orAnd")]
    public long OrAnd { get; set; }
    [JsonPropertyName("page_icon")]
    public string? PageIcon { get; set; }
    [JsonPropertyName("page_name")]
    public string? PageName { get; set; }
    [JsonPropertyName("page_name2")]
    public string? PageName2 { get; set; }
    [JsonPropertyName("sum_function")]
    public List<long>? SumFunction { get; set; }
    [JsonPropertyName("task_id")]
    public long TaskId { get; set; }
}
